### ISSUE TITLE
zero (0) value not appear when use format in DevExtreme grid

### ISSUE THREAD

**Issue by tegarjgap** [DevExpress/devextreme-angular#1011]
# Bug Report

**Package versions:**

    devexteme version: 18.2.7
    devextreme-angular version: 18.2.7

**Steps to reproduce:**

add format= '#,###.##' in grid column like this:
`   <dxi-column
                    dataField="yourDataField" 
                    dataType="number" 
                    format="#,###.##">
    <dxo-format type="fixedPoint" [precision]="2"></dxo-format>
    </dxi-column>`

and then type number that include **'0'** or paste number that include **'0'**.

**Current behavior:**

The zero value not appear.

**Expected behavior:**

The zero value must appear.

**Screenshots:**

![format_zero](https://user-images.githubusercontent.com/17794532/69128828-b0e4f080-0adf-11ea-8ec6-bd792d48c62d.gif)

**Comment by LexDX** [comment]
This is expected behavior. It is necessary to add a leading zero to the format to show 0 in a column. So, you can set the format in this way to resolve the issue:
`format="#,##0.##"`

**Comment by tegarjgap** [comment]
OK thanks @LexDX
