### ISSUE TITLE
Column grouping support on OData Data Source

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#1012]
Hi,
I noticed (watching the http traffic) that if I apply grouping on a grid binded to OData the grid will download ALL the data and than applies grouping on the client side.
In this way, if I have 1000000 records on the db, DevExtreme Grid downloads all the 1000000 items and then it will applies grouping.

Is there a way to apply grouping on the server side (as it should be)?

Thanks a lot

**Comment by LexDX** [comment]
Paging, filtering, and sorting are performed on the server side for ODataStore. Other operations are always client-side. Currently, ODataStore does not support server-side grouping. That is why grouping is performed on the client. Please refer to [ODataStore - Remote Aggregation Support GitHub page](https://github.com/DevExpress/DevExtreme/issues/7974) for additional details.

**Comment by maria-benson** [comment]
Hi, do we have server side grouping feature available now ?
