### ISSUE TITLE
Please enable CommonJS and AMD for Webpack development

### ISSUE THREAD

**Issue by alexsandro-xpt** [DevExpress/devextreme-angular#1027]
For SPA( Angular ) development, the async file load send a thank you. It's optimize and minimize page load and enable javascript module management.

**Comment by LexDX** [comment]
Hi All,

We follow the Angular Package format starting with version 19.2.5. You can find all supported formats in the following Angular documentation article: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit .
