### ISSUE TITLE
DxDataGrid Scrolling Virtual Mode Render

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular#103]
Hi,

When the first dataSource is setted in a not visible zone, the virtual mode doesn't work.

Example
TabPage 1 (Selected) Grid in Virtual Mode -> Works
TabPage 2 (Not Selected) Grid in Virtual Mode -> doesn't re render with the scroll. 

With 'standard' mode it draws aditional empty rows.
With pagination works as expected.

Similar to #81. Maybe if if works with max-heigth it will work inside the TabPanels.

Regards

**Comment by dxvladislavvolkov** [comment]
Hello! 
Could you please provide a code example to help us reproduce this behavior?

**Comment by Angelminster** [comment]
Hi,

This week can't provide an example. Next week maybe i can create a plunkr.

**Comment by dxbykov** [comment]
Several similar issues have been fixed (#81, #174). Please check this with the latest version of the devextreme-angular package. For now, I'm closing the issue. Do not hesitate to reopen it once it appears that your particular case still doesn't work.
