### ISSUE TITLE
Cannot resolve type entity i4.DxDataGridModule to symbol

### ISSUE THREAD

**Issue by JacopoSciampi** [DevExpress/devextreme-angular#1035]
# Bug Report

**Package versions:**

    devexteme version: 19.2.6
    devextreme-angular version: 19.2.6

**Steps to reproduce:**

- Build a basic library in angular 9 with DX
- build it
- import it in an angular 9 project that doesn't have the devExtreme in the dependencies
- ng serve

**Current behavior:**

I just get this error 

**Expected behavior:**

It shouldn't (?)

**Screenshots:**

**Comment by LexDX** [comment]
Hi @JacopoSciampi,

At the moment, it is not completely clear how to reproduce the issue on our side. Please send us a sample project that we can use and provide detailed steps to replicate it.

**Comment by LexDX** [comment]
I'm going to close this issue for now. Feel free to reactivate it once you can provide us with a sample project.
