### ISSUE TITLE
Module 'devextreme-angular' has no exported member 'DxiColumnComponent'

### ISSUE THREAD

**Issue by briosheje** [DevExpress/devextreme-angular#1043]
Since updating to 19.2.6 I had to replace all the occurres of DxiColumnComponent with a temporary `any`.

I was using DxiColumnComponent in `QueryList` to acquire rendered column instances only, so it's not a big deal.

However, I was wondering whether there is any changelog or whatever mentioning changes against such models or so, otherwise it would be better to actually mention which classes / interfaces becomes obsolete or unusable after an update.

**Comment by artem-kurchenko** [comment]
Hi,

We changed the package format in the context of this [Breaking Change](https://supportcenter.devexpress.com/internal/ticket/details/T845070) to support recent Angular changes (version 9 and Ivy renderer).

All nested components like `DxiColumnComponent` were not documented. Therefore, we didn't publish a changeset for them. 

The new format allows you to use only the following paths:

- The `devextreme-angular` and `devextreme-angular/ui` folders contain our official components. 
- The `devextreme-angular/core` and `devextreme-angular/ui/nested` folders contain all internal components.

**Comment by briosheje** [comment]
> Hi,
> 
> We changed the package format in the context of this [Breaking Change](https://supportcenter.devexpress.com/internal/ticket/details/T845070) to support recent Angular changes (version 9 and Ivy renderer).
> 
> All nested components like `DxiColumnComponent` were not documented. Therefore, we didn't publish a changeset for them.
> 
> The new format allows you to use only the following paths:
> 
> * The `devextreme-angular` and `devextreme-angular/ui` folders contain our official components.
> * The `devextreme-angular/core` and `devextreme-angular/ui/nested` folders contain all internal components.

Ok, that's fair.

However, my question still remains whether there is any selector available that I may use to replace DxiColumnComponent: importing from either devextreme-angular or devextreme-angular/core does not seem to work, unless I'm doing something wrong.

**Comment by artem-kurchenko** [comment]
Try importing this component as follows:

`` 
import {  DxiColumnComponent } from "devextreme-angular/ui/nested";
``

Could you please clarify for what scenario you're using it in your application? 

This information would be helpful if we decide to publish it.

**Comment by briosheje** [comment]
> Try importing this component as follows:
> 
> ` import { DxiColumnComponent } from "devextreme-angular/ui/nested";`
> 
> Could you please clarify for what scenario you're using it in your application?
> 
> This information would be helpful if we decide to publish it.

Sorry for the late answer, I was quite busy in these days.

I was using that to select rendered columns using QueryList, like this:

```
@ViewChildren(DxiColumnComponent) public DataGridColumns: QueryList<DxiColumnComponent>;
```

I didn't yet try using `DxiColumnComponent` from `ui/nested`, I probably won't try that until I have enough time to work and test the whole application again, which probably won't happen that soon (it's currently stable enough).

I will update you once I've tested it, although currently, as a solution, I've just marked it as `any` and used a getter that casts to an interface which is working fine.
