### ISSUE TITLE
ngAfterViewChecked trigger all time when mouse move on diagram widget

### ISSUE THREAD

**Issue by fgvicente** [DevExpress/devextreme-angular#1048]
I am testing the angular diagram and detected a problem. The change detector runs constantly when the mouse is moved. you can check by putting

`ngAfterViewChecked () {
console.log ('here');
}`

in any example diagram for angular

I leave an example in
[(https://codesandbox.io/s/b2pjf)]((https://codesandbox.io/s/b2pjf))

but it explodes and is not executed.

**Comment by LexDX** [comment]
Thank you for the report. I reproduced this issue and we are researching why it occurs:

https://supportcenter.devexpress.com/ticket/details/t869898/diagram-the-ngafterviewchecked-event-is-repeatedly-triggered-when-the-mouse-is-moved

We will update this ticket once we have any results.
