### ISSUE TITLE
Accordion item title translate

### ISSUE THREAD

**Issue by Pauline3** [DevExpress/devextreme-angular#1049]
**Package versions:**

    devexteme version: 19.2.5
    devextreme-angular version: 19.2.5

**Steps to reproduce:**

I use devextreme in an Angular application.
In my app, I have a dx-accordion with a dxi-item.
To translate the texts, I use ngx-translate but it doesn't work with the dxi-item title.
When I use |translate on the dxi-item, all the nested devextreme elements are hidden

I made a stackblitz project :
https://stackblitz.com/edit/angular-ufjc7k

**Comment by LexDX** [comment]
Hi @Pauline3,

It is necessary to wrap the content in an element with the dxTemplate directive without parameters. In this case, the button will work correctly. Please check the following documentation article for more information: https://js.devexpress.com/Documentation/Guide/Angular_Components/Component_Configuration_Syntax/#Collections
