### ISSUE TITLE
DevExtreme 20.1 warning on Angular 10

### ISSUE THREAD

**Issue by cesco69** [DevExpress/devextreme-angular#1086]
After Angular 10 upgrade some warning are show in the console when `ng serve` is run:

> WARNING in \node_modules\devextreme-angular\__ivy_n
> gcc__\fesm2015\devextreme-angular-core.js depends on devextreme/core/renderer. C
> ommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependenc
> ies
> 
> WARNING in \node_modules\devextreme-angular\__ivy_n
> gcc__\fesm2015\devextreme-angular-ui-load-indicator.js depends on devextreme/ui/
> load_indicator. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependenc
> ies
>

**Comment by riheldo** [comment]
@cesco69 thats a new angular 10 cli feature
check **Warnings about CommonJS imports** in [Angular 10 post](https://blog.angular.io/version-10-of-angular-now-available-78960babd41)

**Comment by thegreatgreendragon** [comment]
Is devextreme planning on not using CommonJS anymore?

**Comment by hakimio** [comment]
> Is devextreme planning on not using CommonJS anymore?

[Should be fixed in v20.2](https://github.com/DevExpress/devextreme-angular/issues/811#issuecomment-666384633).

**Comment by IlyaKhD** [comment]
We're going to deliver a set of ES6 modules starting with v20.2, see https://github.com/DevExpress/DevExtreme/issues/14351 for more details.
