### ISSUE TITLE
Scheduler displays events in wrong cell.

### ISSUE THREAD

**Issue by nicolassalo** [DevExpress/devextreme-angular#1132]
# Bug Report

**Package versions:**

    devexteme version: ^20.2.3
    devextreme-angular version: ^20.2.3 

**Steps to reproduce:**

    Create recurring event (in my case once a week)

**Current behavior:**

    The three lower week rows are shifted into the upper three rows. Resizing the window fixes it.

**Screenshots:**

    https://youtu.be/uljvu8_zCR8

**Comment by AntonSermyazhko** [comment]
Hello,

Thank you for the reply. 
I reproduced this issue and forwarded it to our developers for further investigation.
We will update this report once any news is available.

**Comment by AntonSermyazhko** [comment]
Our R&D team investigated the issue and found that sometimes angular in debug mode loads styles after the javascript. This is a reason for rendering appointments incorrectly.
To resolve the issue, we suggest loading the main bootstrap module after the document is completely ready:

```
// main.ts
document.onreadystatechange = function () {
  if(document.readyState == "complete") {
      platformBrowserDynamic().bootstrapModule(AppModule)
        .catch(err => console.error(err));
    }
}
```

Also, a similar problem discussed on stackoverflow where the solution uses direct links to the `DevExtreme` styles inside the `index.html`.
