### ISSUE TITLE
Angular DevExtreme: How to use DxDataGrid (OData dataSource) with rxjs store?

### ISSUE THREAD

**Issue by dhlukhatarenka** [DevExpress/devextreme-angular#1139]
Hello!

Similar question was asked in [stackoverflow](https://stackoverflow.com/questions/60316712/how-to-handle-odata-in-redux). How necessary is it? Is it possible at all?

Thank you.

**Comment by onebalaban** [comment]
Hello @dhlukhatarenka,

If you have additional questions, please leave a comment in that ticket or submit your ticket. We'll be happy to assist you.

Regards,
Romeo
