### ISSUE TITLE
dxi-Item Disable/Enable on button Click event

### ISSUE THREAD

**Issue by SohilAhmed** [DevExpress/devextreme-angular#1150]
I've set a dx-form that has multiple dxi-item. when I change the value of isDisabled (bool) on the button click event, it disables all the buttons on my forms.

https://user-images.githubusercontent.com/31825704/109381151-8d257280-78fe-11eb-8792-678e397a6e96.mp4
 
[test.component.html.txt](https://github.com/DevExpress/devextreme-angular/files/6053912/test.component.html.txt)
[test.component.ts.txt](https://github.com/DevExpress/devextreme-angular/files/6053913/test.component.ts.txt)

**Comment by onebalaban** [comment]
Hi,

Please submit a ticket to our [support center](https://devexpress.com/ask) and attach a demo project (you can use our [Angular template](https://github.com/DevExpress/devextreme-angular-template)) to demonstrate the issue.
