### ISSUE TITLE
dxo-toolbar not found  error & custom toolbar not begin displayed

### ISSUE THREAD

**Issue by saurabh47** [DevExpress/devextreme-angular#1227]
Getting `dxo-toolbar not found ` error even `DxToolbarModule` is imported.
I have tried importing `DxoToolbarModule` as well but in this case, it does not throw any error 
but it does not show any toolbar in the data grid.

# Bug Report

**Package versions:**

    devexteme version: ^19.2.5
    devextreme-angular version: ^19.2.5

**Steps to reproduce:**

Component Template          
```
<dx-data-grid [dataSource]="orders">
    <dxo-toolbar>
        <dxi-item location="center" widget="dxButton" locateInMenu="never">
            <div *dxTemplate>
                <div class="toolbar-label"><b>Tom's Club</b> Products</div>
            </div>
        </dxi-item>
    </dxo-toolbar>
</dx-data-grid>
```

Module imports
```
import { DxButtonModule, DxDataGridModule, DxFileUploaderModule, DxPopupModule, DxSelectBoxModule, DxTemplateModule, DxToolbarModule } from 'devextreme-angular';

@NgModule({
  declarations: [ManageUsersComponent, ManageComponent],
  imports: [
    CommonModule,
    RouterModule.forChild(routes),
    DxButtonModule,
    DxDataGridModule,
    DxPopupModule,
    DxFileUploaderModule,
    DxTemplateModule,
    DxSelectBoxModule,
    DxToolbarModule
  ]
})
export class ManageModule { }
```

**Current behavior:**

- In case of `DxToolbarModule & DxDataGridModule` imported
![image](https://user-images.githubusercontent.com/15173289/146672784-1064e0e0-2b7a-4843-878f-8e25cf9019e0.png)
- In case of `DxToolbarModule , DxDataGridModule & DxoDataGridModule ` modules imported
It does not show the toolbar

**Expected behavior:**
- Custom toolbar should be displayed

**Comment by onebalaban** [comment]
Hi,

We implemented a DataGrid toolbar as a component only in v21.2. Please use the `onToolbarPreparing` event handler to customize a toolbar in v19.2.
