### ISSUE TITLE
How to get access to a child's template scope from parent?

### ISSUE THREAD

**Issue by davidalee** [DevExpress/devextreme-angular#143]
```
// Child component

<div *dxTemplate="let data = data of 'itemTemplate'">
  <ng-content select="search-result-template"></ng-content>
</div>
```

```
// Parent component

<search-result-template>
  <div class="item-title">{{ data.title }}</div>
  <div class="item-id">ID: {{ data.id }}</div>
</search-result-template>
```

But obviously this won't work because parent doesn't have access to the `data` object that is defined within template. How do I do this?

**Comment by Angelminster** [comment]
Hi,

If you want to do it properly: _NgTemplateOutlet_. You can send a templateRef to another component and render it there with the proper context. I haven't try it yet, but sounds great.

As a simple _workaround_ use an @Input variable to set the template in the children:

@Input templateVariable
```
<div [ngSwitch]="templateVariable">
    <div *ngSwitchCase="'superTemplate1'">
        <div *dxTemplate="let data = data of 'itemTemplate'">
            <div class="item-title">{{ data.title }}</div>
            <div class="item-id">ID: {{ data.id }}</div>
        </div>
    </div>
    <div *ngSwitchCase="'superTemplate2'">
        <div *dxTemplate="let data = data of 'itemTemplate'">
            <div class="item-title">GREAT: {{ data.title }}</div>
        </div>
    </div>
....
```

Also you can set the HTML template as a variable to the children and generate the dom elements dynamically (DynamicComponentLoader).

Hope it Helps!

**Comment by dxbykov** [comment]
@davidalee Is the issue still relevant? If so, would you please provide us with a sample using our [Plunker template](http://plnkr.co/edit/tpl:3MUrYspAm1RfHLSrc6CP?p=preview)? It's not quite clear in what context the issue takes place.
