### ISSUE TITLE
Does DxLookup's formcontrol attribute use ngModel?

### ISSUE THREAD

**Issue by davidalee** [DevExpress/devextreme-angular#147]
I'm using the formControlName attribute with DxLookup and am getting a weird error: `formControlName must be used with a parent formGroup directive.  You'll want to add a formGroup directive and pass it an existing FormGroup instance (you can create one in your class).`

```
export class AddColumnComponent implements OnInit {
    public newColumnType: FormControl;
    public newColumnName: FormControl;
    public form: FormGroup;

    constructor() {
        this.newColumnType = new FormControl("", Validators.required);
        this.newColumnName = new FormControl("", Validators.required);

        this.form = new FormGroup({
            newColumnType: this.newColumnType,
            newColumnName: this.newColumnName,
        });
    }
```

and my dx-lookup component:

```
<dx-lookup
// other attributes omitted for brevity
                ...
                ...
                formControlName="formControl">
            </dx-lookup>
```

Not sure what I'm doing wrong as it seems to me that I'm doing what the error message is suggesting.

**Comment by Aden-git** [comment]
Hello,
 
I could not reproduce this error, so I created the [simple Plunker](http://plnkr.co/edit/ynr4i2NQxckWWlrVgAqY?p=preview) with DxLookup and the formControlName attribute. Could you please edit it to help us reproduce this error?
