### ISSUE TITLE
How to use dxResponsiveBox 

### ISSUE THREAD

**Issue by xbrabec** [DevExpress/devextreme-angular#166]
It is not clear to me how to use dx-responsive-box.

Content is defined using dxItem, but there is no example anywhere and I cannot even find anything in the source code for dxItem.

Thanks

Honza

**Comment by GoshaFighten** [comment]
@xbrabec 
Specifying dxResponsiveBox items using the dxItem option currently does not work. We have plans to improve this in the future though. For now, specify the dxResponsiveBox items collection and specify a template for an item. See the [plunker](http://plnkr.co/edit/HbKppr?p=preview) that illustrates this.

**Comment by dxbykov** [comment]
You can also use a plunk from [this comment](https://github.com/DevExpress/devextreme-angular/issues/232#issue-190366394).

**Comment by hem19** [comment]
dx-responsive-box doesn't work if height attribute is not given or height is given in percentage.
In the following example - https://js.devexpress.com/Demos/WidgetsGallery/Demo/Responsive_Box/Overview/Angular/Light/
I changed the height to 100% and it doesn't work. Also tried with removing the height attribute, that too didn't work.
