### ISSUE TITLE
devextreme-angular2  DxDataGridComponent  create a CRUD

### ISSUE THREAD

**Issue by Severanin** [DevExpress/devextreme-angular#167]
Hello!
In angular operation CRUD is only used JQuery?

Thank you in advance

**Comment by anna-zhernovkova** [comment]
Hello!
You can see the [example](http://plnkr.co/edit/n86gpB?p=preview), which shows how to implement this functionality.
Should you have any further questions, feel free to contact us.

**Comment by Severanin** [comment]
Hello!
Anna how in Angular2 recive rowindex columnindex for editing columns in datagridcomponent.

//get key in datagrid (rti.component.ts)
  gridRemoveIzdelie() {
        var array = this.dataGrid.selectedRowKeys;
        for (var numElement in array) {
            console.log(array[numElement].id);

**Comment by anna-zhernovkova** [comment]
Hi,
It appears that the information you provided is insufficient for us to determine the exact cause of the issue. It is unclear what you mean when you say: "rowindex columnindex for editing columns", because we have two ways to edit data - change the value of one cell or the whole row. If it possible, can you provide your issue in a simple example?

**Comment by Severanin** [comment]
Добрый день!
Почему то у меня есть уверенность что вы понимаете русский язык )))
Есть небольшое недопонимание работы событий в Devextreeme-angular2.
Подскажите пожалуйста!
Пример:  

showTestId(id :number) {
		console.log(id);

this.treeView.instance.option
({
	onItemClick: function (e) {
	showTestId(e.itemData.id);}, <<<<<<---------- Не видит метод 	showTestId(id)
});

Thank you in advance!

**Comment by anna-zhernovkova** [comment]
Hello,
I see that your last inquiry is not related to the question discussed in this thread. For this reason I have created a [new issue](https://github.com/DevExpress/devextreme-angular/issues/204).
Please write in English. We have other English-speaking customers, who can be interested in our answers.

**Comment by Severanin** [comment]
OK! Thank you!
