### ISSUE TITLE
datetime format in grid

### ISSUE THREAD

**Issue by GhEllie** [DevExpress/devextreme-angular#192]
Hello ,

I have a column with datetme format in my grid like below :
  dataType: 'date',
format: 'dd/MM/yyyy HH:mm'

Grid is showing all dates in +1 hour . for example I have "2016-07-06 10:20:00" and the grid is showing "2016-07-06 11:20:00"

I think that's a bug in grid

**Comment by kvet** [comment]
Hi,
 
I could not reproduce the issue on my side. Date formatting is performed by Globalize, so this issue may be not a DevExtreme bug.
 
If you are not sure that this is a Globalize bug, can you provide a simple example where we can reproduce the issue?

**Comment by achopijocoder** [comment]
@GhEllie  That is the effect of the local time. The data arrives to the grid with the hour "10:20:00" but when is parsed to be shown is converted to local time.  Maybe you should use UTC time or handle the hour in your rest api.
