### ISSUE TITLE
16.2.1-alpha.1 different component name

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular#197]
Hi,

After updating my project to the latest release:
"devextreme": "16.2.1-16294",
"devextreme-angular2": "16.2.1-alpha.1",

It does not compile.  In node_modules/devextreme-angular2/ui/validator.d.ts you have this:

import **DxValidator** from 'devextreme/ui/validator';
export declare class DxValidatorComponent extends DxComponent implements OnChanges, DoCheck {
    private _idh;
    instance: **DxValidator**;

And when i go to node_modules/devextreme/ui/validator.d.ts i have:

import DevExtreme from '../bundles/dx.all';
export default **DevExtreme.ui.dxValidator;**

In dx.all.d.ts also has this name inconsistencies. All the components have differents names.

¿Do I have to use another devextreme package with names updated? 
Thank you

**Comment by dxbykov** [comment]
Hi,
 
node_modules/devextreme/ui/validator.d.ts has **default** export of dxValidator. So, during the import, we can use any local name for it unless we wrap it into the { } braces. So, it's not clear why the issue takes place. What error message do you have?

**Comment by Angelminster** [comment]
Thank you Alexander,

Maybe is an issue with my IDE or my configuration. It couldn't find DxAccordion "local" name. I have to change the type to Devexpress.ui.dxAccordion:

import DxAccordion from 'devextreme/ui/accordion';
export declare class DxAccordionComponent extends DxComponent {
    instance: DxAccordion; //DxAccordion cannot find name -> I've changed it to DevExpress.ui.dxAccordion to get it working
[...]
}

It seems that i cannot use the default export. I dont know why. My tsconfig seems to be good. As a workaround i have changed all my "local" types to the global one and it is working. 

Thank you
