### ISSUE TITLE
dx-data-grid StateStoring

### ISSUE THREAD

**Issue by MarcoMonterminiBolla** [DevExpress/devextreme-angular#199]
**To process your issue more efficiently, please provide the following information:**
-  devextreme-angular2: 16.1.7

I use Angular2 with typescript and I have configured in my component the grid state storing option like this 
 [stateStoring]=
"{
      enabled: true,
      type: 'custom',
      customLoad: customLoad,
      customSave: customSave
}"
in the component I have created a function to load the preferences

customLoad(){
        console.log("loadStorageRequest");
        console.log(this);
...
}
is the correct way? 
It seems that the "customLoad" function it's been called but without having the component instantiated before, like if it would a plain global js function, in fact "this" has not the expected value (it should be equal to the current component instance)

Thanks

**Comment by dxbykov** [comment]
Hi,

Methods of a ES6 class are not automatically bound to its instance due to performance and a number of other reasons. The same is relevant to TypeScript methods. If it's necessary, it's generally recommended to bind them manually. You can do this in the class constructor as follows:

```js
constructor() {
  this.customLoad = this.customLoad.bind(this);
}
```

**Comment by MarcoMonterminiBolla** [comment]
Thanks very much, it works perfectly for me.
