### ISSUE TITLE
dx-data-grid master-detail *dxtemplate angular2

### ISSUE THREAD

**Issue by Severanin** [DevExpress/devextreme-angular#210]
Hello.
1. How to create a template in dx-data-grid.
2. How linked two table  on the key field in (master-detail dxtemplate).

Thank you in advance!

**Comment by dxvladislavvolkov** [comment]
Hello!
You can see an example [here](http://plnkr.co/edit/NYrD0dB3hhdLFMzSTtb2?p=preview).
