### ISSUE TITLE
Samples do not work

### ISSUE THREAD

**Issue by Laoujin** [DevExpress/devextreme-angular#215]
git clone
npm install
npm start

/examples do not work

Console exception:

```
zone.js:232 Error: (SystemJS) XHR error loading http://127.0.0.1:8875/node_modules/devextreme/events/dblclick.js(…)
```

**Comment by dxbykov** [comment]
Hi,
 
I've just performed the same steps as you and it works fine on my side. Please try to clone the repo and install the dependencies once more in an empty folder. There may have been issues during the download process. If this still doesn't help, let us know what browser, OS, node and npm versions you are using.

**Comment by kvet** [comment]
Hi,
 
We have found an issue with loading `dblclick.js` with the enabled adblock. As a workaround, you can turn it off for the demo page.

**Comment by Laoujin** [comment]
Wow... That was unexpected.
Opening in different browser (without AdBlock) or disabling Adblock and it works perfectly.

Thanks for the assistance!
