### ISSUE TITLE
Angular 2 Router and dxDataGrid

### ISSUE THREAD

**Issue by frkolyan** [DevExpress/devextreme-angular#222]
Hi! I would like to know how can I insert [routerLink]'s in dxDataGrid. If I use cellTemplate from code these links become text and angular doesn't "translate" them to router links. 

I've tried some approaches but all of them were useless. Here is one of them using dxTemplate (in my work project I can't use templates, I get "TypeError: n.owner is not a function" error for some unknown reasons).
Test project: 
http://plnkr.co/edit/lqlI85x11A4p3JVIA7YX?p=preview
Thank you!

UPD: I use devExtreme 16.1.7 version in work project.

**Comment by dxbykov** [comment]
Hi,

Please refer to [this guide](https://angular.io/docs/ts/latest/guide/router.html). I have created a working [sample plunk](http://plnkr.co/edit/EUWFgCcrfcckxiIFLnRr?p=preview) for you. Note, it's based on DevExtreme 16.2 since it's more stable and is going to be released soon.

**Comment by frkolyan** [comment]
Hi, thank you very much!

2016-11-30 19:53 GMT+03:00 Alexander Bykov <notifications@github.com>:
