### ISSUE TITLE
Reactive Forms - FormControl.disable() not being applied

### ISSUE THREAD

**Issue by bonejon** [DevExpress/devextreme-angular#224]
Hi,

I am unable to use the disable() method of a FormControl to control the enabled/disabled state of the devextreme editor.

I have created the following plunker to demonstrate the issue. 
[http://plnkr.co/edit/zgvcWTm9M4BrUvroUV7C?p=preview](http://plnkr.co/edit/zgvcWTm9M4BrUvroUV7C?p=preview)

Regards, Jon.

**Comment by strpipe** [comment]
Hi Jon,

you can attach

> [visible]=inputControl.enabled

to your button. Though this might not what does the real trick for you.

Regards!
