### ISSUE TITLE
DxScrollView - The onPullDown and onReachBottom options don't work

### ISSUE THREAD

**Issue by dxvladislavvolkov** [DevExpress/devextreme-angular#228]
See an example [here](http://plnkr.co/edit/fF6g5cgO9asDDMMDC43e?p=preview).

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular 2 integration. dxScrollView does not invoke pull refresh if the "pullDown" event is handled. I have created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T454319) in our Support Center.
