### ISSUE TITLE
Datebox fails to render dropdown

### ISSUE THREAD

**Issue by bonejon** [DevExpress/devextreme-angular#229]
This is a very specific edge case within the date-box control, and is reproducible using 16.1 and 16.2-unstable

If you initialise a date-box using a model driven form, then set the value of the form control to an invalid date value the dropdown will fail to render. If the control is initialised with a valid value or the user interacts with the control before the invalid value is set then the behavior is as expected.

See the following plunker for reproduction, click the "Set Invalid Date" button then try and open the drop down.
[http://plnkr.co/edit/W9GQIcXIh7yE23srQpei](http://plnkr.co/edit/W9GQIcXIh7yE23srQpei)

**Comment by dxbykov** [comment]
Hi @bonejon ,

I've tested your code sample and found that an error occurs in both the cases you've mentioned. You can see it in the browser's dev console. Would you please clarify the use case when you need to set an invalid value to the editor from your code?

**Comment by bonejon** [comment]
Hi @dxbykov 

When using moment to parse strings to dates before binding them to the DevExpress control you could get this issue. It could argued that the code parsing the date should handle the exception, however as the date box appeared to handle most other situations I thought it worth mentioning.

**Comment by dxbykov** [comment]
Thank you for sharing your use-case. You are right that the dx-date-box component could be smarter and handle your scenario without exceptions. If we consider fixing this issue, we should apply the fix to all our editors. At the moment it will cause lots of changes in the codebase and might affect the overall stability. Let me mark this issue as 'enhancement', and we'll think it over while planning future releases.

**Comment by elasticrash** [comment]
I don't know if it is related but I have similar issues with dx-date-box component when i try do enter a custom parser/formatter. So basically this works

```
<dx-date-box width="100%" [(value)]="dateReceived" type="datetime">           
    <dx-validator>
        <dxi-validation-rule type="required" message="'DATE_REQUIRED'"></dxi-validation-rule>
    </dx-validator>
</dx-date-box>
```

and this the date is parsed/formatted just fine but the datebox fails to render the dropdown calendar

```
<dx-date-box width="100%" [(value)]="dateReceived" type="datetime">
    <dxo-display-format
                    [parser]="parserFunction(currentReProduct.dateReceived)"
                    [formatter]="formatterFunction(currentReProduct.dateReceived)" >
    </dxo-display-format>             
    <dx-validator>
        <dxi-validation-rule type="required" message="'DATE_REQUIRED'"></dxi-validation-rule>
    </dx-validator>
</dx-date-box>
```

**Comment by LexDX** [comment]
Hi,

The issue should be fixed in the latest version of our components. If you still have any issues, feel free to reopen this issue and create a small runnable sample project to show it. This way we will be able to analyze and debug the incorrect behavior on our side.
