### ISSUE TITLE
dxFileUploader - The onValueChanged event fires more than once

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-angular#230]
The DevExtreme Angular package's version is 16.2.1-alpha.3

See an [example](http://plnkr.co/edit/oDixPHBaTNgticf6ZMUO?p=preview).
Please try uploading the file and take a look at the console.

**Comment by dxbykov** [comment]
This issues appears not to be related to DevExtreme Angular integration and should be fixed in the dxFileUploader widget.
