### ISSUE TITLE
Accordion Event

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#237]
i want to when i click in accordion item, close the accordion. Which property will set true or false ?

**Comment by dxvladislavvolkov** [comment]
Hello!
Try to set the collapsible option to true. It will allow collapsing all items of the accordion.

**Comment by Consi007** [comment]
You can give me an example ?

**Comment by dxvladislavvolkov** [comment]
You can see the example [here](http://plnkr.co/edit/adYbYZpIMdMk2Wp2jFi7?p=info).

**Comment by Consi007** [comment]
there is no exsample accordion on devextreme angular 2 githup repository

**Comment by Consi007** [comment]
![accordion](https://cloud.githubusercontent.com/assets/22006033/20557941/6c5276ba-b176-11e6-9352-8dce68c0f2f9.png)

**Comment by dxvladislavvolkov** [comment]
In this case you can use the collapseItem method. 
I've prepared a simple [example](http://plnkr.co/edit/YpyOdBu8Hucpj8giBkyW?p=preview) illustrating how you can use the method.
