### ISSUE TITLE
Some nested components don't exist 

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-angular#238]
The DevExtreme Angular package's version is 16.2.1-alpha.3

Some nested components don't exist for options that can accept several data types. For instance, the valueAxis option of the DxChart can accept an array or an object, but we have only the dxi-value-axis and not dxo-value-axis components.

**Comment by ovchinnikov** [comment]
To configure options that can accept a configuration object or an array of configuration objects, use dxi- prefixed components.
