### ISSUE TITLE
DxSelectBox loses its data

### ISSUE THREAD

**Issue by anna-zhernovkova** [DevExpress/devextreme-angular#245]
The DevExtreme Angular package's version is 16.2.1-alpha.3

Reproduced in [example](http://plnkr.co/edit/5sKFvF2LtFI68JLa9Fg3?p=preview)
Steps:
1. Write a search value in the DxSelectBox (for instance, "led")
2. Choose the value or press outside the DxSelectBox
3. Open the drop-down menu. You can see that the data, which didn't meet the search condition, was lost.

**Comment by nightskylark** [comment]
Hi,
This issue is fixed in the context of [another issue](https://www.devexpress.com/Support/Center/Question/Details/T454977) in the DevExpress Support Center. The fix will be available with the next DevExtreme npm packages update.
