### ISSUE TITLE
Globalize not working

### ISSUE THREAD

**Issue by mydoom5** [DevExpress/devextreme-angular#246]
I've recently updated my project's devextreme-angular version to 16.2.1-alpha.3 and everything went well, except for the components localization.
I'm working in another project which uses the devextreme framework and was updated to the 16.1.7 version without any problems regarding the use of Globalize 1.x version. I've followed your updating guide and added all the needed files (cldr and devextreme localizations as well as the basic globalize files), but never managed to get it working.

My index.cshtml is as follows:

`<!DOCTYPE html>
<html>
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="libs/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css" />
    <link href="libs/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="libs/toastr/build/toastr.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="styles.css">

    <link href="assets/global/css/components-md.min.css" id="style_components" rel="stylesheet" type="text/css" />
    <link href="assets/layouts/layout/css/layout.min.css" rel="stylesheet" type="text/css" />
    <link href="assets/layouts/layout/css/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
    <link href="assets/layouts/layout/css/custom.min.css" rel="stylesheet" type="text/css" />

    <link href="css/vendors/dxtreme/dx.common.css" rel="stylesheet" type="text/css" />
    <link href="css/vendors/dxtreme/dx.spa.css" rel="stylesheet" type="text/css" />
    <link href="css/vendors/dxtreme/dxSkills.css" rel="stylesheet" type="text/css"/>
    <link href="css/vendors/jqueryui/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
    <link href="css/custom/jqueryui.tooltip.css" rel="stylesheet" type="text/css"/>

    <script src="libs/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="libs/ms-signalr-client/jquery.signalR.min.js" type="text/javascript"></script>
    <script src="libs/block-ui/jquery.blockUI.js" type="text/javascript"></script>
    <script src="libs/core-js/client/shim.min.js"></script>
    <script src="libs/zone.js/dist/zone.js"></script>
    <script src="libs/reflect-metadata/Reflect.js"></script>
    <script src="libs/systemjs/dist/system.src.js"></script>
    <script src="systemjs.config.js" type="text/javascript"></script>

    <script src="scripts/vendors/cldr/cldr.min.js" type="text/javascript"></script>
    <script src="scripts/vendors/cldr/event.min.js" type="text/javascript"></script>
    <script src="scripts/vendors/cldr/supplemental.min.js" type="text/javascript"></script>
    <script src="libs/globalize/dist/globalize.js" type="text/javascript"></script>
    <script src="libs/globalize/dist/globalize/message.js" type="text/javascript"></script>
    <script src="libs/globalize/dist/globalize/number.js" type="text/javascript"></script>
    <script src="libs/globalize/dist/globalize/currency.js" type="text/javascript"></script>
    <script src="libs/globalize/dist/globalize/date.js" type="text/javascript"></script>
    <script src="libs/devextreme/dist/js/dx.all.js" type="text/javascript"></script>
    <script src="scripts/vendors/dxtreme/localization/dx.all.pt.js" type="text/javascript"></script>

    <script src="libs/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="libs/toastr/build/toastr.min.js" type="text/javascript"></script>

    <script src="assets/global/scripts/app.min.js" type="text/javascript"></script>
    <script src="assets/layouts/layout/scripts/layout.min.js" type="text/javascript"></script>
    <script src="assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>

    <script type="text/javascript">
        $(function () {
            $.when(
                $.getJSON("scripts/vendors/cldr/main/pt/ca-gregorian.json"),
                $.getJSON("scripts/vendors/cldr/main/pt/numbers.json"),
                $.getJSON("scripts/vendors/cldr/main/pt/currencies.json"),
                $.getJSON("scripts/vendors/cldr/main/pt/timeZoneNames.json"),
                $.getJSON("scripts/vendors/cldr/supplemental/likelySubtags.json"),
                $.getJSON("scripts/vendors/cldr/supplemental/timeData.json"),
                $.getJSON("scripts/vendors/cldr/supplemental/weekData.json"),
                $.getJSON("scripts/vendors/cldr/supplemental/currencyData.json"),
                $.getJSON("scripts/vendors/cldr/supplemental/numberingSystems.json")
            ).then(function () {
                return [].slice.apply(arguments, [0]).map(function (result) {
                    return result[0];
                });
            }).then(
                Globalize.load
            ).then(function () {
                Globalize.locale("pt");

                System.import('app').then(function (a) {
                    a.runApplication("@ViewBag.SkillsWeb", "@ViewBag.ApiUrl", "@ViewBag.ApiV2Url", "@ViewBag.ChatApi", "@ViewBag.ChatHub");
                }).catch(function (err) { console.error(err); });
            });
        });
    </script>
  </head>
<body class="page-header-fixed page-sidebar-closed-hide-logo ng-scope page-content-white">
    <app-component></app-component>
</body>
</html>
`

In the browser's developer console, when inserting `Globalize.formatMessage("Cancel")`, for instance, the correct localized message is returned, but somehow that never reflects into the devextreme components. It also doesn't matter if I use angular2 directives or create the objects via JQuery.

Can you give me a clue about what am I doing wrong, please?

Thank you very much.

**Comment by nightskylark** [comment]
Hello
It is not clear in what environment your project operates, so I cannot tell you why it works incorrectly.
Please see [this example](https://github.com/DevExpress/devextreme-examples/tree/16_2/systemjs-angular-globalize) of using the Globalize localization in DevExtreme with the Angular 2 integration. It should help you figure out how to improve your project.
If it does not help, please provide a project that reproduces the issue. For example, you can modify [the project](http://plnkr.co/edit/tpl:3MUrYspAm1RfHLSrc6CP?p=preview) we prepared for you using Plunker to demonstrate your scenario.
