### ISSUE TITLE
DxGallery example request

### ISSUE THREAD

**Issue by stevenrobijns** [DevExpress/devextreme-angular#248]
Hi,

We are having troubles with the dxGallery in angular 2. 
We posted a previous issue #214 before and closed it because indeed the plunkr you guys provided works with a newer unstable version than the one we use(16.1.7, last stable). 

Still we were having troubles with integrating the unstable version and thus the dxgallery into our angular 2  application(something with an import statement in a .ts file).

We were wondering about 2 things.

- When will the next stable release be approx.?
- Can you please provide a working dx gallery example in the examples devextreme-angular/examples/app/

**Comment by dxbykov** [comment]
Hi,

* We have released the first DevExtreme Angular 2 integration beta, and recommend switching to it. Its npm package is available under the '16.2-unstable' tag. Once we are confident that there are no any severe issues in it, we'll publish the final release. We believe it will happen next month.

* You can refer to [this sample](http://plnkr.co/edit/sAGq7NYvVgUFhg5Cgqur?p=preview) to see the use of dxGallery.

**Comment by stevenrobijns** [comment]
Will the next release work with typescript 2.x?

**Comment by dxbykov** [comment]
Yes, it will. You can check it out right now with the beta package.

**Comment by stevenrobijns** [comment]
I just did that, and we're having the same problem as before. Maybe because of the editors we use(VS 2015 or VS 2017 RC) 

Apprantly there's a problem with the typescript import statements without curly braces, as seen in the screenshot below.

![capture](https://cloud.githubusercontent.com/assets/9976683/20676298/930ad780-b58f-11e6-9682-c94ef8b8fa8c.PNG)

Have you got this feedback before or do you know what the solution might be?

**Comment by Angelminster** [comment]
Same problem in #197

**Comment by stevenrobijns** [comment]
It indeed looks like it's the same problem. But we cannot afford to modify the *.ts files manually each time after npm install. For us it could make the difference buying the component suite or not. But I guess it's a Visual Studio problem, more than a DevExtreme problem than.

**Comment by Angelminster** [comment]
We haven't got enough time to debug the problem. It could be one of the multiple new flags of typescript in compilation.

If you find a solution, let us know please.

**Comment by Angelminster** [comment]
Can you try import { default as DxGallery } from 'devextreme/ui/gallery';  ?

Or 

import * as DxGallery from 'devextreme/ui/gallery'

Could be some problem mixing es6 with commonjs modules: [info](http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/)

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
