### ISSUE TITLE
Edit multiple values in a column - using tag-box in a dx-data-grid

### ISSUE THREAD

**Issue by prabhdaffo** [DevExpress/devextreme-angular#255]
Hi,

How can I use a tag-box in a dx-data-grid in angular 2?  I have found this example here - http://jsfiddle.net/jc1x2q7k/ 

Our grid is always in edit mode, by default and we will use data-source to bind the values in tag-box which might be searchable. 

tag-box provide all these features - https://js.devexpress.com/Demos/WidgetsGallery/#demo/editors-tag_box-overview/angular

I have tried multiple ways to make it work in a dx-grid but it is not showing any value

----   dx-data-grid  -----

            <div *dxTemplate="let type of 'typeTemplate'">
                <div dx-tag-box="tagBox.search"></div>
            </div>

----   dx-data-grid  -----

      this.tagBox = {
            search: {
                items: [
                    "HD Video Player",
                    "SuperHD Video Player",
                    "SuperPlasma 50",
                ],
                searchEnabled: true
            }
        };

Please let me know, what should I do to make it work in angular 2?

**Comment by dxbykov** [comment]
Hi,

Try to modify your code as follows:

```html
        <div *dxTemplate="let type of 'typeTemplate'">
            <dx-tag-box [items]="tagBox.search.items" [searchEnabled]="tagBox.search.searchEnabled">
            </dx-tag-box>
        </div>
```

**Comment by prabhdaffo** [comment]
@dxbykov this approch was not working for me

I found another example for it - http://jsfiddle.net/jf713jf/1Ld2p4mn/

I have done this - 
    
         type: any;

-------  In Constructor -----------
                this.type = [{
                    id: 1,
                    name: 'Mustang'
                 },
                 {
                    id: 2,
                    name: 'Charger'
                 },
                 {
                    id: 3,
                    name: 'Camaro'
                 }]

----------------  In dx-data-grid column in the component ------

           {
                dataField: 'type',
                caption: 'Type',
                cellTemplate: 'typeTemplate',
                width: '15%',
                showEditorAlways: true,
                editCellTemplate: function (container, data) {
                    container.dxTagBox({
                        dataSource: this.type ,
                        values: data.type || [],
                        valueExpr: 'id',
                        displayExpr: 'name',
                        onValueChanged: function (e) {
                            data.setValue(e.values);
                        },
                        searchEnabled: true
                    });
                }
            }

this.type is undefined in the dataSource, how can we access 'this' insided the function. I have also tried passing 'this' as a parameter but it is undefined -

                editCellTemplate: function (this, container, data) {
                      -----------
                      -----------
                }

The above don't give error if my dataSource is directly assigned to an array of object -

                  dataSource: [
                            {
                                id: 1,
                                name: 'Mustang'
                            },
                            {
                                id: 2,
                                name: 'Charger'
                            },
                            {
                                id: 3,
                                name: 'Camaro'
                            }
                        ]

**Comment by dxbykov** [comment]
It's better to use the Angular 2 way to create components and specify templates. I've prepared a [working sample](http://plnkr.co/edit/LwFxy1TxqBzHhkZhd6R9?p=preview) for you. Please check it out and let us know if it is what you are asking for.

**Comment by prabhdaffo** [comment]
@dxbykov  The plunkr sample that you have shared above binds an array of string, as a datasource, to tagbox

We are not using the tag-box in a grid  anymore because it wasn't working for us.

Now, if I have to bind array of object to a tag-box 

`types = [
    {
      name: "Item 1",
      type: "A"
    },
    {
      name: "Item 2",
      type: "B"
    }
  ];`

`<dx-tag-box [dataSource]="types" [(value)]="type"></dx-tag-box>`

Ref to angular 1 - https://js.devexpress.com/Demos/WidgetsGallery/#demo/editors-tag_box-overview

When we try to bind it with the tag-box, it shows Object object, Object object... as the list. We can achieve the same in angular 1 but that is not working when I added the those attributes.

**Comment by mikkelbm** [comment]
Hi @dxbykov 

I've played a little bit with your plunkr example and almost got it working in our own project. But the onRowUpdating event is not fired, if the only changes are in the tagbox column.

I forked your plunkr here:
[](http://plnkr.co/edit/r1O3u4Ncx2KJ5tn67Pqo?p=preview)

Where I would expect the onRowUpdating event to be fired, when I change something in the TagBox. But it doesn't. If I change the text in the other column it fires.

Can you explain that behavior?

Thanks

/Mikkel

**Comment by mikkelbm** [comment]
@prabhdaffo 

I have temporary fixed this with the following code:

`
@ViewChild('columnContactTypes') columnContactTypes: any;

ngAfterViewInit() {
        this.columnContactTypes.editCellTemplate = (container, options) => {
            container.dxTagBox({
                placeholder: 'Select types',
                dataSource: this.contactTypes,
                value: options.data.ContactTypes,
                displayExpr: 'Name',
                onValueChanged: (e) => {
                    options.setValue(e.value.slice(0)); // This code will push the changes back to the bound property...
                }
            });
        };
    }`

It's not a pretty solution, and I would really like to do this the Angular 2 way instead... But it works.

**Comment by vconst** [comment]
Hi @mikkelbm,
 
I have prepared an [example](http://plnkr.co/edit/2TjNT0pV3TQPKzd2sqih?p=preview) with an angular template, where the onRowPrepared event works fine. 
In the editCellTemplate you should call the cell.setValue method to return the modified value to the grid:

```html
<div *dxTemplate="let cell of 'tagsEditTemplate'">
    <dx-tag-box 
        [dataSource]="types" 
        [value]="cell.value.slice(0)"
        (onValueChanged)="cell.setValue($event.value)">
    </dx-tag-box>
</div>
```

Also, we will think about improving API for editCellTemplate in future versions.

**Comment by mikkelbm** [comment]
Hi @vconst 

Thanks a lot! It works great. For some reason I had to change:

`[value]="cell.value.slice(0)"`
to
`[value]="cell.value"`

Before it worked in my own project.
