### ISSUE TITLE
Bug on date and hour picker.

### ISSUE THREAD

**Issue by skoczylm** [DevExpress/devextreme-angular#256]
When clicking multiple times onto one of buttons (in short amount of time = try clicking as fast as you can :)):

![image](https://cloud.githubusercontent.com/assets/1774283/20799272/f4c4c310-b7e1-11e6-9697-dfe1701a691d.png)

The clock starts spinning continuously until refresh.

**Comment by kvet** [comment]
Hi,

I created an [example] (http://plnkr.co/edit/FBUbR50rZ9qJBYE6qB6e?p=preview) and tried it in Chrome, FireFox, IE. However, I could not reproduce the behavior you described above.

Could you please clarify how to reproduce it? It would be of great help if you provide a sample project showing the issue.

**Comment by hneuer** [comment]
Hy!

Its easy to reproduce, just click the spin button for the minutes for some seconds. The clock will then start to spin.

**Comment by hneuer** [comment]
Seems not to be related to the angular integration,  see here: https://www.devexpress.com/Support/Center/Question/Details/T476121
