### ISSUE TITLE
Dx-Tabs: Show/Hide tabs dynamically does not work

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#260]
I couldn't find any way how to hide and show again tabs in the code when dx-tabs has been created already.
1) I've tried to change visible property on the  column object
2) I've tried to remove tab from collection, it didn't have any effect as well

**Comment by DokaRus** [comment]
Hi,
 
Be sure to use two-way binding before doing something with dx-tabs items. I've prepared an [example](http://plnkr.co/edit/2MmitZzBYYWVs60lLcBd?p=preview), that demonstrates your 1) and 2) scenarios and it works fine.

**Comment by artstalker** [comment]
Thanks for your response. I see that example does not work with 16.2 version. Is this a known issue? What version can I use to verify that it works?

**Comment by artstalker** [comment]
It was an issue with old version of devextreeme-angular package. I've upgraded the package up to the latest and it worked just fine.
