### ISSUE TITLE
SelectionChanged event for a single select dx-list

### ISSUE THREAD

**Issue by varghesep** [DevExpress/devextreme-angular#262]
I'm using devextreme-angular 16.2.2-beta.1

I'm trying to use the dx-list as described [here](https://js.devexpress.com/Documentation/15_2/Guide/UI_Widgets/UI_Widgets_-_Deep_Dive/dxList/#End_User_Interaction_With_Items). I need an example how to do with devextreme-angular.

I want a _custom template_ for an item with an image on the left of a person's name. The item is only single select. When an item is selected (mouse or touch), another page should be opened to edit his information.

A sample list without the image on the left of the name is given below:

![people_list](https://cloud.githubusercontent.com/assets/12233474/20868074/edf15b4c-ba17-11e6-8ac6-aa1a0ae2da5b.png)

I have also noticed that the scrollbar is invading the space of the list.

**Comment by dxbykov** [comment]
Please check the [Custom Templates](https://github.com/DevExpress/devextreme-angular#custom-templates) section of the README page. You can also refer to the [list examples](https://github.com/DevExpress/devextreme-angular/blob/master/examples/app/app.component.html#L90). If you need to navigate between views, please refer to the [corresponding Angular 2 docs](https://angular.io/docs/ts/latest/guide/router.html).
