### ISSUE TITLE
How to use dxTabs and dxTabPanel with html templates?

### ISSUE THREAD

**Issue by varghesep** [DevExpress/devextreme-angular#263]
Can I use the dxTabs or dxTabPanel with separate HTML template file as the content of each tab? In the following example, I have a **user.html, comment.html and find.html** as the source for each tab? 

Each tab URL should take a query parameter like the userid. For example _user.html?userid=200_

![image](https://cloud.githubusercontent.com/assets/12233474/20869995/66d74c48-ba44-11e6-845c-e3e41fca658d.png)

**Comment by dxbykov** [comment]
If your tab templates are static, you can just create corresponding Angular 2 components with the 'templateUrl' property specified. Then, put them into each tab template. You can find an example [here](https://github.com/DevExpress/devextreme-angular/blob/master/examples/app/app.component.html#L230).

As I see, you want to pass a request parameter such as *userid*. That means you need to handle this request by your server-side code and return the corresponding template. If the *userid* value becomes available only at runtime, you'll need to process the template dynamically. You can find some info about this [here](http://stackoverflow.com/questions/38888008/how-can-i-use-create-dynamic-template-to-compile-dynamic-component-with-angular/38888009#38888009). Generally, all these tasks are not related to the DevExtreme components and are solved the same way in a pure Angular 2 app.
