### ISSUE TITLE
dx-data-grid dxo-master-detail does not seem to work 

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#274]
16.2.2-beta.2

This works

[masterDetail]="{enabled : !sessionSelectionOnly, template : 'masterDetail'}"

This does not.

	<dxo-master-detail [enabled]="!sessionSelectionOnly" template="masterDetail"></dxo-master-detail>

**Comment by dxbykov** [comment]
Hi,

Angular has a built-in *template* directive. For instance, you can find the following code in the [Angular docs](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#star-template):

```html
<hero-detail template="ngIf:currentHero" [hero]="currentHero"></hero-detail>
```

To make Angular use the *template* input variable of the *dxo-master-detail* component you need to use square braces:

```html
<dxo-master-detail [enabled]="!sessionSelectionOnly" [template]="'masterDetail'"></dxo-master-detail>
```

We'll update our docs to cover this exceptional scenario.

**Comment by stonecourier** [comment]
Thanks, that works well
