### ISSUE TITLE
DxToolbar - Dxi-Item issues?

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#278]
Using 16.2.2-beta.2

Was trying to use dx-item for dx-toolbar

This does not seem to work

```
<dx-toolbar class="ptx-toolbar-bottom">
    <dxi-item location="before" widget="dxButton" [text]="lang.ChangeEmailAddress" icon="fa fa-envelope" (onClick)="submit()"></dxi-item>
</dx-toolbar>
```

I was thinking I may need to use options, but dxo-options did not seem to be available. 

This is similar to how it was originally

`<dx-toolbar class="ptx-toolbar-bottom" [items]="toolbarItems"></dx-toolbar>`

```
  this.toolbarItems = [{
            location: "before",
            widget: "dxButton",
            options: {
                text: languageData.ChangePassword,
                icon: "fa fa-unlock",
                onClick: () => {
                    this.submit();
                }
            }
        }];
```

**Comment by DokaRus** [comment]
I've prepared [an plunker](http://plnkr.co/edit/fVzTGrylKMKbg5TKjylE?p=preview) that demonstrates how you can describe the content of a toolbar dxi-item.

**Comment by stonecourier** [comment]
Thanks, that works well
