### ISSUE TITLE
Youtube video about how to start from scratch with Asp.Net Core 1.1, Angular2, DevExtreme

### ISSUE THREAD

**Issue by viktorbk** [DevExpress/devextreme-angular#281]
To help those who are starting:
https://www.youtube.com/watch?v=iR-azi-kgjg

**Comment by SidorovX86** [comment]
Hi there

Anybody know how to speed up first time loading?

When I run my project, the "Loading..." test is appearing only after 30 sec waiting..

**Comment by strpipe** [comment]
@SidorovX86 if your question is still active, consider looking up lazy-loading.
@viktorbk thank you for that video.

**Comment by Mehul** [comment]
Hi Victor, thanks for supporting devextreme, we appreciate it. If you have more videos, please feel free to share with the community.
