### ISSUE TITLE
DxGrid Dxi-Column [visible] issues

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#289]
`<dx-data-grid *ngIf="sessionData.length> 0" [noDataText]="lang.noDataLessons" height="530px" width="880px" [dataSource]='sessionData'>
<dxi-column dataField="StudentsStr" [caption]="lang.students" width="150"></dxi-column>
<dxi-column dataField="TutorName" [caption]="lang.teacher" width="150" [visible]="selectedTutor == 0"></dxi-column>
<dxi-column dataField="SessionID" caption="" width="150" cellTemplate="buttonCell" [visible]="sessionSelectionOnly"></dxi-column>`

If you have the visibility of the column set based on a variable, and the variable changes, the column visibility does not change.

You can't use *ngIf on the column as it causes exceptions with captions.

As a workaround, I have put a *ngIf on the grid to reload the entire grid and this then works.

Using 16.2.2-beta.2
	`

**Comment by dxvladislavvolkov** [comment]
This issue appears not to be related to DevExtreme Angular integration and was fixed in the dxDataGrid widget. The fix will be available in devextreme version 16.2.4.
