### ISSUE TITLE
Dx accordion left and right

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#291]
![accordion](https://cloud.githubusercontent.com/assets/22006033/21213393/b6b26b52-c29c-11e6-9372-af27a4085a95.png)

**Comment by nightskylark** [comment]
Hi,
As I understand, the issue is not related to the devextreme-angular integration, but rather concerns the DevExtreme component functionality. Please contact the [DevExtreme support center](https://www.devexpress.com/Support/Center) to address your question.
