### ISSUE TITLE
Focus editor inside popup when popup opens

### ISSUE THREAD

**Issue by swollaert** [DevExpress/devextreme-angular#292]
Hi,

I would like to focus my editor inside a popup when the popup opens, but I can't seem to get it to work.
Here is what I have now.

`<dx-popup [title]="'Title'" (onShown)="focusEditor(numberBoxBudgetInHours)">`
`<div *dxTemplate="let data of 'content'">`
`            <dx-number-box #numberBoxBudgetInHours [(value)]="budgetInHours">`
`            </dx-number-box>`
`        </div>`
`    </dx-popup>`

`    focusEditor(editor) {`
`        setTimeout(function () {`
`            editor.instance.focus();`
`        }, 0);`
`    }`

Apparently my editor is still undefined when the event OnShown is triggered.

**Comment by Aden-git** [comment]
Hello @swollaert 

DxPopup content rendering is deferred ([deferRendering](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxPopup/Configuration/#deferRendering) option). You can use ViewChildren decorator to get access to DxNumberBoxComponent. Look at the [sample on plunker](http://plnkr.co/edit/N1i7p5tGSIQ1M1h0PPjC?p=preview).
