### ISSUE TITLE
Dx Tab Color

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#293]
How can i change dx tab color? Only one html page. not in css

**Comment by GoshaFighten** [comment]
If you need to change the tab color only in the dx-tabs markup, you can define your own item template for it that will have markup with the required color. See the [Custom Templates](https://github.com/DevExpress/devextreme-angular#custom-templates) topic to learn how to create a custom template in Angular.
If you don't want to completely override the default markup, handle the onItemRendered event. In the event handler, you can assign the required styles to the `e.itemElement' parameter using jQuery.
``` JavaScript
onItemRendered: function(e) {
e.itemElement.css("color", "red");
}
```
See the [Event Handling](https://github.com/DevExpress/devextreme-angular#event-handling) help topic to learn how to handle an event in Angular.
