### ISSUE TITLE
dx-tag-box model binding bug

### ISSUE THREAD

**Issue by muena** [DevExpress/devextreme-angular#294]
Hi,

I am using devextreme-angular@16.2.3 and encountered the following bug:
I have a dx-tag-box that gets the items from an api request and the model per input parameter.
The preselected tags (from the model) are displayed without any text. When I deselect and reselect them, everything works.
This bug doesn't occur when the tag-box is bound to a local array of items.

This is how it looks like:
![dx-tag-box_1](https://cloud.githubusercontent.com/assets/6779118/21305363/8623218e-c5cb-11e6-826f-b962db412e43.png)

And expanded:
![dx-tag-box_2](https://cloud.githubusercontent.com/assets/6779118/21305362/860a134c-c5cb-11e6-80f8-368f7a5107f8.png)

**Comment by anna-zhernovkova** [comment]
Hello!
I created an [example](http://plnkr.co/edit/u2LARxu2taLHsFRlDqJF?p=preview) but wasn't able to reproduce the issue. If possible, please, modify my example and send it back to us for further research.

**Comment by muena** [comment]
Hello Anna!

Thank you for the example!

Here is my modified fork:
http://plnkr.co/edit/JHfU7A0QBwuQiiWKCA5E?p=preview

The error is that the items are an Array<Resource> while the model is an Array<string>.
The displayExpr and valueExpr can't find the given attribute at the model and display an empty string.

**Comment by anna-zhernovkova** [comment]
This issues appears not to be related to DevExtreme Angular integration and should be fixed in the dxTagBox widget. I've created a report in the DevExpress Support Center so you can track our progress with it [here](https://www.devexpress.com/Support/Center/Question/Details/T464720).
As a workaround, you can set the 'value' options after data is received:

```
constructor(private service: Service) {
    this.service.getResources().subscribe(resources => { 
        this.resources = resources;
        this.client.allowedScopes = ["scope1"];
    });
    this.client = {name: "demo"};
}
```
