### ISSUE TITLE
Can't bind to 'columns' since it isn't a known property of 'dx-data-grid'.

### ISSUE THREAD

**Issue by Freez** [DevExpress/devextreme-angular#296]
When I add a devextreme widget I got the follow errors:

> VM23187:27 Unhandled Promise rejection: Template parse errors:
> Can't bind to 'columns' since it isn't a known property of 'dx-data-grid'.
> 1. If 'dx-data-grid' is an Angular component and it has 'columns' input, then verify that it is part of this module.
> 2. If 'dx-data-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
>  ("
> 
> <dx-data-grid
>     [ERROR ->][columns]='[
>         "FullName"
>     ]'
> "): EmployeesList@16:4
> Can't bind to 'dataSource' since it isn't a known property of 'dx-data-grid'.
> 1. If 'dx-data-grid' is an Angular component and it has 'dataSource' input, then verify that it is part of this module.
> 2. If 'dx-data-grid' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.......`

I got this error with all widget, I try to add a button but it doesn't work.

> `Can't bind to 'text' since it isn't a known property of 'dx-button'.
> 1. If 'dx-button' is an Angular component and it has 'text' input, then verify that it is part of this module.
> 2. If 'dx-button' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

I using webpack and Angular 2.2.3.
How can I fix this?

**Comment by Aden-git** [comment]
Hello @Freez 

I suppose that you need to add a DevExtremeModule to imports of your root module. To find the real cause of this error, please provide an example, what demonstrate this behavior. You can use our [plunker template](http://plnkr.co/edit/tpl:3MUrYspAm1RfHLSrc6CP?p=preview) for this.
