### ISSUE TITLE
dxPopup content not displayed

### ISSUE THREAD

**Issue by jandresampaio** [DevExpress/devextreme-angular#300]
I've followed "DxPopUp not transcluding content #19" but content is still not visible, using the example provided (with a simple div). Is this a recent problem that results from Angular2 updates?

Thank you.

**Comment by kvet** [comment]
Here is [a working example with dxPopup](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Popup/Overview/Angular/Light/). Can you describe the issue in greater detail or give us a sample project demonstrating the issue?

**Comment by jandresampaio** [comment]
Tried that example but instead of using mock data I've used the following:
<dx-popup
        [width]="300"
        [height]="250"
        [showTitle]="true"
        title="Information"
        [dragEnabled]="false"
        [closeOnOutsideClick]="true"
        [(visible)]="popupVisible">
        <div *dxTemplate="let data of 'content'">
            <p>
                Full Name:
            </p>
           
        </div>
    </dx-popup>


I receive the error: 
![image](https://cloud.githubusercontent.com/assets/13848625/21394367/4233c12e-c790-11e6-9850-21c1918cf84a.png)

My files:

**Html:**
![image](https://cloud.githubusercontent.com/assets/13848625/21394453/9cc93614-c790-11e6-90dd-c83ac8c7e3c7.png)

**Component imports:**
![image](https://cloud.githubusercontent.com/assets/13848625/21394484/b3eb9fe4-c790-11e6-8e9c-58fa6249af16.png)

**Component showInfo() method:**
![image](https://cloud.githubusercontent.com/assets/13848625/21394499/c328f3b2-c790-11e6-9590-540ee3d666e7.png)

If I change the *ngTemplate from "let data of 'content'" to "let t= data of 'contentTemplate'" (like thread nº 19), the error goes way but no content is displayed.

Thank you.

**Comment by kvet** [comment]
Syntax "let t= data of 'contentTemplate'" [is not supported anymore](https://github.com/DevExpress/devextreme-angular/blob/master/CHANGELOG.md#1622-beta1-2016-11-25).

[The example based on your screenshots](http://plnkr.co/edit/YxhThBM1hZMb7J01opCE?p=preview) works well.

**Comment by jandresampaio** [comment]
After viewing the Changelog, I've noticed we upgraded to latest Devextreme version but Angular was still on 2.2.0. After upgrading to 2.3.0, the examples now work.
Thank you for the help.
