### ISSUE TITLE
Russify components devextreme-angular

### ISSUE THREAD

**Issue by Severanin** [DevExpress/devextreme-angular#301]
Hello! 
How can russify components devextreme-angular?
Thanks in advance.

**Comment by DokaRus** [comment]
Hi,
We're planning to add an example that demonstrates how you can create an application via [angular-cli](https://github.com/angular/angular-cli) using devextreme-angular with localization(include Russian) and [devextreme-intl](https://github.com/DevExpress/DevExtreme-Intl) soon. I'll update this issue when we publish it

**Comment by DokaRus** [comment]
We have published [an example](https://github.com/DevExpress/devextreme-examples/tree/16_2/intl-angular) that demonstrates how you can create an angular application using [angular-cli](https://github.com/angular/angular-cli) devextreme-angular and devextreme-intl.
Take a look at ``src/app/app.module.ts`` file - here we load localization messages and set the locale according to the browser's language. If you need to set it to Russian, call ``locale("ru")``.
Feel free to ask if you will need further assistance.

**Comment by Severanin** [comment]
Thanks!
