### ISSUE TITLE
Using devextreme-intl with Angular 2 Quick Start

### ISSUE THREAD

**Issue by palexander30** [DevExpress/devextreme-angular#302]
Looking for examples of how to use the Globalize  devextreme-intl, with the Angular 2 Quick Start

How to set systemjs.config.js, app.module, loading localised json files etc

**Comment by DokaRus** [comment]
Hi,
We're planning to add an example that demonstrates how you can create an application via [angular-cli](https://github.com/angular/angular-cli) using devextreme-angular with localization and [devextreme-intl](https://github.com/DevExpress/DevExtreme-Intl) soon. I'll update this issue when we publish it

**Comment by DokaRus** [comment]
We have published [an example](https://github.com/DevExpress/devextreme-examples/tree/16_2/intl-angular) that demonstrates how you can create an angular application using [angular-cli](https://github.com/angular/angular-cli) devextreme-angular and devextreme-intl.
Feel free to ask if you will need further assistance.
