### ISSUE TITLE
dx-file-uploader not firing events

### ISSUE THREAD

**Issue by luigidallavalle** [DevExpress/devextreme-angular#305]
Basically I cannot get dx-file-uploader firing any events,
here's how it's placed into the template:
`<dx-file-uploader
  [multiple]="true"
  [accept]="'*'"
  (value)="value"
  [uploadMode]="'instantly'"
  [uploadUrl]="uploadUrl"
  (uploaded)="fileUploaded($event)">
</dx-file-uploader>`
The web api that stands behind uploadUrl is getting called and simply returns an HTTP 201.

What happens is that the event's handler of (uploaded) is not being fired, I've also tried other events but it seems they suffer from the same issue. Does the web api response need to return something different that a 201 http status code?

Thanks in advance,
Luigi

**Comment by DokaRus** [comment]
Hi,
Try using `[onUploaded]="fileUploaded($event)"` instead of `(uploaded)="fileUploaded($event)"`

**Comment by luigidallavalle** [comment]
I've tried bit I got the following errore during Angular loading: "Template parse errors: Binding to event property 'onUploaded' is disallowed for security reasons, please use (Uploaded)=...".

I tried with the uppercase 'U' bit the result is still the same, am I missing something?

**Comment by DokaRus** [comment]
Oh, my fault. Use round braces, like this `(onUploaded)="fileUploaded($event)"`

**Comment by luigidallavalle** [comment]
It works!
Thanks

**Comment by DokaRus** [comment]
You're always welcome!

**Comment by reachmururalimurugan** [comment]
Hi,
With above example, I need to call event's handler of (uploaded) in client side without specifying the url.
Is it possible?Could you help me on this?
