### ISSUE TITLE
How can I format the label of a dx-range-selector

### ISSUE THREAD

**Issue by bonejon** [DevExpress/devextreme-angular#306]
Hi,

I am using devextreme v16.1, an would like to change the date format of the range selector label. I found the following article on the devexpress site [https://www.devexpress.com/Support/Center/Question/Details/T342574](https://www.devexpress.com/Support/Center/Question/Details/T342574), however I cannot work out how to implement this against the angular2 component.

I would be grateful if you could assist with an example.

Thanks, Jon.

**Comment by GoshaFighten** [comment]
Assign your configuration object to the scale option:
 
``` HTML
<dx-range-selector 
[scale]="{
label: {
customizeText: customizeText
}
}"
</dx-range-selector>
```
See [Plunker](http://plnkr.co/edit/y3BwrzFVFuy6OQgK9hhu?p=preview) that illustrates this.

**Comment by bonejon** [comment]
@GoshaFighten thanks for the example plunker, I also needed the slideMarker customizeText function.
