### ISSUE TITLE
Issue with Bootstrap 4 

### ISSUE THREAD

**Issue by martinmasse** [DevExpress/devextreme-angular#307]
Hi,

I have followed the instructions to add devextreme to a Angular-CLI generated application. It work fine.

Problems start when I add Bootstrap 4 using the instructions found on that page
https://github.com/angular/angular-cli

Then I get the following error.

Uncaught TypeError: Cannot read property 'jquery' of undefined
    at Object.<anonymous> (deferred.js:25)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (common.js:12)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (string.js:11)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (error.js:12)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (errors.js:10)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (fx.js:11)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (accordion.js:11)
    at __webpack_require__ (bootstrap c038965…:52)
    at Object.<anonymous> (accordion.js:20)

Bootstrap 4 works fine if devextreme is not added to the app.

Any idea how to solve this issue?

Thanks

**Comment by GoshaFighten** [comment]
Bootstrap requires jQuery to be in the global scope. But, we are loading jQuery as a module. They are not compatible by default. I've attached a sample project created using Angular-CLI. The project loads a simple module as the following:
``` JAVASCRIPT
var $ = require("jquery");
alert($.fn.jquery);
```
As you can see, you are getting the error that 'jquery' is undefined. If you clear the `scripts` of the `angular-cli.json` file, you see that this module does work. To handle this scenario, it's necessary to customize the Webpack configuration file to use the `ProvidePlugin` as illustrated in the [https://github.com/GoshaFighten/Angular2DXWebpackDotNetCore/blob/master/webpack.config.vendor.js#L45](https://github.com/GoshaFighten/Angular2DXWebpackDotNetCore/blob/master/webpack.config.vendor.js#L45) line. But, Angular-CLI does not provide an API to specify this. See the [https://github.com/angular/angular-cli/issues/1656](https://github.com/angular/angular-cli/issues/1656) issue on the Angular-CLI repository. I suggest you use an Angular project with Webpack without Angular-CLI.
[GH307.zip](https://github.com/DevExpress/devextreme-angular/files/673219/GH307.zip)

**Comment by martinmasse** [comment]
Ok thanks. Il will do that.

**Comment by LuisANino** [comment]
Use angular-cli 1.0.0-beta.30 = @angular/cli@1.0.0-beta.30,  and @ngtools/webpack@1.2.4 for tenmporal fix (https://github.com/angular/angular-cli/issues/4338)
