### ISSUE TITLE
DxAccordion-close accordion

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#308]
How can i close accordion with one item i created 18 accordion 

For example

                <dx-accordion *ngFor="let cat of form.FormCategories" [items]="[{title:cat.Name}]" collapsible="false">
                    <div *dxTemplate="let a of 'item'">
                        <div class="panel-group">
                            <div class="panel panel-success">
                                <div class="panel-body">
                                    <table class="pull-left" style="margin-right:15px; width:15%" *ngFor="let detail of cat.FormDetails">
                                        <tr>
                                            <td width="10px" valign="middle" style="padding:7px">
                                                <dx-check-box [(value)]="detail.Checked" (onValueChanged)="procedureRequestOnChange(detail.Id, detail.Checked)"></dx-check-box>
                                            </td>
                                            <td valign="middle" align="left" style="padding:7px" [ngStyle]="detail.Color">{{detail.Name}}</td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </dx-accordion>

**Comment by GoshaFighten** [comment]
What do you mean by "close accordion"? Do you mean having all its items collapsed? If so, you need to enable the `collapsible` option.

**Comment by Consi007** [comment]
Yes collapsed

**Comment by GoshaFighten** [comment]
If the `collapsible` option is enabled, a user can collapse all accordion items. Doesn't it work for you?

**Comment by Consi007** [comment]
no dont work for me

**Comment by Consi007** [comment]
But i want firstly page initilize all accordions collapsed. Then if user want open it, for this code.

**Comment by GoshaFighten** [comment]
As far as I understand, you need to have all items to be collapsed when a user opens your page. Am I correct? I see that you are rendering a new accordion for each item. I don't think you need this. I think you need to have one accordion with all items. To have all items collapsed by default, set the `selectedIndex` option to `-1`. So, your code will look as follows:
``` HTML
<dx-accordion [collapsible]="true" [selectedIndex]="-1">
    <dxi-item *ngFor="let item of source" [title]="item.title">
        {{item.content}}
    </dxi-item>
</dx-accordion>
```
``` TypeScript
export class App {
    constructor() {
        this.source = [{title: 'First', content: 'First'}, {title: 'Second', content: 'Second'}]
    }
}
```
See [Plunker](http://plnkr.co/edit/1pEQna1XX3ffkXPfQ7ax?p=preview) that illustrates this.

**Comment by Consi007** [comment]
Thanks...
