### ISSUE TITLE
dx-data-grid: how to select(focus) row from the code?

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#309]
Hi, we need to select a first row in dx-data-grid when data is loaded. I couldn't find any Input property on  dx-data-grid where I could bind the row and make it selected.

**Comment by GoshaFighten** [comment]
The grid provides the `selectedRowKeys` option to select records programmatically. You can bind your property to this option that will hold the key of the first row. If this does not work for you, provide me with a sample that reproduces the issue. You can use our [Plunker template](http://plnkr.co/edit/tpl:3MUrYspAm1RfHLSrc6CP?p=preview) for this.

**Comment by RezaRahmati** [comment]
Hey @GoshaFighten my grid has paging and record I want to focus is not on first page, by using selectedRowKeys it will select but it won't focus to bring it in viewable area. Is there any workaround for it?
