### ISSUE TITLE
exportAs

### ISSUE THREAD

**Issue by GPetrites** [DevExpress/devextreme-angular#312]
DxSelectBoxComponent does not appear to have an exportAs property set on the component decorator. The exportAs would allow us to use a reference to the select box in the template as well as obtaining named references in the component class using ViewChild.  If exportAs was configured, we would be able to do something like:

<dx-select-box #selectBox1="dxSelectBox" ... />
<dx-select-box #selectBox2="dxSelectBox" .../>

@ViewChild("selectBox1") selectBox1: DxSelectBoxComponent;
@ViewChild("selectBox2") selectBox2: DxSelectBoxComponent;

**Comment by kvet** [comment]
Hi,
 
Here is an example with the requested functionality: http://plnkr.co/edit/W4hCwTGbGIOX0ZKX3IB7?p=preview. It operates well on my side.
 
Can you modify this example to show us the scenario that doesn't work?
