### ISSUE TITLE
dx-data-grid: cssClass on cell works only for global styles

### ISSUE THREAD

**Issue by hneuer** [DevExpress/devextreme-angular#315]
version: 16.2.3-rc.3

Setting the cssClass property on a cell ( https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#cssClass ) works only for classes which are defined globally. Classes defined in an angular component do not work, as they are scoped to the component.

I would expect this to work for classes from the component's styles too.

**Comment by dxvladislavvolkov** [comment]
Hello!
It's the same issue as in #124 . So, I am closing the current ticket.
