### ISSUE TITLE
How to edit datagrid's datasource item without save button?

### ISSUE THREAD

**Issue by gonulboluk** [DevExpress/devextreme-angular#318]
As seen in image, we don't want  to see Save  ikon on the right above of the grid. 
For this grid editing attributes like this 

[editing]="{mode: 'batch' ,editEnabled:true , insertEnabled:false, removeEnabled:false}
![devextreme-mail-jpg](https://cloud.githubusercontent.com/assets/24889541/21603251/5f63f20a-d1a4-11e6-9a76-751c832675e1.png)

**Comment by DokaRus** [comment]
Hi,

Please refer to the [dxDataGrid "Editing in code" guide](https://js.devexpress.com/Documentation/16_2/Guide/Widgets/DataGrid/Data_Editing/#Editing_in_Code).
You can also find the ["Cell Editing and Editing API" technical demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Data_Grid/CellEditingAndEditingAPI/Angular/Light/) useful.
If you need assistance that is not related to the devextreme-angular integration directly, you can also ask any question in our [Support Center](https://www.devexpress.com/Support/Center/Question).
