### ISSUE TITLE
Loadoptions (skip, take, filter, sort) not available in CustomStore?

### ISSUE THREAD

**Issue by tcn-verla** [DevExpress/devextreme-angular#319]
I'm using the new version of the customstore like this:
```
import CustomStore from "devextreme/data/custom_store";

orders = new CustomStore({
    load: (opts) => {
        return new Promise((resolve, reject) => {
            resolve([{ text: "Test" }]);
        });
    },
    totalCount: (opts) => {
        return new Promise((resolve, reject) => {
            resolve(1);
        });
    }
});
```

In the (opts) parameters, I can't find the skip, take, filter and sort options that used to be available. Am I doing something wrong or are they no longer supported?

devextreme-angular version: 16.2.3-rc.3

**Comment by GoshaFighten** [comment]
I believe this issue relates to the [BC3882](https://www.devexpress.com/Support/Center/VersionHistory?TechnologyName=DevExtreme+(HTML+JS)&PlatformName=AllPlatforms&ProductName=AllProducts&VersionHistoryItemsType=BreakingChanges&StartBuildName=16.2.3&EndBuildName=16.2.3&version-mode=single-mode#BC3882) breaking change introduced in version 16.2. Now, the grid performs paging, sorting, filtering on the client if CustomStore is used. Explicitly enable the `remoteOperations` option to get the previous behavior.
If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question).

**Comment by tcn-verla** [comment]
OK, thank you for the clarification
