### ISSUE TITLE
dx-tree-view - The onItemContextMenu callback does not work

### ISSUE THREAD

**Issue by NikitaKunashov** [DevExpress/devextreme-angular#320]
The issue is reproducible with the [online demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tree_View/ItemSelectionAndCustomization/)
While the callback works in the jQueryApproach it does not work with the angular approach. Here is the code snippet used for my tests:
`<dx-tree-view
        id="selection-treeview"
        [items]="products"
        [width]="320"
        showCheckBoxesMode="normal"
		(onItemContextMenu)="contextMenu($event)"
        (onItemSelectionChanged)="selectionChanged($event)"
    >`

`    contextMenu(){
		debugger;
	}`

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular 2 integration. **itemContextMenu** and **itemHold** events don't work for dxTreeView widget. I have created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T470287) in our Support Center.
