### ISSUE TITLE
How can I make accordion like menu?

### ISSUE THREAD

**Issue by gonulboluk** [DevExpress/devextreme-angular#322]
![untitled](https://cloud.githubusercontent.com/assets/24889541/21758947/ff8f94de-d648-11e6-847a-c4c8fc329898.png)

Picture on the left is the current situation. But we want to open accordion like right picture, when the accordion opened, we don't want to slide other components below like right picture.

**Comment by kvet** [comment]
Hi,
 
The DxAccordion widget doesn't provide such functionality. We will take it into account in future releases.
 
As an alternative, I can recommend using the DxTabPanel widget. Also, you may combine, for example, the DxMultiView widget with DxMenu, DxRadioGroup or DxTabs.

**Comment by gonulboluk** [comment]
Thank you for your comments :)
Could you give us a sample in feddler?

**Comment by kvet** [comment]
We have a demo demonstrating how to combine DxAccordion with DxSelectBox: https://js.devexpress.com/Demos/WidgetsGallery/Demo/Accordion/Overview/Angular/Light/. Use the same approach for your scenario.
 
Also, there are other demos that can help you achieve your goal:
- [DxTabPanel](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tab_Panel/Overview/Angular/Light/)
- [DxMultiView](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Multi_View/Overview/Angular/Light/)
