### ISSUE TITLE
dxAccordion - Two-way binding for the selectedItems option does not work in development mode

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-angular#323]
See the [this](http://plnkr.co/edit/7hGbArqNoADyaWAbSRMV?p=preview) example that shows the issue in action. Click the "collapse all" button. It should collapse all items. There is no issue in the production mode (enableProdMode()).

**Comment by kvet** [comment]
Hi,
 
We have reproduced the issue. As a workaround, set the `selectedIndex` property to `-1`. [Updated example](http://plnkr.co/edit/Sqh1hslCdQuO8LKAcb8L?p=preview).
