### ISSUE TITLE
Final version???

### ISSUE THREAD

**Issue by marcelgood** [DevExpress/devextreme-angular#327]
When will we see the final npm package? The current package is 3 months old and was released before Angular 2 went final. My understanding was the final release was planned for about a month after the final release of Angular 2. What happened to that?

**Comment by hneuer** [comment]
Are you looking at the wrong package? The current one can be found here: https://www.npmjs.com/package/devextreme-angular

**Comment by marcelgood** [comment]
Yes, apparently so. I missed that the package got renamed. I'm still using devextreme-angular2.

**Comment by marcelgood** [comment]
Are there any instructions for how to migrate from the old devextreme-angular2 package to the new devextreme-angular package. This is turning into a major pitta. Looks like the dependency are managed very different know. Our app is using jQuery as well, so we have it statically loaded as was previously required with the old package, but now it's managed as a module dependency, which is messing everything up for me. I'm trying to look at the updated examples and see what I have to remove and change etc.
