### ISSUE TITLE
DxDataGrid always displays the loading panel if its data source is provided using a function

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular#328]
See [Plunker](http://plnkr.co/edit/VKToRrqmi7o89VIaRnxq?p=preview). As you can see the loading panel is always displayed.

**Comment by hneuer** [comment]
Isn't creating a new datasource on each call the problem? Angular's change detection kicks then in.

Try this:

```
export class App {
  ds: ODataStore;
  
  constructor() {
    this.buttonText = 'DevExtreme button!';
    this.ds = new ODataStore({
        url: "http://services.odata.org/V4/Northwind/Northwind.svc/Orders",
        version: 4,
        key: "OrderID",
        keyType: "Int32"
    });
  }
  getDataSource(grid: DxDataGridComponent): ODataStore {
    return this.ds;
}
}

```

**Comment by NickMitrokhin** [comment]
Set the [changeDetection](https://angular.io/docs/ts/latest/api/core/index/ChangeDetectionStrategy-enum.html) option to **OnPush** to prevent Angular from tracking component entire changes. See the [ANGULAR CHANGE DETECTION EXPLAINED](https://blog.thoughtram.io/angular/2016/02/22/angular-2-change-detection-explained.html) article to learn more. I've updated your [example](http://plnkr.co/edit/tUhRw2JSJNaeLkGMd7GO?p=preview).
