### ISSUE TITLE
global jQuery side-by-side with devextreme-angular

### ISSUE THREAD

**Issue by marcelgood** [DevExpress/devextreme-angular#330]
I'm trying to switch to the new devextreme-angular package from the devextreme-angular2 package. The old package had a dependency on the global jQuery and I'm using some other third-party libraries that depend on the global jQuery, so I continue to need to load it globally. However, devextreme-angular does require('jquery') now and loads it as an external module, which is causing issues with also trying to load jQuery globally. require('jquery') seems to replace the global '$', so I'm loosing all the extensions that the other third-party libs install to jQuery. How can I get devextreme-angular to use the global jQuery instead of requiring it.

**Comment by GoshaFighten** [comment]
Such tasks are handled by configuring the bundler tool you are using. Webpack, for example, provides the `ProvidePlugin` plugin for this purpose. See the [line](https://github.com/GoshaFighten/Angular2DXWebpackDotNetCore/blob/master/webpack.config.vendor.js#L45) in the `webpack.config` file that illustrates how to use it.

**Comment by marcelgood** [comment]
Thanks. That's where I landed in the meantime as well. I reverted back to SystemJS and I'm using a SystemJS adapter module to handle this, but eventually I need to move back to Webpack, so thanks for the pointer.
