### ISSUE TITLE
Cannot make dx-lookup work with dynamic list&pre-selected item

### ISSUE THREAD

**Issue by chaonextdoor** [DevExpress/devextreme-angular#334]
I'm using the 16.1.17 version. The thing is if I‘m passing a static array list as dataSource, the pre-selected item works as expected. But when I want to use a dynamic list, like a http call to the back-end, then I cannot make the pre-selected item work at all. If I understand correctly, only the `value` and `valueExpr` control the pre-selected item setup. But I tried different combination of `value` and `valueExpr` and nothing magic happened. I guess it's probably because since the list is dynamic, it's impossible to check whether or not the pre-selected item is part of the list during initialization?

**Comment by anna-zhernovkova** [comment]
Hello,
 
It looks like this issue is a duplicate of #294. Let us know if I'm wrong.
