### ISSUE TITLE
devextreme-angular@16.2.3-rc.4 requires a peer of devextreme@~16.2.4-0 but none was installed.

### ISSUE THREAD

**Issue by marcelgood** [DevExpress/devextreme-angular#335]
I just installed rc.4, but devextreme 16.2.4 is not published yet. The latest is 16.2.3

**Comment by Aden-git** [comment]
Hello @marcelgood 

You are right, we do not released devextreme 16.2.4, but we published pre-release version of devextreme. You can get access to it by use "16.2-unstable" tag, as `npm i devextreme@16.2-unstable`, or specify a version in package.json as "~16.2.4-0".

**Comment by Aden-git** [comment]
Hello @stephanblaurock.
 
We need some more details to reproduce this behavior. Please check what version of npm you are using? You can check it by using the `npm -v` command.

**Comment by stephanblaurock** [comment]
Hello @Aden-git ,
thanks for your answert. My Version of npm = 3.10.9
Now i have deinstalled all devextreme + devextreme-angular-packages and reinstall the unstable, now it works fine :-)
Thanks!

**Comment by Aden-git** [comment]
@stephanblaurock,

Glad to help you! If you have any questions - feel free to contact us.

**Comment by Aden-git** [comment]
Yesterday we published a devextreme 16.2.4 and devextreme-angular 16.2.4 npm packages with "latest" tags, so now you can install it with the following npm command: `npm i devextreme devextreme-angular -S`.
