### ISSUE TITLE
DateTimePicker format string

### ISSUE THREAD

**Issue by gonulboluk** [DevExpress/devextreme-angular#341]
How can i set format string "dd/MM/yyyy hh:SS" to datetimepicker? And how can I ignore  AM / PM indicator?

**Comment by nightskylark** [comment]
Hi
Dates formatting in DevExtreme can be configured by a [`format` object structure](https://js.devexpress.com/Documentation/16_2/ApiReference/Common/Object_Structures/format/). It can accept one of the predefined shortcut values out of the box.
If you want to use custom formatting, you need to use one of third-party libraries ([Intl](https://github.com/DevExpress/DevExtreme-Intl) or [Globalize](https://js.devexpress.com/Documentation/16_2/Guide/Widgets/Common/UI_Widgets/Localization_-_Use_Globalize/)). You can see the examples of using these libraries in Angular applications [here](https://github.com/DevExpress/devextreme-examples).
Please note, that LDML patterns such as "dd/MM/yyyy hh:SS" are not supported by the `Intl`, but you can use the [Intl.DateTimeFormat parameters object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Parameters) instead.
