### ISSUE TITLE
dxScrollView doesn't have the display: block style and scrolling doesn't work

### ISSUE THREAD

**Issue by artem-kurchenko** [DevExpress/devextreme-angular#343]
devextreme-angular@16.2.3-rc.4

dxScrollView should have this style out of the box for proper scrolling. 
Example - http://plnkr.co/edit/cYQbKLRlZfghS6MTtzNx?p=preview

**Comment by kvet** [comment]
Duplicated in [T472952](https://isc.devexpress.com/Thread/WorkplaceDetails/T472952)
