### ISSUE TITLE
first item of list dx-item does not render, using promise and observable Angular 2

### ISSUE THREAD

**Issue by paulo3262** [DevExpress/devextreme-angular#345]
- devextreme-angular : "16.2-rc"
- When inject array in promisse or observable does not render first item in angular 2 

- if is made with *dxTemplate It works.
![captura de tela de 2017-01-17 13-32-47](https://cloud.githubusercontent.com/assets/17967366/22026974/79bc6b08-dcb9-11e6-9a8a-2aa6211f02c1.png)

Can someone help me?

**Comment by kvet** [comment]
Hi, 

The issue has been fixed in `16.2.3-rc.4`. Original bug: https://www.devexpress.com/Support/Center/Question/Details/T468713
