### ISSUE TITLE
Devextreme 16.2.4 DxDataGrid Header Text Margin with Alignment Center 

### ISSUE THREAD

**Issue by Angelminster** [DevExpress/devextreme-angular#350]
Hi,

It seems that in columns with templates or affected by globalilze (dates) you are creating two "**dx-column-indicators**" inside the column header.

One with class="dx-column-indicators" style="float: right;" and the invisible one with class="dx-column-indicators dx-visibility-hidden". Both contains sort and filter items.

This invisible item cause a left margin in the column header text.

Regards

**Comment by Aden-git** [comment]
Hello @Angelminster,
 
Could you please provide your set of options to help us reproduce this behavior?

**Comment by Angelminster** [comment]
Hi,

It seems a problem with alignment: 'center' in all kind of columns. When i remove this option, the invisible column-indicator disappears and works as expected.

You can reproduce the behaviour in any of your demo page (alignment center, filterheader visible and allowColumnResizing) trying to resize as small as possible a column: 
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Data_Grid/ColumnTemplate/Angular/Light/Compact/

Copy this markup:

```
<dx-data-grid id="gridContainer" [dataSource]="employees" [allowColumnResizing]="true" [headerFilter]="{visible : true }">

    <dxi-column dataField="Picture" [allowFiltering]="false"
        [allowSorting]="false" cellTemplate="cellTemplate" alignment="center" ></dxi-column>
    <dxi-column dataField="Prefix" caption="Title"></dxi-column>
    <dxi-column dataField="FirstName" alignment="center" ></dxi-column>
    <dxi-column dataField="LastName" alignment="center" ></dxi-column>
    <dxi-column dataField="Position" alignment="center" ></dxi-column>
    <dxi-column dataField="BirthDate" dataType="date"></dxi-column>
    <dxi-column dataField="HireDate" dataType="date"></dxi-column>
    <div *dxTemplate="let data of 'cellTemplate'">
        <img [src]="data.value"/>
    </div>
</dx-data-grid>
```

Regards

**Comment by Aden-git** [comment]
It looks like this issue is not related to the Angular 2 integration. I have created a corresponding ticket ([T474801](https://www.devexpress.com/Support/Center/Question/Details/T474801)) in our Support Center.
