### ISSUE TITLE
Tree shaking support

### ISSUE THREAD

**Issue by kvet** [DevExpress/devextreme-angular#353]
Currently, it is required to use [long paths](https://github.com/DevExpress/devextreme-angular#bundlers-without-tree-shaking-support) in order to reduce bundle size.

**Comment by kvet** [comment]
This issue is related to #283

**Comment by feco93** [comment]
Do you plan to fix it?

**Comment by GoshaFighten** [comment]
@feco93 , this is not something in our immediate plans. To properly support Tree Shaking, it's necessary to re-write the entire DevExtreme code. It's unlikely this will be implemented in the near future.
