### ISSUE TITLE
Input mask for dx-text-box cannot be reset

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#356]
If you have the input mask set and try and reset it back to blank, the mask still shows up in the textbox.

If you set the mask to something other than null/double quotes it works as expected.

Affects 16.2.4. 

See Plunker. It has a mask set, if you type something in the textbox directly below the change mask button and then click the button the mask will be changed.

http://plnkr.co/edit/VkIV6Zikla6P2EZ2jOc9?p=preview

Any workarounds would be great.

**Comment by GoshaFighten** [comment]
This is an issue in our dxTextBox. I've created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T476866) in our Support Center. Track it to be notified of our results.
