### ISSUE TITLE
DxScheduler: custom cell duration for a view not working

### ISSUE THREAD

**Issue by w-andre** [DevExpress/devextreme-angular#357]
I tried to specify a custom cell duration for a view like this (devextreme-angular 16.2.4):

```html
<dx-scheduler>
    <dxi-view type="workWeek" cellDuration="15"></dxi-view>
</dx-scheduler>
```

The rendered view has a cell duration of 15 minutes, but the size of the appointments do not change. They are still rendered as if the view has a cell duration of 30 minutes.
Full working example: [Link](http://plnkr.co/edit/puB6avPCiyn8rkvaMbgQ?p=preview)

![image](https://cloud.githubusercontent.com/assets/12671470/22251070/c11aa29a-e249-11e6-8a46-0030352b40af.png)

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular integration. I have created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T475743) in our Support Center.
