### ISSUE TITLE
DxFileUploaderComponent uploadHeaders not working

### ISSUE THREAD

**Issue by yotga** [DevExpress/devextreme-angular#358]
Hello,

   I'm using devextreme-angular@16.2.4, on Windows 10.

   I'm trying to upload files to my WebApi with headers, because WebApi request must have token JWT in header in order to be validated.

   I see in DxFileUploaderComponent.d.ts that exists the property "uploadHeaders: any;", but although I try to fill it, the WebApi is not receiving any header.

   The HTML of my component looks like:
       <dx-file-uploader [uploadUrl]="uploadUrl" [uploadHeaders]="uploadHeaders"
                                    [multiple]="false" accept="*" (value)="value" uploadMode="instantly">
       </dx-file-uploader>

   And my component looks like:

   export class VehiculoDetailAdjuntosComponent implements OnInit {

    // Variables para hacer el Upload
    value: any[] = [];
    uploadUrl: any;
    uploadHeaders: any;

   constructor(private route: ActivatedRoute, private tokenService: TokenService) { }

    ngOnInit() {
        let id = null;
        this.route.parent.params.forEach((params: Params) => {
            id = params['id'];
        });

        if (id != null) {
            this.uploadUrl = 'http://localhost/api/' + id + '/attached';

            let headers = new Headers();
            headers.append("Authorization", "Bearer " + this.tokenService.getToken())
            this.uploadHeaders = headers;
       }
   }

   Anyone has faced the same problem? Any idea to solve it?

   Thanks in advance,
Regards

**Comment by GoshaFighten** [comment]
As far as I understand, the Headers class is from [the `@angular/http` package](https://angular.io/docs/ts/latest/api/http/index/Headers-class.html). Our FileUploader does not work with it. You need to create an object like this:

``` TypeScript
this.uploadHeaders = { "Authorization": "Bearer " + this.tokenService.getToken() };
```
