### ISSUE TITLE
DxDataGrid 2-way binding to an array element does not work

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#360]
Hey,

I have a data model with an array field. The example of simplified model looks like this
```
[
   {
     label: 'First row', 
     array:[
       {value: 0},
       {value: 1},
       {value: 2}]
     
   },
...
]
```
I need to bind columns to the values within array so I'm declaring dataField as following:
`dataField: 'array[0].value'`
It works with the read binding. But when I do changes in this cell and click save, binding does not update the value in the array. Instead, it creates a separate field with name `array[0].value`

You can see example by this link: https://plnkr.co/edit/KUwhHcZTQg2ADjJ9k5Xf?p=preview
Click edit, change val1 value and click save.
1. Notice that val1 value has not been changed
2. Check console log for details.

Is it angular2 specific issue in devextreme or general devextreme issue?

**Comment by GoshaFighten** [comment]
dxDataGrid does not support this. While you can display a collection property's items in this way, you can't edit them. See the [dxDataGrid - Edit doesn't work with collection binding](https://www.devexpress.com/Support/Center/Question/Details/T420882) ticket.
