### ISSUE TITLE
After opening/closing a dx-popup widget, Angular2 routing is broken

### ISSUE THREAD

**Issue by jandresampaio** [DevExpress/devextreme-angular#367]
Using devextreme-angular for angular2, I have a main page (a list with a dx-button that opens a dx-popup widget:

Project list:
![image](https://cloud.githubusercontent.com/assets/13848625/22381613/3487178c-e4ba-11e6-8cb7-9c3fbf25dd1d.png)
![image](https://cloud.githubusercontent.com/assets/13848625/22381706/88f66502-e4ba-11e6-89eb-571c2ac4dfd6.png)

Project-popup-new:
![image](https://cloud.githubusercontent.com/assets/13848625/22381638/48edd634-e4ba-11e6-9511-46779e40d76c.png)

After closing the dx-popup, routing stops working, when trying to navigate to other row items. If I don't open the dx-popup, routing is Ok.

Any clues on this issue?

Thank you.

**To help us process your issue more efficiently, please provide the following information:**

- Specify the version of the *devextreme-angular* package. If you replaced the default version of the *devextreme* package, please specify it as well.
- If you consider the issue to be a bug, provide detailed steps to reproduce it. If possible, create a demo illustrating the problem using https://plnkr.co or a similar service. Feel free to use the [template for version 16.2](http://plnkr.co/edit/tpl:3MUrYspAm1RfHLSrc6CP?p=preview) or [template for version 16.1](http://plnkr.co/edit/tpl:HNf0vB?p=preview).

**Comment by GoshaFighten** [comment]
This issue is known to us. Please provide me with a sample project to reproduce it. At the moment, I don't see any reason why our popup may break routing in Angular applications.

**Comment by jandresampaio** [comment]
What files (or configurations) do you need to replicate this behavior ? 

Thank you.

**Comment by jandresampaio** [comment]
Hello,

This was caused by other problem not related to Devextreme but to Angular2.

**Comment by reemagadhia** [comment]
I am facing the similar issue. Can you specify how was the issue solved?
