### ISSUE TITLE
DxSelectBox. I can select disabled item by arrow keys

### ISSUE THREAD

**Issue by xbadcode** [DevExpress/devextreme-angular#369]
DevExtreme Version: devextreme-angular 16.2.4
DxSelectBox. I can select disabled item by arrow keys Up and Down on keyboard when drop-down list is hidden.
My code:
`
import { Component } from '@angular/core';

@Component({
    selector: 'my-dropdown',
    template: '<dx-select-box [dataSource]="contactTypes" displayExpr="name" valueExpr="id" searchEnabled="true" searchExpr="name"></dx-select-box>'
})
export class DropdownComponent {
    contactTypes: any;

    constructor() {
        this.contactTypes = [
            { id: 1, name: "first" },
            { id: 2, name: "──────────", disabled: true },
            { id: 3, name: "third"}
        ];
    }
}
`

**Comment by Aden-git** [comment]
Hello @xbadcode 

We made some research and found that this issue is not related to Angular integration, so I created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T479073) in our support center. Please refer to it to be informed of our progress.
