### ISSUE TITLE
DxTextBox. Dirty is set by default

### ISSUE THREAD

**Issue by xbadcode** [DevExpress/devextreme-angular#370]
The version of the *devextreme-angular* package: 16.2.
Why DxTextBox is allways dirty, but simple HTML input is not dirty?
http://plnkr.co/edit/xmouc6THcKSNeLQV9Wom?p=preview

In version 16.1 dirty works fine. Both DxTextBox and simple HTML input is not dirty.
http://plnkr.co/edit/i55TLWfAbR3Zd87MsqcZ?p=preview

**Comment by dxvladislavvolkov** [comment]
This issue is a bug on the side of angular. You can see details of the issue [here].(https://github.com/angular/angular/issues/14988) 
You can use the following [workaround](http://plnkr.co/edit/Ffe4RiXawYi7u6hW2d11?p=preview) while the issue is present.
