### ISSUE TITLE
Input mask for dx-text-box cannot be reset

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#371]
Continuation of previous issue of same name.

https://www.devexpress.com/Support/Center/Question/Details/T476866

I am trying to use this with your Angular2 implementation.

The file structure is very different in the node modules folder.

It appears that it references ui.text_editor.mask.js

Can you provide some detail on what files have changed and what I need to copy to get it to work.

**Comment by GoshaFighten** [comment]
Install the latest unstable DevExtreme version as Alex described in the mentioned ticket via NPM. The new package will update all required files.
