### ISSUE TITLE
dx-Select-box allows null values - how to prevent this behavior

### ISSUE THREAD

**Issue by jandresampaio** [DevExpress/devextreme-angular#373]
We have a form with some dx-select-box but we noticed that these allow the user to delete the datasource values manually, resulting on a null value. We would need to prevent this behavior by always selecting by default the first element of the array, in this case, the clientsDatasource.values[0]. How can we do this without using any validator, forcing the user to choose a value from the list? 

Code below:

![image](https://cloud.githubusercontent.com/assets/13848625/22659722/ab3230b8-ec96-11e6-8dd9-e726ba4bbd64.png)

![image](https://cloud.githubusercontent.com/assets/13848625/22659748/c6f218fe-ec96-11e6-9d93-45e7c927422b.png)

Thank you.

**Comment by anna-zhernovkova** [comment]
Hello,
Since version 16.2.5, you can check for a `null` value on `onValueChange `event handler: 
    
```
onValueChanged(e) {
    if(e.value === null) {
        this.selectBox.value = e.previousValue;
    }
}
```

I created an [example](http://plnkr.co/edit/Hk4uxPHR9OoMsS5ggE3D?p=preview) to demonstrate this way.
