### ISSUE TITLE
Devextreme angular 2 setup

### ISSUE THREAD

**Issue by shobeir228** [DevExpress/devextreme-angular#375]
I have been trying to install and use devextreme in angular 2 project, and I have done all steps exactly as you said, but still I get this error which can not find devexreme-anglar, any idea?

![image](https://cloud.githubusercontent.com/assets/3613375/22859831/10c8e262-f0b8-11e6-93e4-c808b9647350.png)

**Comment by Aden-git** [comment]
Hello @shobeir228
 
Looks like the problem might be in configuration of your module loading system. To help us find the real reason for this behavior, please provide a sample, or as a start, your configuration of the module loader or bundler system.

**Comment by shobeir228** [comment]
Hi, 

I don't do anything special just I have created new angular 2 project and then doing step by step based on the help, Do I need to to have any additional configuration which is not in the help doc?
https://github.com/DevExpress/devextreme-angular

**Comment by Aden-git** [comment]
I tried to follow our Installation steps and found some difference with Angular QuickStart. I'm not sure that this is the cause of the problem but you may take a look at my [commit](https://github.com/DevExpress/devextreme-angular/commit/2dcb8ee0fea8bb93a5a18378944966f51af6a236#diff-7119ff88f958f237fff35c4bde1f367b) with the fix. Maybe it will help you.
