### ISSUE TITLE
paging and scrollbar not visible when data grid is inside tab panel

### ISSUE THREAD

**Issue by hem19** [DevExpress/devextreme-angular#378]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tab_Panel/Overview/Angular/Light/

I have modified the code of the above url to include data grid inside tabs of tab panel.
The problem is that even though paging is provided, it is not visible if the height of tab panel is provided. If we don't provide height it works fine.
Please replace the code of the app.component.html and app.component.ts in the below URL, with the respective files provided in the attached zip:
[tabPanelDataGridIssue.zip](https://github.com/DevExpress/devextreme-angular/files/776564/tabPanelDataGridIssue.zip)

https://js.devexpress.com/Demos/WidgetsGallery/Demo/Tab_Panel/Overview/Angular/Light/

**Comment by ovchinnikov** [comment]
Hello,
Try to set the dxDataGrid height option to "100%"
