### ISSUE TITLE
Unable to submit a form pressing enter in a textbox and using DevExtreme Validation Features

### ISSUE THREAD

**Issue by RonaldV** [DevExpress/devextreme-angular#379]
devextreme-angular version 16.2.4

You are unable to submit a form pressing enter in a textbox and using DevExtreme Validation Features. params.validationGroup (https://github.com/DevExpress/devextreme-angular#using-devextreme-validation-features) is undefined because the actual event object is being passed.

**Comment by dxvladislavvolkov** [comment]
Hello @RonaldV 
You can try to use the useSubmitBehavior option of dxButton. You can find more information about this option [here](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxButton/Configuration/#useSubmitBehavior). I created an example to demonstrate how this works. You can see it [here](http://plnkr.co/edit/YJMeEwo7apK2ah5425kY?p=preview).

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by cfsean** [comment]
Is there not a way to do this without the button? Seems crazy that I need to add a dxButton just to handle this behavior. Can we look at improving this? Perhaps with a DxUseSubmitBehaviourDirective or similar to put on the form or container element for inputs?
