### ISSUE TITLE
In a DxDataGrid, calculated value for columns are not bound to the rowData

### ISSUE THREAD

**Issue by jandresampaio** [DevExpress/devextreme-angular#381]
We have a DxDataGrid (16.2 version) using batch edit, where 2 columns (Margin and UnitPriceIncome) are calculated based on other columns:

![image](https://cloud.githubusercontent.com/assets/13848625/22988581/85484e44-f3aa-11e6-86e9-2411d0096d6c.png)

For these 2 columns, we use the calculateCellValue to correctly calculate and display the value.
Our Html for the DataGrid is:

![image](https://cloud.githubusercontent.com/assets/13848625/22988652/c76d2826-f3aa-11e6-9096-c518a0b73ed4.png)

One of our calculateCellValue assigned functions is (the other is similar to this):

![image](https://cloud.githubusercontent.com/assets/13848625/22988704/f3c740c8-f3aa-11e6-9ea4-f9522218f409.png)

However, when we need to Update or Insert the row data, using OnRowUpdating or OnRowInserting, the values for data.Margin and data.UnitPriceIncome are NaN, so not valid for us to submit to the server.

How can we get and set these field values in order to correcty submit their values to the server, in each of the events above mentioned?

Thanks.

**Comment by dxvladislavvolkov** [comment]
Hello @jandresampaio 
I created a simple example illustrating how you can get the value of a calculated field.
You can see it [here](http://plnkr.co/edit/2PYC7xTEA9LBLlWrbQza?p=preview).

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
