### ISSUE TITLE
Header filters fetch all data from all columns instead of just one

### ISSUE THREAD

**Issue by lohiarahul** [DevExpress/devextreme-angular#382]
Plot: I have an OData service call as a datasource to my devextreme grid. The datasource contains of approximately 40 columns and I have the header filter enabled for all the columns.

Whenever I click the header filter icon to populate the values for a particular column a request is generated to fetch all the columns which is basically asking for all the data for the grid again.

Simply put, the '$select=columnname' attribute is missing on the header filter service call because of which the filter takes a massive amount of time to load and crashed for large number of rows.

**Comment by ovchinnikov** [comment]
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
