### ISSUE TITLE
Angular 4.0.0-rc.1 | this._trackByFn is not a function on datasources

### ISSUE THREAD

**Issue by guehmann** [DevExpress/devextreme-angular#386]
Using: 
       "devextreme": "^16.2.4",
        "devextreme-angular": "^16.2.5-rc.1"

with new Angular 4.0.0-rc.1

Get the above error on dxDataGrid and dxScheduler if i use datasource from local or http service.
With Angular 4.0.0-beta.7 everything worked fine.

Anybody an idea  what i did wrong or to get a workaround?
Many thanks in advance.

---
Error: Uncaught (in promise): Error: this._trackByFn is not a function
    at View_DashboardHolidayComponent_0 (/AnytimeModule/DashboardHolidayComponent/component.ngfactory.js:47:7) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:317165:31) [angular]
    at resolvePromise (http://localhost:4200/vendor.bundle.js:317141:17) [angular]
    at http://localhost:4200/vendor.bundle.js:317201:17 [angular]
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:12187:331) [angular]
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor.bundle.js:316884:36) [angular]
    at Zone.runTask (http://localhost:4200/vendor.bundle.js:316688:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:4200/vendor.bundle.js:317051:35) [<root>]
    at HTMLAnchorElement.ZoneTask.invoke (http://localhost:4200/vendor.bundle.js:316942:25) [<root>]
handleError @ vendor.bundle.js:11048
next @ vendor.bundle.js:13894
schedulerFn @ vendor.bundle.js:12074
SafeSubscriber.__tryOrUnsub @ vendor.bundle.js:19621
SafeSubscriber.next @ vendor.bundle.js:19570
Subscriber._next @ vendor.bundle.js:19512
Subscriber.next @ vendor.bundle.js:19476
Subject.next @ vendor.bundle.js:21424
emit @ vendor.bundle.js:12069
triggerError @ vendor.bundle.js:12202
onHandleError @ vendor.bundle.js:12189
ZoneDelegate.handleError @ vendor.bundle.js:316856
Zone.runGuarded @ vendor.bundle.js:316664
_loop_1 @ vendor.bundle.js:317062
drainMicroTaskQueue @ vendor.bundle.js:317071
ZoneTask.invoke @ vendor.bundle.js:316942
vendor.bundle.js:317038 Unhandled Promise rejection: this._trackByFn is not a function ; Zone: angular ; Task: Promise.then ; Value: ZoneAwareError     at View_DashboardHolidayComponent_0 (/AnytimeModule/DashboardHolidayComponent/component.ngfactory.js:47:7) [angular]
consoleError @ vendor.bundle.js:317038
_loop_1 @ vendor.bundle.js:317067
drainMicroTaskQueue @ vendor.bundle.js:317071
ZoneTask.invoke @ vendor.bundle.js:316942
vendor.bundle.js:317040 ZoneAwareError
consoleError @ vendor.bundle.js:317040
_loop_1 @ vendor.bundle.js:317067
drainMicroTaskQueue @ vendor.bundle.js:317071
ZoneTask.invoke @ vendor.bundle.js:316942

-----

    /** Konstruktor */
    constructor(private api: GlobalService, public router: Router) {
        this.api.showMenu = false;

        this.resourcesData = [
            {
                text: "Samantha Bright",
                id: 1,
                color: "#cb6bb2"
            }, {
                text: "John Heart",
                id: 2,
                color: "#56ca85"
            }, {
                text: "Todd Hoffman",
                id: 3,
                color: "#1e90ff"
            }, {
                text: "Sandra Johnson",
                id: 4,
                color: "#ff9747"
            }
        ];

        this.appointmentsData = [
            {
                text: "Website Re-Design Plan",
                ownerId: [1],
                startDate: new Date(2017, 2, 25, 9, 30),
                endDate: new Date(2017, 2, 25, 11, 30)
            }
        ];
    }

**Comment by Aden-git** [comment]
Hello @guehmann
 
We working on supporting Angular 4.0.0-rc.1 at the current time and you will be notified in this thread as soon as we finish.

**Comment by guehmann** [comment]
@Aden-git 
Thanks for info.

**Comment by chybie** [comment]
Any updates on this? We are planning to upgrade to Angular 4 as it's release officially. This is the only road block for us now.

**Comment by Aden-git** [comment]
We resolved this issue in the context of #404. Support for Angular 4 will be available with the next release.

**Comment by jecelyniflix** [comment]
Nice, thanks. Do you guys has a date for the release?

**Comment by Aden-git** [comment]
@jecelyniflix 
We already released the [16.2.6-rc.1](https://github.com/DevExpress/devextreme-angular/releases/tag/v16.2.6-rc.1) version with this enhancement. You can check it now.

**Comment by guehmann** [comment]
thanks, it's working now!
