### ISSUE TITLE
DxScheduler: moths view is awfully slow when loading lots of events

### ISSUE THREAD

**Issue by yurzui** [DevExpress/devextreme-angular#388]
We have implemented DxScheduler in our application. Our clients can create more 1000 events per months. The ajax call takes about 400 milliseconds while the browser is taking about 5 to 10 seconds to render all the events during which the UI is blocked and the page appears unresponsive. 

Here is live example to reproduce it https://plnkr.co/edit/a2ISU3lwyZxSKjB9DYBC?p=preview

We noticed that every item is inserted in the DOM, then it is removed after calculation its position and finally only two apointments with "show more" remain in the DOM. 
![1](https://cloud.githubusercontent.com/assets/11659769/23451945/a49717ae-fe7b-11e6-92e1-c55370f42435.gif)

Please help us! What are some reasonable ways of remedying the situation? Maybe 
 we can limit rendering items per day somehow?

**Comment by Aden-git** [comment]
Hello @yurzui 

It looks like this issue is not related to the Angular 2 integration. I have created a [corresponding ticket](https://www.devexpress.com/Support/Center/Question/Details/T490937) in our Support Center.
