### ISSUE TITLE
Dragging of Controls does not work for me

### ISSUE THREAD

**Issue by markblandford** [DevExpress/devextreme-angular#389]
package.json:
"devextreme": "^16.2.4",
"devextreme-angular": "^16.2.4"

I'm very new to this and I've hit a bit of a brick wall. For some reason, in my project I'm unable to drag / move any controls, for example fields within the Field Chooser (in dx-pivot-grid) or a dx-popup. Here is my Pivot Grid:

`
<dx-pivot-grid id="pivGrid"
               [height]="830"
               [allowSortingBySummary]="true"
               [allowSorting]="true"
               [allowFiltering]="true"
               [showBorders]="true"
               [rowHeaderLayout]="'tree'"
               [dataSource]="dataSource"
               (onCellClick)="cellClicked($event)">
    <dxo-export [enabled]="true" fileName="sectorPivotExport"></dxo-export>
    <dxo-field-chooser [enabled]="true"></dxo-field-chooser>
    <dxo-scrolling mode="virtual"></dxo-scrolling>
</dx-pivot-grid>
`

This works in plunker (http://plnkr.co/edit/8JaUD7TFFPR9IbVGPECg?p=preview) but for some reason not in my much more complex project (where the pivot is a child component). I'm at a complete loss so any help or guidance would be greatly appreciated.

**Comment by markblandford** [comment]
So dragging will work in my project but only once I reload the page containing the control. If I then navigate to another page and come back, dragging stops working again. Any ideas as to what is going on?

**Comment by ovchinnikov** [comment]
Hi.
It is difficult to determine the cause of the issue without reviewing your whole application. Would you please provide a runnable project that replicates your scenario so that we can perform detailed research?

**Comment by markblandford** [comment]
Unfortunately I wasn't able to replicate it in Plunker or anything like that so I will close this issue.
