### ISSUE TITLE
DxDataGrid does not update a lookup column if the lookup data source is changed at run-time

### ISSUE THREAD

**Issue by GoshaFighten** [DevExpress/devextreme-angular#391]
devextreme-angular - 16.2.

[Plunker](http://plnkr.co/edit/iMitpZlxVPbp42z0Uz2E?p=preview)

![Screenshot](https://cloud.githubusercontent.com/assets/10522139/23516445/43f4206e-ff7e-11e6-8f38-8ecceca3c877.png)

**Comment by GoshaFighten** [comment]
At the moment, replace the whole lookup object.

``` HTML
<dxi-column dataField="ID" caption="State" [width]="400" [lookup]="stateLookup">
</dxi-column>
```

``` TypeScript
setStates(): void {
  this.loadService
    .getStates().then(
      data => {
        this.stateLookup = {
          dataSource: {
            store: {
              type: 'array',
              data: data
            },
          paginate: true,
          pageSize: 50
        },
        displayExpr: "Name",
        valueExpr: "ID"
      };
      }
    );
 }
```

[Plunker](http://plnkr.co/edit/BrRoK5juLCHZcUZdrAEE?p=preview)

**Comment by ovchinnikov** [comment]
This issue was fixed in DevExtreme 16.2.7

**Comment by foaudkajj** [comment]
I have the same issue. I spent hours but couldn't solve it.

**Comment by mena149f** [comment]
This issue still exist

**Comment by dathoang** [comment]
Still have this issue in 20.1.8
