### ISSUE TITLE
tab panel visible

### ISSUE THREAD

**Issue by eyimcen-tchealth** [DevExpress/devextreme-angular#392]
<dx-tab-panel [selectedIndex]="0" [animationEnabled]="true" [swipeEnabled]="true">
        <dxi-item class="tabpanel-item" title="Mesajlaşma">
            <div class="row">
                <div class="list-container col-sm-1">
                    <div class="btn" (click)="btnMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-inbox" style="color:#00ACF1; ">Gelen Kutusu</i></div>
                    <div class="btn" (click)="btnSendMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-paper-plane" style="color:#00ACF1; ">Giden Kutusu</i></div>
                    <div class="btn" (click)="btnDraftMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-envelope" style="color:#00ACF1;">Taslaklar</i></div>
 
                </div>
                <div class="list-container col-sm-3">
                    <div class="dx-searchbar">
                        <dx-text-box valueChangeEvent="keyup" placeholder="Ara" mode="search" (onValueChanged)="txtChange($event)">
                        </dx-text-box>
                    </div>
                    <dx-list [dataSource]="inbox" height="900" (onItemClick)="selectedChange($event)">
                        <div *dxTemplate="let data of 'item'">
                            <div class="col-sm-12">
                                <div class="col-sm-12">
                                    <b style="float:left">{{data.Gonderenadi}}</b>
                                </div>
                                <div class="col-sm-4">
                                    <p>{{data.Baslik}}</p>
                                </div>
                                <div class="col-sm-6">
                                    <p style="float: right;margin-right: -90px;">{{data.Tarih}}</p>
                                </div>
                            </div>
                        </div>
                    </dx-list>
                </div>
                <div class="list-container col-sm-8">
                    <div class="btn" (click)="btnNewMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-newspaper-o" style="color:#00ACF1;">Yeni Mesaj</i></div>
                    <br />
                    <br />
                    <div id="systemapi-container" class="col-sm-12" style="height:100%">
                        <comp-compose [Info]="systemApiService?.componentInfo"></comp-compose>
                    </div>
                </div>
            </div>
        </dxi-item>
        <dxi-item #smsemail class="tabpanel-item" title="SMS-Email">
            <div class="row">
                <div class="col-sm-1">
                    <label>SMS</label>
                    <dx-check-box [(value)]="SMS"></dx-check-box>
                </div>
                <div class="col-sm-1">
                    <label>E-Mail</label>
                    <dx-check-box (onValueChanged)="mailchanged($event)" [(value)]="Email"></dx-check-box>
                </div>
            </div>
            <dx-tag-box [items]="usertdt" searchEnabled="true" displayExpr="Name" valueExpr="ObjectID" showSelectionControls="true" multiline="true" placeholder="Personel Seçiniz" [(value)]="SelectedUser">
            </dx-tag-box>
            <dx-text-box [visible]="subjectvisible" placeholder="Başlık Giriniz." [(value)]="subject"></dx-text-box>
            <dx-text-area placeholder="Mesaj Giriniz..." [(value)]="message"></dx-text-area>
            <dx-button (onClick)="send()" text="Gönder"></dx-button>
        </dxi-item>
    </dx-tab-panel>

How can i change visible for dx-item

for example if i want to sms-email's tab visible false ?

Best regard...

**Comment by GoshaFighten** [comment]
You can hide a tab at runtime using the [ngIf](https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html) directive. See the [Plunker](http://plnkr.co/edit/3nxk0Yha2p3fzKxIN1WA?p=preview) that illustrates this.

**Comment by 16adianay** [comment]
We included the feature you inquired about in our plans for the upcoming major release - v24.2. You can find more details in the [DevExtreme Roadmap](https://js.devexpress.com/jQuery/Roadmap/#tabpanel-multiview%E2%80%94item-visibility-option).

Your feedback is valuable to us as we strive to incorporate user requests throughout the development process. If you have any insights or suggestions to share, please take a moment to complete our [survey](https://www.devexpress.com/support/surveys/devextreme-roadmap-item-visibility.xml).

Stay tuned for updates regarding development progress. We have an Early Access Program (EAP) release scheduled for September, during which a portion of the features planned for the major release will be available for early testing. We will publish a blog post about the EAP release.

The RTM version of the major release 24.2 is planned for December.

Thank you.

**Comment by 16adianay** [comment]
Hello,

I'm happy to inform you that we introduced a new `item|visible` option in v24.2: [TabPanel/MultiView - Item Visibility Option](https://www.devexpress.com/subscriptions/whats-new/#js-visible).

Also, please refer to our other [JavaScript-related features](https://www.devexpress.com/subscriptions/whats-new/#devextreme) and, if time permits, leave your feedback in the [survey](https://www.devexpress.com/subscriptions/whats-new/#devextreme-survey).

Thank you. Your feedback matters to us.
