### ISSUE TITLE
Tab Visible

### ISSUE THREAD

**Issue by eyimcen-tchealth** [DevExpress/devextreme-angular#393]
<dx-tab-panel [selectedIndex]="0" [animationEnabled]="true" [swipeEnabled]="true">
        <dxi-item class="tabpanel-item" title="Mesajlaşma">
            <div class="row">
                <div class="list-container col-sm-1">
                    <div class="btn" (click)="btnMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-inbox" style="color:#00ACF1; ">Gelen Kutusu</i></div>
                    <div class="btn" (click)="btnSendMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-paper-plane" style="color:#00ACF1; ">Giden Kutusu</i></div>
                    <div class="btn" (click)="btnDraftMessage_Click()" style="border:0px; box-shadow:none; text-align:center;"><i class="fa fa-envelope" style="color:#00ACF1;">Taslaklar</i></div>
 
                </div>
            </div>
        </dxi-item>
        <dxi-item class="tabpanel-item" title="SMS-Email">
            <div class="row">
                <div class="col-sm-1">
                    <label>SMS</label>
                    <dx-check-box [(value)]="SMS"></dx-check-box>
                </div>
            </div>
        </dxi-item>
    </dx-tab-panel>

How can i change visible tabs (Mesajlaşma and SMS-Email)?

**Comment by GoshaFighten** [comment]
Duplicate for #392
