### ISSUE TITLE
Angular2 - How to change the size of DevExtreme load indicator in datagrid control

### ISSUE THREAD

**Issue by lohiarahul** [DevExpress/devextreme-angular#395]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: "16.2.5",
    devextreme-angular version: "16.2.5",
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[x
[dx-data-grid.txt](https://github.com/DevExpress/devextreme-angular/files/830609/dx-data-grid.txt)
 ] feature request 
[ ] support inquiry

**Comment by ovchinnikov** [comment]
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
