### ISSUE TITLE
When DxDataGrid is in cell mode,  addRow function does not work fully correct

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#396]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using. 
    devexteme version: latest
    devextreme-angular version: latest
- Specify the type of the issue (check one with "x"): 
    bug Report

Here it is an example of the bug:
http://plnkr.co/edit/4NdPjSU2RLrPLMWdO9HD?p=preview
When you click DevExtreme "+" button, a row is added and first editable cell is focused.
But when you execute addRow() function from the code (by clicking custom button), it adds a new row, but focus is not set.

**Comment by ovchinnikov** [comment]
Try to call the **addRow** method with a delay to automatically apply focus to the first column: 
```js
onClick() {
    setTimeout(this.dataGrid.instance.addRow);
}
```
