### ISSUE TITLE
Dx Date Box

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#397]
![untitled](https://cloud.githubusercontent.com/assets/22006033/23850360/ba2bf736-07e7-11e7-8e31-e14ccd87475e.png)

<dx-date-box width="100%" type="date" displayFormat="dd/MM/yyyy" [(value)]="StartDate"></dx-date-box>

When i manuel write 23/03/2017 its will be error Value must be date or time

How can i repair it ?

**Comment by ovchinnikov** [comment]
Hello,
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
