### ISSUE TITLE
Date Box

### ISSUE THREAD

**Issue by Consi007** [DevExpress/devextreme-angular#398]
![untitled](https://cloud.githubusercontent.com/assets/22006033/23854139/aeaa1aa8-07f8-11e7-8a95-d5b244a54261.png)

How can i set displayFormat ? version 16.2.5

**Comment by ovchinnikov** [comment]
Hello,
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
