### ISSUE TITLE
dx-validator controlled by *ngIf doesn't work

### ISSUE THREAD

**Issue by Adelor** [DevExpress/devextreme-angular#409]
I validate a textbox based on some condition.
````
<dx-text-box>
  <dx-validator *ngIf="checked">
      <dxi-validation-rule type="required"></dxi-validation-rule>
  </dx-validator>
</dx-text-box>
````

Validation doesn't work if I use it as in the above sample. See [plunkr](http://plnkr.co/edit/XgYmK7K6b6luZTVSSIav?p=preview).

Steps:
1) Click on the checkbox
2) Click on the button
The textbox is not validated.

**Comment by dxvladislavvolkov** [comment]
Hello @Adelor 
This scenario will work if you add *ngiF for a validation rule. You can see an example [here](http://plnkr.co/edit/ykJtJTy53Sia3AMMCWPP?p=preview).

**Comment by Boombasteg** [comment]
Hello @dxvladislavvolkov
Your solution doesn't works for me.

@Adelor, I can solve same problem this way:
...
<dx-text-box id="{{definition.Code}}" maxLength=50 value="{{definition.Required}}">
                                        <template [ngIf]="definition.Required">
                                            <dx-validator>
                                                <dxi-validation-rule type="required" message="{{definition.Name}} is required."></dxi-validation-rule>
                                            </dx-validator>
                                        </template>
                                    </dx-text-box>
...

**Comment by dxvladislavvolkov** [comment]
Hello @Boombasteg  
Your example does not work on our side.

Could you provide an example using a [planker](http://plnkr.co/edit/XuAPDd?p=preview) or another service?
Please also provide an example where our solution does not work.
