### ISSUE TITLE
How can I make editable only one cell of a column that isn't editable?

### ISSUE THREAD

**Issue by gvise17** [DevExpress/devextreme-angular#410]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 
    devextreme-angular version: v2016 vol 2.5
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x] support inquiry 

-------------------------------------------------------------------------------------------------------------------

In a web project with Angular 2 I have a datagrid with a column that isn't editable in 'update mode' but when I add a new row I want that this cell becomes editable.

I have tryed to set allowEditing=true on my column in the events:
- initNewRow
- cellPrepared

without success. The property allowEditing result correctly setted to true, becomes selectable (blue line appear around the cell), but the cell ist't editable as a readOnly cell.

How can I do?

Thank you.
Best regards,
Danilo Visentin

**Comment by dxAnthony** [comment]
Hello,

Handle the [editorPreparing](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxDataGrid/Events/#editorPreparing) event to resolve this issue.

````
  onEditorPreparing(e: any): void {
     if(e.parentType == "dataRow" && e.dataField == "orderID")
          e.editorOptions.readOnly = !e.row.inserted;
  }
````

See the [online example](http://plnkr.co/edit/QDyrAGKiZsHWAda0lBFe?p=preview).
