### ISSUE TITLE
How to fire focus on first editable cell?

### ISSUE THREAD

**Issue by gvise17** [DevExpress/devextreme-angular#412]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 
    devextreme-angular version: v2016 vol 2.5
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x] support inquiry 

------------------------------------------------------------------------------------------------------------------

In this example:

http://plnkr.co/edit/bObonozBkexlMoXkrccA?p=preview

when I push on the 'Edit' button of a row the focus is fired on the first cell, but that cell isn't editable and the content is emptied.
How can fire focus on first editable cell and avoid that first cell is emptied?

**Comment by dxAnthony** [comment]
Hello,

It is possible to focus an editor as described in [T273089](https://www.devexpress.com/Support/Center/Question/Details/T273089)
I've modified your sample accordingly: [link](http://plnkr.co/edit/ItjRcPfY33wnSp0GUM8G?p=preview)
