### ISSUE TITLE
No expandItem() method in DxAccordionComponent

### ISSUE THREAD

**Issue by cafeburger** [DevExpress/devextreme-angular#418]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2.5
    devextreme-angular version: 16.2.5
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[x] feature request 
[ ] support inquiry 

https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxAccordion/Methods/

The `expendItem()` method exist in the document as above but not in `DxAccordionComponent`

**Comment by dxAnthony** [comment]
Hello,

I believe you are referring to the [expandItem](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxAccordion/Methods/#expandItemindex) method. It exists in the DxAccordionComponent and works correctly as you can see in the [plunker](http://plnkr.co/edit/GNDmS9LstsBtYalRXlUw?p=preview) example.
