### ISSUE TITLE
The way to use "deleteRow" in a dx-data-grid

### ISSUE THREAD

**Issue by mpulido73** [DevExpress/devextreme-angular#420]
Hi! How can we use in angular2, "deleteRow" in a dx-data-grid?? There are no doc about that.
<dx-data-grid 
   ...
   <dxo-editing 
            mode="row"
            [allowUpdating]="true"
            [allowDeleting]="true"
            [allowAdding]="true">
            <dxo-texts ?????
                [deleteRow]="Custom delete row msg"> ????
            </dxo-texts>  ????
        </dxo-editing>

Thanks a lot!

**Comment by dxvladislavvolkov** [comment]
Hello @mpulido73 !
You can see an example [here](http://plnkr.co/edit/I4BhBpyZ9KrkPMWyyqXU?p=preview).
