### ISSUE TITLE
How to use confirm dialog with webpack?

### ISSUE THREAD

**Issue by JavascriptParrot** [DevExpress/devextreme-angular#423]
I try to use the confirm dialog but it throws an error

`DevExpress is not defined`

How can I use the Devextreme dialog? I try the example of issue [125](https://github.com/DevExpress/devextreme-angular/issues/125) but it don't work.

Thanks

**Comment by eloekset** [comment]
I agree, it doesn't work with devextreme-angular. The Plunker sample uses devextreme-angular2 16.1.7-alpha, but that is probably deprecated, or? At least all documentation in this repo references devextreme-angular, not ..gular2.

**Comment by ovchinnikov** [comment]
Please refer to the [How to show a ui confirm dialog in an Angular 2 app](https://www.devexpress.com/Support/Center/Question/Details/T494067) ticket where we discussed a similar issue.

If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question).
