### ISSUE TITLE
dx-date-box implementation in Angular

### ISSUE THREAD

**Issue by AliAmir1992** [DevExpress/devextreme-angular#424]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    typeScripe version: 4.4.x
    devexteme version: 16.2.x
    devextreme-angular version: 2
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ x ] support inquiry 

I'm unable to use displayFormat option of dx-date-box in Angular2. Please find my sample implementation below:
`<dx-date-box maxZoomLevel="year" [displayFormat]="{ month: 'short', year: 'numeric'}"><dx-validator><dxi-validation-rule type="required" message="Select Date Of Birth"></dxi-validation-rule></dx-validator></dx-date-box> `

In the above example **[displayFormat]** option is not working while using with Angular 2. We even tried localization and using the **skeleton** syntax.

Please let me know what's wrong with this implementation. Or if I can implement that option in some other way.

Thanks.

**Comment by ovchinnikov** [comment]
Hi,
Would you please modify [this](http://plnkr.co/edit/a03qedG793jciY2yauhZ?p=preview) example to show the issue?
