### ISSUE TITLE
dx-validation-group options in Angular2

### ISSUE THREAD

**Issue by AliAmir1992** [DevExpress/devextreme-angular#425]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    typescript version: 4.4.x
    devexteme version: 16.2.x
    devextreme-angular version: 2
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ x ] support inquiry 

I am using multiple **dx-validation-group** control on  single page. How can I specify the name property of each validation-group to identify it in my typescript / html. Please find below some option that I have tried:

```
option 1 : <dx-validation-group name="validGrp1">
option 2 : <dx-validation-group validationGroup="validGrp1">
```

Please let me know how can I implement this using name / validationGroup properties. Or if I can use some other property name which is valid.

**Comment by danonechik94** [comment]
You can implement this scenario using the Angular 2 element query feature. See the [ViewChild](https://angular.io/docs/ts/latest/api/core/index/ViewChild-decorator.html) documentation article to learn how to get the first element that matches a query.
 
Specify the dxValidationGroup component's unique identifier using the following syntax:
 
`<dx-validation-group #val1>`
 
and get this element in the component using the following code:
 
`@ViewChild('val1') validationGroup1: DxValidationGroupComponent;`
 
To access the component's widget instance, use the following code:
 
`this.validationGroup1.instance`
 
I demonstrated this approach in the [Plunker example](http://plnkr.co/edit/U8NQcvlKnQMA0yWNSFth?p=preview).
