### ISSUE TITLE
dx-file-uploader options in Angular2

### ISSUE THREAD

**Issue by AliAmir1992** [DevExpress/devextreme-angular#426]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    typescript version: 4.4.x
    devexteme version: 16.2
    devextreme-angular version: 2
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ x ] support inquiry 

Hi,
I am using dx-file-uploader and I'm unable to find the option to call callback function after the file is uploaded. i tried using this:

```
<dx-file-uploader
                            #fileUploader
                            uploadUrl="https://js.devexpress.com/Content/Services/upload.aspx"
                            [multiple]="false"
                            accept="images/*"
                            uploadMode="instantly"
                            (Uploaded)="fn"
                            (UploadError)="errFn"
                        ></dx-file-uploader>
```

Please let me know what options can I provide over here.

Thanks.

**Comment by ovchinnikov** [comment]
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
