### ISSUE TITLE
Using angular #var in Form interactive configuration

### ISSUE THREAD

**Issue by prabhdaffo** [DevExpress/devextreme-angular#427]
Hi,

How can we add a field for angular template variable in dxfrom interative configuration?

Here is a Form interactive configuration -[https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxForm/](https://js.devexpress.com/Documentation/16_2/ApiReference/UI_Widgets/dxForm/)

Plunker - Using #var  with devexterme-
[http://plnkr.co/edit/W4hCwTGbGIOX0ZKX3IB7?p=preview](http://plnkr.co/edit/W4hCwTGbGIOX0ZKX3IB7?p=preview)

**Comment by dxvladislavvolkov** [comment]
Hello @prabhdaffo 
You can do this as shown in this [example](http://plnkr.co/edit/UP2bocmowutTFaHNzheT?p=preview).
