### ISSUE TITLE
dxDataGrid  - Changing a data source at runtime overwrites the data source object that was initially passed to the grid componen

### ISSUE THREAD

**Issue by danonechik94** [DevExpress/devextreme-angular#429]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2.6
    devextreme-angular version: 16.2.6
- Specify the type of the issue (check one with "x"): 
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

See the [Plunker example](http://plnkr.co/edit/KQHfKc0W4NQQ5UF17E85?p=preview) where I illustrate the issue. The dataSources object contains multiple data sources which can be accessed by the key ('Categories' or 'Products' in my case). The data source object is passed to a separate property and then this property is bound to the dataSource option of the dxDataGrid component. 
 
currentDataSource: string = 'Categories';
gridDataSource: any = this.dataSources[this.currentDataSource];
...
`<dx-data-grid`
` [dataSource]="gridDataSource"`
 
 
The data source is changed on a button click;
 
`let newDataSource: string = this.currentDataSource == 'Categories' ? 'Products': 'Categories';`
`this.gridDataSource = this.dataSources[newDataSource];`
 
At this stage, the `this.dataSources` object is not changed. But if you debug the application and check the `this.dataSources` object in the `onOptionChanged` event of the dxDataGrid component, you'll see that the `this.dataSources['Categories']` object is the same as `this.dataSources['Products']`. I demonstrated this behavior in the attached screencast.
[dxDataGrid_issue.zip](https://github.com/DevExpress/devextreme-angular/files/905576/dxDataGrid_issue.zip)
 
Setting the `gridDataSource` object in the following manner resolves the issue:
`gridDataSource: any = Object.assign({}, this.dataSources[this.currentDataSource]);`
 
The issue is not reproducible if you remove the dxDataGrid component from the plunker demo I linked below.

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular integration. I have created a corresponding [ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T521407) in our Support Center.

**Comment by gtteamamxx** [comment]
this.dataGrid.instance.refresh();
