### ISSUE TITLE
How to create custom directive for DxComponent

### ISSUE THREAD

**Issue by artstalker** [DevExpress/devextreme-angular#430]
I want to create a custom directive that will set focus to the element. The problem is here that Angular2 directive ctor accept ElementRef and does not have access to DxComponent object where I can call dxComponent.instance.focus();

Please, look at this example (find AutofocusDirective):
http://plnkr.co/edit/Jp6CFS1coeLycROudbWG?p=preview

**Comment by danonechik94** [comment]
Hi,

At the time the ngInit event is fired, the dxTextBox component is not yet initialized. Use the [AfterViewChecked](https://angular.io/docs/js/latest/api/core/index/AfterViewChecked-class.html) lifecycle hook instead. At this stage, our components are already initialized and you can get the widget instance using the jQuery 'instance' approach:

      var tb = $(this.elementRef.nativeElement).dxTextBox('instance');
      tb.focus();

I updated your [Plunker Demo](http://plnkr.co/edit/QZNknjDxEhhp6q0uZRqm?p=preview) to illustrate this approach.

**Comment by artstalker** [comment]
Hi, thanks for your answer! 
I don't like this solution because
1. I don't want to use jQuery for such simple tasks within Angular2 directives and components
2. AfterViewChecked lifehook is triggered  a lot of times when interacting with UI. Even so, it's possible to use backend flag field to execute focus() function only one time, it's kind of dirty.

But I don't have any other solution. I might use it for now. I will let you know if I find better one.

**Comment by artstalker** [comment]
Btw, that solution doesn't work for me.
It throws an exception
TypeError: $(...).dxTextBox is not a function

I think it could be because I'm using webpack 2.0 and I import devextreme-angular only, not devextreme itself (according to the official guide).

**Comment by danonechik94** [comment]
Hi, thank you for the clarification. 
 
You can implement this scenario without jQuery. Use the @Host decorator in the AutofocusDirective constructor to obtain an instance of the hosting component.
 
As a DevExtreme component is initialized in the AfterViewInit event, a widget instance is not available when a custom directive's constructor is executed. Thus, I suggest you access the widget instance in the AfterViewInit event handler:
 
	export class AutofocusDirective implements AfterViewInit {
	 constructor(@Host() tb: DxTextBoxComponent) { 
	  this.tb = tb;
	 };
	 ngAfterViewInit() {
	  this.tb.instance.focus();
	 }
	}
 
See the [Plunker example](http://plnkr.co/edit/px4vsio0cg4PdnE9TxGT?p=preview) where I illustrated this approach.

**Comment by artstalker** [comment]
Thanks a lot!
This solution worked for me like a charm.
