### ISSUE TITLE
dx-data-grid - How to sort the column chooser column list

### ISSUE THREAD

**Issue by jandresampaio** [DevExpress/devextreme-angular#434]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version:  16.2.6
    devextreme-angular version: 16.2.6 
- Specify the type of the issue (check one with "x"): 
[x] support inquiry 

I'm using columnChooser but cannot find a way to sort alphabetically the columns inside. 
        <dxo-column-chooser mode="select" [enabled]="true"></dxo-column-chooser>

Is this possible using Angular 2+ ?

Thank you
José Sampaio

**Comment by danonechik94** [comment]
Hi,
 
The dxDataGrid component does not provide an API for sorting the column chooser column list. However, you can redefine the column chooser function that obtains a list of columns and sort this list in your custom function. 

```js
import DataGrid from 'devextreme/ui/data_grid';
DataGrid.registerModule("columnChooserSorting", {
  extenders: {
      controllers: {
          columns: {
              getChooserColumns: function(loadAllColumns) {
                  var result = this.callBase(loadAllColumns);
                  return result.sort(function(column1, column2) {
                        return column1.caption.localeCompare(column2.caption);
                  });
              }
          }
      }
  } 
});
```

See the [Plunker demo](http://plnkr.co/edit/0TevhwxtGNCxwOXzBBsK?p=preview) where I demonstrated this approach in action.

**Comment by jandresampaio** [comment]
Thanks for the update. 

However, I receive the error: 
error TS2339: Property 'registerModule' does not exist on type 'typeof dxDataGrid'.

![image](https://cloud.githubusercontent.com/assets/13848625/25044347/1c71b03a-211e-11e7-8c05-5ce167fb0891.png)

Can you help ?

**Comment by danonechik94** [comment]
Thank you for the clarification. The typescript compiler configuration is not so strict in the Plunker service, thus this error is not displayed in the [Plunker demo](http://plnkr.co/edit/nrOYACf4gdG10CtKGpOr?p=preview). As this API is private, no type definitions are provided for the 'devextreme/ui/data_grid' module.

You can workaround this issue by tricking the compiler in the following manner:

```js
(DataGrid as any).registerModule("columnChooserSorting", {
  ...
});
```

Refer to the 
[434.zip](https://github.com/DevExpress/devextreme-angular/files/922310/434.zip) sample project where I demonstrated this approach.

**Comment by jandresampaio** [comment]
It worked. 

Thanks for the help!
