### ISSUE TITLE
Cant seem to trigger onValueChange, onCellPrepared, editCellTemplate 

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#444]
When in cell editing mode is there a way to fire a function once the value has changed

I've tried to fire onCellPrepared, editCellTemplate and onValueChanged but nothing seems to log

HTML

`        <dx-data-grid id="gridContainer" [dataSource]="cash" [columns]="customcols" [editing]="editing">
        </dx-data-grid>
`

  this.editing = {
      allowUpdating: true,
      mode: 'cell',
      allowAdding: false,
      allowDeleting: false,
      onValueChanged: function (cellElement, cellInfo) {
        console.log(cellElement, cellInfo)
      }

 customcols = [{
            dataField: item,
            dataType: 'number',
            onCellPrepared: function (cellElement) {
              console.log(cellElement)
            }
            // editCellTemplate: function (cellElement, cellInfo) {
            // console.log(cellElement, cellInfo);           
            //},
          }];

**Comment by gwsampso** [comment]
I solved my issue using  (onEditorPreparing) and (onCellPrepared)

plnkr below

https://plnkr.co/GwgBD1Mp8XF5oLZoYt4k?p

But now changes in my bottom grid flow though to my top even though they are using different datasets but from the same subscription

**Comment by GoshaFighten** [comment]
While you are binding the first grid to the "cash" variable and the second grid to "cash2", these variables reference the same array ("data" that comes from your service). So, when you modify an item of the "cash2" array, the "cash" array is modified as well. See the [Plunker](https://plnkr.co/edit/tBxcCIds8K71v9jZGQN5?p=preview) that illustrates this behavior with a standard `ngFor` directive.

To edit the arrays separately, you need to make a copy of the original array. You can do this, for example, like `this.cash2 = JSON.parse(JSON.stringify(data));`. See the updated [Plunker](https://plnkr.co/edit/enGTpoIkBba4hedD9mpz?p=preview).
