### ISSUE TITLE
examples do not run - missing node dependencies

### ISSUE THREAD

**Issue by davidekarasek** [DevExpress/devextreme-angular#450]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 
    devextreme-angular version: 
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by GoshaFighten** [comment]
@davidekarasek 
What examples do you mean? Also, please provide us with the NPM error log.

**Comment by davidekarasek** [comment]
I walked through the whole process from scratch, removing all prior instances of dev express tools from NPM and going strickly by your documentation. The problem isn't versions, since in this process I installed all the latest dev express npm components.  It was pre-assuming what web server we are going to use.

Subsequently I've had a good discussion with your CTO on this and we're squared away now.  Thanks.
