### ISSUE TITLE
DateBox - Internal validation is not bubbled up to an Angular form control 

### ISSUE THREAD

**Issue by bonejon** [DevExpress/devextreme-angular#458]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2
    devextreme-angular version: 16.2
- Specify the type of the issue (check one with "x"): 
[x] bug Report
[ ] feature requestspecify expected results. -->
[ ] support inquiry

Please consider the following example: http://plnkr.co/edit/aUgSLuJ4YVQFzV77eba1?p=preview

Notice the date-box has a minimum range set to 1st May 2017, you are unable to select a value from the date picker, however if you enter via the keyboard 1st April 2017 this is accepted by the input control. However the control validation kicks in and shows an error icon. If you review the output below neither the formGroup for formControl associated with the datebox are marked as invalid.

**Comment by artem-kurchenko** [comment]
Hi,
 
dxDateBox has the internal validation mechanism, which doesn't raise the default valueChanged event in the described case. I suggest you manually track changes of the isValid option using the onOptionChanged handler and create a custom validator that will take these changes into account. Please take a look at the following code example - 

[validation.zip](https://github.com/DevExpress/devextreme-angular/files/1038806/validation.zip)

Anyway, we understand that this solution doesn't look generic and consider improving our existing integration mechanisms in future versions.

**Comment by cmaart** [comment]
This is still an issue. A FormControl that has a red exclamation mark in the UI because of wrong input but still has `valid: true` is definitely not the expected behavior.
