### ISSUE TITLE
TextBox - Model is not updating at realtime if ngModel is used

### ISSUE THREAD

**Issue by tpongratz-lhi** [DevExpress/devextreme-angular#460]
devexteme version: 16.2.6
    devextreme-angular version: 16.2.4

[x] bug Report http://plnkr.co/edit/H5LZmM?p=preview

Hello,

As you can see in the above plnkr example. When using the ngModel on an input control, the data is bound real-time as the user types. On the DevExtreme Text Box, the model data is not updated until the control has lost focus.

Thoughts?

Thank you,
Tyler

**Comment by artem-kurchenko** [comment]
Hi,

Change the default [valueChangeEvent](https://js.devexpress.com/Documentation/17_1/ApiReference/UI_Widgets/dxTextBox/Configuration/#valueChangeEvent) option value to complete this task. 
Please review the modified example - http://plnkr.co/edit/vatHXTMn9YsJHKIjVghk?p=preview

**Comment by tpongratz-lhi** [comment]
Thank you! Follow-up question:

Is there a way to override the default valueChangeEvent option globally throughout the application? Possibly using something like the .config() options: 

https://js.devexpress.com/Documentation/16_1/ApiReference/Common/utils/#configconfig

**Comment by artem-kurchenko** [comment]
You're welcome! The config setting doesn't provide this capability. You can use the [defaultOptions](https://js.devexpress.com/Documentation/17_1/ApiReference/UI_Widgets/dxTextBox/Methods/#defaultOptionsrule) option for this purpose. Alternatively, wrap our editor(s) with pre-defined options in a custom component to make them reusable
