### ISSUE TITLE
Is there a place i can check status on Angular 4 support?

### ISSUE THREAD

**Issue by KevivL** [DevExpress/devextreme-angular#463]
I see the project has an angular 4 tag, but i can't find mention of whether this is angular 4 compatible, apart from a merged PR which suggests that it is?

**Comment by artem-kurchenko** [comment]
Hi,
 
We supported Angular 4 in the context of the mentioned PR. So, starting with version 16.2.6, our Angular integration package supports Angular 4, and you are welcome to use it.
