### ISSUE TITLE
dxForm colspan error

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-angular#464]
I'm trying layout content in 2 columns where the first column will be 3 times
If the item is not in the first column and the colspan is set, an error occurs:  `E1025 - This layout is too complex to render`

Template:
```html
<dx-form colCount="4" [formData]="request" #form>
    <dxi-item colSpan="4" dataField="FirmId" [label]="{visible:false}">
        <bda-client-selector [(clientId)]="request.FirmId" [(readOnly)]="readOnly"></bda-client-selector>
        <!--<dxi-validation-rule type="required" message="Выберите клиента"></dxi-validation-rule>-->
    </dxi-item>
    <dxi-item [label]="{text:'Срок исполнения'}" dataField="DateEndByCreator" editorType="dxDateBox" [disabled]="readOnly">
        <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-item>
    <dxi-item [label]="{visible:false}" dataField="Name" [editorOptions]="{placeholder:''}" colSpan="3" [disabled]="readOnly">
        <dxi-validation-rule type="required"></dxi-validation-rule>
    </dxi-item>
</dx-form>
```

**Comment by NikitaKunashov** [comment]
The error appears inside the dxForm widget and seems not to be specific to the angular integration package. So it's better to create a ticket in [DevExpress support center](https://www.devexpress.com/Support/Center/). Please attach a runnable project that shows markup of the **bda-client-selector** component and our support team will be happy to assist you.

**Comment by kentsitu** [comment]
@genusP I had the same issue before. Correction:
 colSpan="3" => [colSpan]="3"

**Comment by genusP** [comment]
@kentsitu Thanks
