### ISSUE TITLE
Installing dependencies with yarn creating issue

### ISSUE THREAD

**Issue by secabhi** [DevExpress/devextreme-angular#466]
Hi I have installed dependencies with yarn 
I have imported DevExtremeModule in my root module . when i running webpack getting below error .
I am using angular 4.0.3 , rxjs 5.0.2 ,zonejs.0.8.12

Also , I have checked in drop-down-box.d.ts file . I think devextreme/ui/drop_down_box file is missing while installing via yarn 
`                                                                                                                        ERROR in ./~/devextreme-angular/ui/drop-down-box.js                                                                     Module not found: Error: Can't resolve 'devextreme/ui/drop_down_box' in 'H:\boomerang\boomerang-ui\node_modules\devextreme-angular\ui'                                                                                                           @ ./~/devextreme-angular/ui/drop-down-box.js 20:22-60                                                                   @ ./~/devextreme-angular/index.js                                                                                       @ ./src/app/app.module.ts                                                                                               @ ./src/main.browser.ts                                                                                                 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts                                                                                                                                                                ERROR in ./~/devextreme-angular/ui/tree-list.js                                                                         Module not found: Error: Can't resolve 'devextreme/ui/tree_list' in 'H:\boomerang\boomerang-ui\node_modules\devextreme-angular\ui'                                                                                                               @ ./~/devextreme-angular/ui/tree-list.js 20:18-52                                                                       @ ./~/devextreme-angular/index.js                                                                                       @ ./src/app/app.module.ts                                                                                               @ ./src/main.browser.ts                                                                                                 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts                                                                                                                                                                ERROR in ./src/app/app.module.ts                                                                                        Module not found: Error: Can't resolve 'devextreme' in 'H:\boomerang\boomerang-ui\src\app'                               @ ./src/app/app.module.ts 19:0-20                                                                                       @ ./src/main.browser.ts                                                                                                 @ multi (webpack)-dev-server/client?http://localhost:3000 ./src/main.browser.ts `

**Comment by Aden-git** [comment]
Hello @secabhi
 
Please take a look at the #468 issue. It looks like it occurs due to the same reason. Feel free to contact us if it does not help you.
