### ISSUE TITLE
Devextreme 17.1.3, typings for typescript not provided 

### ISSUE THREAD

**Issue by tamohugues** [DevExpress/devextreme-angular#467]
devexteme version: 17.1.3
    devextreme-angular version: 17.1.3
     npm: 4.1.1
     node: 7.9.0

How to set typings for typescript, I want to use jquery for manipulating dom but typings not provided. When I use npm i --save-dev @types/devextreme, I cant see typings devextreme-angular

**Comment by NikitaKunashov** [comment]
Hello,
Since the TypeScript definitions are included in our main packages, it does not make sense to maintain separate packages which contain these definitions. 
So, starting with the 17.1 version, the Typings packages for our products are not updated.
