### ISSUE TITLE
Cannot find module 'devextreme/ui/drop_down_box'.  Cannot find module 'devextreme/ui/tree_list'.

### ISSUE THREAD

**Issue by sheetaldshivdas** [DevExpress/devextreme-angular#468]
Using Angular CLI 

```
@angular/cli: 1.0.0
node: 7.4.0
os: darwin x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.0
@angular/compiler-cli: 4.1.3
```

After installing npm install --save devextreme devextreme-angular

got below error:
├─┬ UNMET PEER DEPENDENCY devextreme@16.2.7
│ └─┬ jszip@3.1.3 
│   ├── core-js@2.3.0 
│   ├── es6-promise@3.0.2 
│   ├─┬ lie@3.1.1 
│   │ └── immediate@3.0.6 
│   ├── pako@1.0.5 
│   └─┬ readable-stream@2.0.6 
│     └── string_decoder@0.10.31 
└─┬ devextreme-angular@17.1.3 
  ├── @types/jquery@2.0.45 
  └── jquery@3.2.1 

npm WARN devextreme-angular@17.1.3 requires a peer of devextreme@~17.1.3 but none was installed.

Still after proceeding to use range slider got the below errors:
Cannot find module 'devextreme/ui/drop_down_box'.Cannot find module 'devextreme/ui/tree_list'.

HOW TO INSTALL THE MISSING ITEMS?

**Comment by iubarif** [comment]
I got this same error. any idea how to fix this ...

**Comment by Aden-git** [comment]
Hello
 
We found that there was a mistake with the `latest` tag in our npm package, so npm installed an old version. We already fixed it.
To resolve the current issue, please manually specify the version of the `devextreme` package during installation: `npm i devextreme@~17.1.3 devextreme-angular@~17.1.3 -S`

**Comment by 3669** [comment]
yeeeee. is work now. thank you!!!!!! all day i try to use it's and only you helped me/))
