### ISSUE TITLE
How can to create a custom component using DevExpress.registerComponent

### ISSUE THREAD

**Issue by mickjol** [DevExpress/devextreme-angular#474]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2.6
    devextreme-angular version: 16.2.6
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x] support inquiry 

In javascript I use the "DevExpress.registerComponent" to create my own component.
How can I create the same component with devextreme-angular ?

`
DevExpress.registerComponent('dxMultiLang', (function (_super) {
        cause.extends(customControl, _super);

        var totalColumn = 0;
        var config = {};
        var container = $('<div>');
        var selectedLanguage = null;

        var _tabChanged = function (e) {
            selectedLanguage = e.addedItems[0].language;

            if (config.value) {
                if (typeof(config.value) != 'object') {
                    var tmpValue = config.value;
                    config.value = { id_language_content: null };

                    for (var i=0, j=cause.languages.available.length; i<j; i++) {
                        config.value[cause.languages.available[i]] = tmpValue;
                    }
                }
            } else {
                config.value = { id_language_content: null };

                for (var i=0, j=cause.languages.available.length; i<j; i++) {
                    config.value[cause.languages.available[i]] = '';
                }
            }

            container.find('input').val(config.value[selectedLanguage]);
        };

        var _createField = function () {
            $('<div class="dx-multilang-container">').html('<input type="text" />').focusin(function (e) {
                $(e.target).parents('.dx-multilang').addClass('focus');
            }).focusout(function (e) {
                $(e.target).parents('.dx-multilang').removeClass('focus');
            }).change(function (e) {
                config.value[selectedLanguage] = e.target.value;

                if (typeof(config.onValueChanged) == 'function') {
                    config.onValueChanged({
                        value: config.value,
                        jQueryEvent: e
                    });
                }
            }).appendTo(container);
        };

        var _createList = function () {
            config.value = (config.value ? config.value : {});
            selectedLanguage = cause.languages.available[0];

            var tabs = [];
            for (var i=0, j=cause.languages.available.length; i<j; i++) {
                tabs.push({
                    language: cause.languages.available[i],
                    text: cause.localize(cause.languages.available[i])
                });
            }

            $('<div>').dxNavBar({
                items: tabs,
                onSelectionChanged: _tabChanged
            }).appendTo(container);
        };

        function customControl(element, options) {
            _super.call(this, element, {});
            config = cause.extend({
                value: null,
                onValueChanged: null
            }, options);

            container.addClass('dx-multilang').addClass('dx-texteditor').html('').appendTo($(element));

            _createList();
            _createField();
        }

        return customControl;
    })(DevExpress.DOMComponent));
`

**Comment by artem-kurchenko** [comment]
Hi,

The Angular framework is based on the component model while the DevExpress.registerComponent is related to our internal API that doesn't match this concept. You can create a custom component using the Angular mechanism and use our widgets inside to make certain features reusable. Please refer to the [MULTIPLE COMPONENTS](https://angular.io/docs/ts/latest/tutorial/toh-pt3.html) help topic to learn how to create custom components in an Angular app. If this approach doesn't meet your requirement, please clarify what functionality you're trying to achieve.

**Comment by mickjol** [comment]
OK, I had no problem to create a angular component.

But how can I use it to edit a cell in datagrid ?
If my widget was register on devextreme, i could use to following code.

`columns: [{
      dataField: 'name',
      caption: 'name',
      editCellTemplate: function(cellElement, cellInfo) {
        $('<div>').dxMultiLang({
          value: cellInfo.data.name,
          onValueChanged: function (e) {
            cellInfo.setValue(e.value);
          }
        }).appendTo(cellElement);
      }
    }]`

Maybe I could insert dynamically my angular component. But I don't know how.
`function(cellElement, cellInfo) {
    cellElement.insert('<div class="myComponenent"></div>')
}`

**Comment by artem-kurchenko** [comment]
Define editCellTemplate in the Angular manner to complete this task - [Custom Templates](https://github.com/DevExpress/devextreme-angular#custom-templates)
This way, you'll be able to place an Angular component inside a template as well.

**Comment by kodermax** [comment]
How can i create custom element(hyperlink) on onCellPrepared(e)?
