### ISSUE TITLE
How do I receive the onSelectionChanged event in a dx-list?

### ISSUE THREAD

**Issue by homerokzam** [DevExpress/devextreme-angular#475]
I want to receive the onSelectionChanged event from a certain dx-list, but the event does not fire.

  <dx-list id="listPeriodos" [dataSource]="_periodos" [height]="200" selectionMode="multiple" [showSelectionControls]="true" 
    keyExpr="Oid" [(selectedItems)]="_selectedItems" (onSelectionChanged)="onSelectionChanged($event)" >
    <dxi-item *ngFor="let item of _periodos">
      {{item.Periodo}}
    </dxi-item>
  </dx-list>

....

onSelectionChanged(e) {
    console.log("onSelectionChanged", e);
  }

Thanks.

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: "^17.1.3",
    devextreme-angular version: "^17.1.3"
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x] support inquiry

**Comment by GoshaFighten** [comment]
You are using both the `dataSource` and `items` options to provide dxList with items. Use only one, for example, `dataSource`. To display the required property of a dxList item, implement dxList's `itemTemplate`:

``` HTML
<div *dxTemplate="let item of 'item'">
   {{item.Periodo}}
</div>
```

See the [Plunker](http://plnkr.co/edit/lHHnXPXmKprpswNRIYyA?p=preview) that illustrates this.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
