### ISSUE TITLE
node_modules/devextreme/bundles/dx.all.d.ts (2206,22): Interface 'dxLoadPanelOptions' incorrectly extends interface 'dxOverlayOptions'

### ISSUE THREAD

**Issue by tcrack326** [DevExpress/devextreme-angular#479]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.3
    devextreme-angular version: 17.1.3 
- Specify the type of the issue (check one with "x"): 
[x ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by tcrack326** [comment]
Full text of error:
node_modules/devextreme/bundles/dx.all.d.ts (2206,22): Interface 'dxLoadPanelOptions' incorrectly extends interface 'dxOverlayOptions'.
  Types of property 'animation' are incompatible.
    Type 'AnimationOptions' has no properties in common with type '{ show?: AnimationOptions; hide?: AnimationOptions; }'.
webpack: Failed to compile.

**Comment by GoshaFighten** [comment]
@tcrack326 
What TypeScript version are you using?

**Comment by tcrack326** [comment]
@GoshaFighten I am using 2.4.0. It works with 2.3.4.

**Comment by GoshaFighten** [comment]
This is an issue with our DevExtreme TypeScript definition. So, I've created a corresponding [bug report](https://www.devexpress.com/Support/Center/Question/Details/T525720) in our Support Center. We will address the issue in that ticket. Add it to your Favorites to be automatically notified of our progress.
