### ISSUE TITLE
Internationalizing the application

### ISSUE THREAD

**Issue by homerokzam** [DevExpress/devextreme-angular#482]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: "^17.1.3"
    devextreme-angular version: "^17.1.3"
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[X ] feature request 
[] support inquiry 

How do I submit data (date and currency) in pt-BR format?

Thanks.

**Comment by GoshaFighten** [comment]
You can use the widget `text` option to get the localized text a widget displays and post it to your service. If it's in Brazilian format, you will get it in this format. But, it sounds strange that your service accepts data in any localized format. If this approach does not work for you, open a [Support Center issue](https://www.devexpress.com/Support/Center/Question/Create).
