### ISSUE TITLE
Build error with latest @types/jquery version - 3.2.0

### ISSUE THREAD

**Issue by mustafasadikot** [DevExpress/devextreme-angular#483]
Hi Team,

The latest builds with webpack are failing since last 12 hours for 17.1.3 version.

I looked into the issue and found that the latest version for @types/jquery (version - 3.2.0) is causing the issue. I found [this ](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17239)thread for the same.

Then I looked into the package.json for devextreme and I believe below is the issue:

```
"devDependencies": {
    "@types/jquery": "^2.0.34",
    .....
}
```

**Comment by mustafasadikot** [comment]
As a work around I have temporarily added below code in my package.json:

"dependencies": {
    ....
    "@types/jquery": "2.0.34",
   ....
}

**Comment by GoshaFighten** [comment]
Would you please clarify if you are getting errors like `node_modules/@types/jquery/index.d.ts(43,40): error TS1005: ',' expected.`? What TypeScript version are you using?

**Comment by StephanHartmann** [comment]
I had errors like `node_modules/@types/jquery/index.d.ts(43,40): error TS1005: ',' expected.`
Using Typescript 2.3.4 fixed them for me.

**Comment by GoshaFighten** [comment]
@mustafasadikot @StephanHartmann 
It looks like jQuery updated their typings so that they need TypeScript 2.3+. At the moment, explicitly specify a version of the `@types/jquery` package to `2.0.34` or upgrade your TypeScript version to 2.3+. We will think about a better solution from our side in version 17.2 because if we apply corresponding changes now, it will be a breaking change for existing projects.

**Comment by NN---** [comment]
@GoshaFighten The issue is not with TS 2.3+ but with requirement of "es2015.iterable" .
Same here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17284

The only solution is to continue using 2.x typing.

**Comment by GoshaFighten** [comment]
@NN--- 
It looks like this is a fix for the `Cannot find name 'Iterable'` error. But, it does not fix the `',' expected` error.

![dximage](https://user-images.githubusercontent.com/10522139/27605828-826db67a-5b86-11e7-817a-032278a0a3dc.png)

**Comment by ShahinShabnam** [comment]
after writing  "dependencies": {
    ....
    "@types/jquery": "2.0.34",
   ....
} 

> package is building successfully but when i m installing this package in my angular2 project it throwing error.error description is below


"ERROR in Error: Error encountered resolving symbol values statically. Could not resolve devextreme-angular relative to D:/office/dateDev/node_modules/datepackage/datepackage.d.ts., resolving symbol SampleModule in D:/office/dateDev/node_
modules/datepackage/datepackage.d.ts, resolving symbol SampleModule in D:/office/dateDev/node_modules/datepackage/datepackage.d.ts.



package githublink is  https://github.com/ShahinShabnam/datepackage.git
