### ISSUE TITLE
TreeList, change value of cell when edited another

### ISSUE THREAD

**Issue by pawlik92** [DevExpress/devextreme-angular#490]
To help us process the issue more efficiently, please provide the following information:

Specify the version of the devextreme-angular and devextreme packages you are using.

devexteme version: 17.1.3
devextreme-angular version: 17.1.3

Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[x ] support inquiry

Hi,
I'm using editCellTemplate with dx-select-box inside.  In Row edit mode, when I change selected item inside dx-select-box I want to change value of another cell too.
My template look like this:
```
<div *dxTemplate="let data of 'resourceEditCellTemplate'">
  <dx-select-box [dataSource]="currentEditingRowAvailableResources" displayExpr="name" valueExpr="id" placeholder="" [value]="data.data.idResource"
          (onValueChanged)="resourceChanged($event,data)">
  </dx-select-box>
</div>
```

And my resourceChanged method:
```
resourceChanged(args: any, e: any) {
   e.setValue(args.value);
   let indexOfNameColumn = this.treeList.instance.getVisibleColumns().findIndex(x => x.dataField == "name");
   let nameCell = e.row.cells[indexOfNameColumn];
   nameCell.setValue("Changed name");
}
```

Unfortunately this does not work. Value does not change. Is there any possibility in the edit mode to change the value of another cell programmatically?

**Comment by GoshaFighten** [comment]
You need to implement the [setCellValue](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeList/Configuration/columns/#setCellValue) callback function of the master column to change a value of a dependent column in it. See the [dxDataGrid - How to implement cascaded lookup columns in an Angular app](https://www.devexpress.com/Support/Center/Question/Details/T508944) ticket where this approach is illustrated for the grid. If you need further assistance, feel free to post a corresponding ticket to our [Support Center](www.devexpress.com/ask).
