### ISSUE TITLE
dxi-item in dx-form. How to set the label text??

### ISSUE THREAD

**Issue by KevivL** [DevExpress/devextreme-angular#493]
<dxi-item label="ab" dataField="EndDate" editorType="dxDateBox" [editorOptions]="{ type: 'date' }">

I would expect the label there to set the text label next before the editor to "ab", instead it's still "End Date". Is there any way to change the label before the editor?? I tried the caption property as well, no effect.

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 16.2.6
    devextreme-angular version: 16.2.6
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ x ] support inquiry

**Comment by GoshaFighten** [comment]
Take a look at the [label](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxForm/Item_Types/SimpleItem/label/) help topic. The `label` option is an object. To change its text, use
 
```HTML
[label]="{text: 'ab'}"
```
