### ISSUE TITLE
Cannot test dxTemplate rendering

### ISSUE THREAD

**Issue by Spiti** [DevExpress/devextreme-angular#498]
devexteme version: 17.1.3
    devextreme-angular version: 4.1.2

I am trying to test that the content of a popup was loaded correctly.

The component template looks like this: 
`<dx-popup
    class="popup"
    [(visible)]="isVisible">
    <div *dxTemplate="let data of 'content'">
        <div>WTDFFFFFFFFFFFFFFFFFFFFFFFF</div>
    </div>
</dx-popup>`

The testing setup looks like this:
TestBed.configureTestingModule({
            imports: [
                HttpModule,
                BrowserModule,
                FormsModule
            ],
            declarations: [
                MyConfirmationComponent,
                DxPopupComponent,
                DxTemplateDirective
            ],
            schemas: [NO_ERRORS_SCHEMA],
            providers: [
                PopupService,             
            ]
        });
        TestBed.compileComponents();

The element that is render does not contain the template text: WTDFFFFFFFFFFFFFFFFFFFFFFFF.
It looks like this: `<dx-popup _ngcontent-c4="" class="popup dx-overlay dx-popup dx-widget dx-visibility-change-handler" ng-reflect-visible="true"></dx-popup>`

I can give more details if necessary. Thanks!

**Comment by GoshaFighten** [comment]
You can write a test to check the popup content in the following way:

``` TypeScript
it('should render popup content', async(() => {
  const fixture = TestBed.createComponent(AppComponent);
  const component = fixture.componentInstance;
  component.isVisible = true;
  fixture.detectChanges();
  const compiled = fixture.debugElement.nativeElement;
  const popupInstance = <DxPopupComponent>getDebugNode(compiled.querySelector('.dx-popup')).componentInstance;
  const content: any = popupInstance.instance.content();
  expect(content.find(':contains("WTDFFFFFFFFFFFFFFFFFFFFFFFF")')).toBeTruthy();
}));
```

But, perhaps, it's better to write an e2e test for this purpose.
[GH498.zip](https://github.com/DevExpress/devextreme-angular/files/1120404/GH498.zip)

**Comment by Spiti** [comment]
Thanks, GoshaFighten. Can I somehow use 'querySelector' instead of 'find'?

**Comment by GoshaFighten** [comment]
The `content` method returns a jQuery element. You can get a native element from a jQuery element in the following way:
 
```
const content: any = popupInstance.instance.content()[0];
```
But, jQuery selectors are much more powerful than native ones. So, you can't use the `:contains` selector with a native element. But, I think you can give an ID or CSS class to your content to obtain it using the `querySelector` method. For example:
 
```
const content: any = popupInstance.instance.content()[0];
expect(content.querySelector('#content')).toBeTruthy();
```
const content: any = popupInstance.instance.content()[0];
expect(content.querySelector('#content')).toBeTruthy();
```
 
```
<div *dxTemplate="let data of 'content'">
<div id="content">WTDFFFFFFFFFFFFFFFFFFFFFFFF</div>
</div>
```

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by Spiti** [comment]
thanks for the replies. I managed to implement it using your suggestion. Now I am trying to test the title of the popup which is in another dxtemplate, and I didn't manage that. Do you have any suggestions?
