### ISSUE TITLE
devextreme-angular [feature request] [Report viewer for angular]

### ISSUE THREAD

**Issue by apis3445** [DevExpress/devextreme-angular#499]
Hi! I think that is a good idea add support for the reportviewer from aspx https://documentation.devexpress.com/#XtraReports/CustomDocument17738  to devextreme for angular

**Comment by GoshaFighten** [comment]
You already can use our Report Viewer in an Angular application. I've attached a sample project to illustrate this. If you need further assistance, feel free to post a corresponding ticket to our [Support Center](https://www.devexpress.com/ask).
[GH499.zip](https://github.com/DevExpress/devextreme-angular/files/1120453/GH499.zip)

**Comment by johseffer** [comment]
Hi, with the demo in GH499.zip, how can i bind the field values? I try binding the DataSource (as the attach) property with the CustomReportResolve but not work's.
![capturar](https://user-images.githubusercontent.com/25435217/29790060-b053c170-8c0e-11e7-9493-53954bb37db7.PNG)

**Comment by GoshaFighten** [comment]
@johseffer 
This question does not relate to our Angular components. Post it to our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).

**Comment by johseffer** [comment]
Thank u, I already got it.

**Comment by johseffer** [comment]
Can i use the same of the project GH499 in an .Net Core 2.0 + Angular 4?

**Comment by GoshaFighten** [comment]
No, you need the full .NET framework. See [https://www.devexpress.com/Support/Center/Question/Details/T360117](https://www.devexpress.com/Support/Center/Question/Details/T360117).
