### ISSUE TITLE
DxToolbar content declaration is inconvenient

### ISSUE THREAD

**Issue by dxbykov** [DevExpress/devextreme-angular#50]
To add a button to a DxToolbar you declare it as a DxButton configuration object as follows:

in your host component TS code:

``` js
import { Component } from '@angular/core';
import { DxToolbar } from 'devextreme-angular2';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [DxToolbar]
})
export class AppComponent {
  toolbarItems = [{
            location: 'before',
            widget: 'dxButton',
            options: {
                text: 'Press me',
                icon: 'refresh',
                onClick: function() {
                    alert("Hello world!");
                }
            }
        }
    ];
}
```

in your HTML template:

``` html
<dx-toolbar [items]="toolbarItems"></dx-toolbar>
```

It doesn't seem to be natural. It's better to declare this as follows:

``` js
import { Component } from '@angular/core';
import { DxToolbar, DxToolbarItems, DxButton } from 'devextreme-angular2';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [DxToolbar, DxToolbarItems, DxButton]
})
export class AppComponent {
  sayHello() {
    alert("Hello world!");
  }
}
```

``` html
<dx-toolbar>
  <dx-toolbar-items location="before">
    <dx-button text="Press me" (onClick)="sayHello()" icon="refresh"></dx-button>
  </dx-toolbar-items>
</dx-toolbar>
```

**Comment by KevinGruber** [comment]
What is the current status on that?

I mean the overall status of rewriting components to use more transclution. for example i also think it is a problem that the button is having a text property and ignores the content between the brackets. The natural way would be to use that.

That problem is consistent across all of your Components.

BR,
Kevin

**Comment by GoshaFighten** [comment]
@KevinGruber 
You can achieve this functionality using the `dxi-item` component as described in the [Configuration Components](https://github.com/DevExpress/devextreme-angular#configuration-components) topic. This works for the `items` option of any widget. So, your markup will be like the following:
 
``` HTML
<dxi-item location="before">
<dx-button type="back" text="Back" (onClick)="buttonClick('Back button has been clicked!')"></dx-button>
</dxi-item>
```
 
See the [Plunker](http://plnkr.co/edit/Pat9VoJWqQ8WqdmlyliM?p=preview) that illustrates how it's possible to re-write the [Toolbar - Overview demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Toolbar/Overview/Angular/Light/) using this approach.
