### ISSUE TITLE
devextreme-angular [feature request] [Export to pdf]

### ISSUE THREAD

**Issue by apis3445** [DevExpress/devextreme-angular#500]
I think that the components like grid and charts should include the export to pdf option

**Comment by GoshaFighten** [comment]
This question is about our DevExtreme widget rather than our Angular integration. The grid supports exporting to XLSX only. But, our charts support exporting to PDF. See [this help topic](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/export/).
