### ISSUE TITLE
Typescript(JQuery) Issues, breaking framework

### ISSUE THREAD

**Issue by AndrewVetovitz** [DevExpress/devextreme-angular#501]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.4
    devextreme-angular version: 17.1.4
- Specify the type of the issue (check one with "x"): 
[X ] bug Report 
[ ] feature request 
[ ] support inquiry 

Issues:
Too many to list all of them, 100-200 total, some examples below.
Examples:
.../node_modules/@types/jquery/index.d.ts (4471,9): ',' expected.

.../node_modules/devextreme/viz/vector_map.d.ts (13,20): Generic type 'JQuery<TElement, HTMLElement>' requires 2 type argument(s).

Problem areas:
typescript@~2.2.0

Dependencies currently break modules when importing them, just installing and running is not enough to show the break happening. 

Currently I can fix the issue by doing:
npm install --save-dev @"types/jquery"@2.0.34 (remove quotes, git wont show this otherwise)
or
npm install --save jquery@2.2.4
or
updating typescript version to 2.3.0. Problem is you would not know this from just seeing the issues.

There is a similar problem currently with another framework regarding this break that can be read here, so this is not isolated to just devextreme-angular: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/17239

**Comment by GoshaFighten** [comment]
Yes, this is a known issue. See the [Build error with latest @types/jquery version - 3.2.0](https://github.com/DevExpress/devextreme-angular/issues/483) issue for more details.

**Comment by rvacchi** [comment]
i am having this problem can anyone help me sort this out thanks
