### ISSUE TITLE
List Selection 17.1.4

### ISSUE THREAD

**Issue by VitaliiStriu** [DevExpress/devextreme-angular#503]
After update to 17.1.4 notice that Select All not uncheck all fields for dx-list. You can reproduce it in your example when select Selection Mode = all and Select All Mode = allPages. 
https://js.devexpress.com/Demos/WidgetsGallery/Demo/List/ListSelection/Angular/Light/Compact/

Will it be fixed in next version?

**Comment by GoshaFighten** [comment]
This issue is already fixed in the context of the [dxList - "Select All" stops working after selecting all items if selectAllMode is "allPages"](https://www.devexpress.com/Support/Center/Question/Details/T531246) ticket.
