### ISSUE TITLE
Error in Demo?

### ISSUE THREAD

**Issue by iqmeta** [DevExpress/devextreme-angular#504]
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DropDownBox/MultipleSelection/Angular/Light/

Unselect all not working.

![seacoll](https://user-images.githubusercontent.com/7533842/27904298-94e71320-623c-11e7-9b4f-281e82d417da.gif)

**Comment by GoshaFighten** [comment]
This issue is already fixed in the context of the [dxList - "Select All" stops working after selecting all items if selectAllMode is "allPages"](https://www.devexpress.com/Support/Center/Question/Details/T531246) ticket.
