### ISSUE TITLE
How to get the parent row on onInitNewRow using the Master-Detail view

### ISSUE THREAD

**Issue by afriedma** [DevExpress/devextreme-angular#507]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.4
    devextreme-angular version: 17.1.3
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x ] support inquiry 

Hi,

I did put in a request with support, but I am afraid they may not be familiar with Angular.
Can you please assist?  Link to support request https://www.devexpress.com/Support/Center/Question/Details/T533277/how-to-get-the-parent-row-on-oninitnewrow-event-using-the-master-detail-view

**Comment by GoshaFighten** [comment]
@afriedma 
Believe me that our entire Support Team is familiar with Angular. Please wait for our reply in the mentioned Support Center ticket.

**Comment by alberthoekstra** [comment]
I'm having the same question.
Unfortunately the ticket cannot be viewed.

Can you post the result or make the question public or so?

**Comment by afriedma** [comment]
@alberthoekstra 

You can pass the master row key via the custom attribute of the detail grid element. For example, based on the Master-Detail View demo, you can use the following syntax:

app.component.html:
[HTML]Open in popup window
<dx-data-grid class="internal-grid"
    [dataSource]="employee.data.Tasks"
    [attr.data-master]="employee.data.ID"
    (onInitNewRow)="onInitNewRow($event)"
...

app.component.ts:
[JavaScript]Open in popup window
onInitNewRow(e: any): void {
    alert(e.element[0].attributes["data-master"].value);
}

Based on this key, you can obtain the required values from the underlying datasource.

**Comment by alberthoekstra** [comment]
Thanks!
