### ISSUE TITLE
Internationalization i18n Angular

### ISSUE THREAD

**Issue by Spiti** [DevExpress/devextreme-angular#508]
We are using Angular 4 in our project and we added angular i18n internationalization. It works as expected for statis html, but we have an issues when it comes to devextreme-angular controls. Is it possible to use angular i18n for translating content for popup titles, buttons, placeholders, etc, or we need to use some other solution?
Thanks,
Andrei

**Comment by GoshaFighten** [comment]
You can surely use the Angular i18n feature to translate grid column captions, button texts, etc. to your language. See the [Plunker sample](https://plnkr.co/edit/3BebUJ2xFVp7gdrFZmiW?p=preview) that illustrates this. But, to translate our internal strings, you still need to use the approach described in the [Localization](https://js.devexpress.com/Documentation/Guide/Widgets/Common/UI_Widgets/Localization/) article.

**Comment by dondre** [comment]
Angular4 isn't using SystemJS any longer is it?

**Comment by GoshaFighten** [comment]
@dondre Why do you think that you can't use Angular 4 with System JS? You should be able to use it with any module loader.

**Comment by tropetre** [comment]
How about your nested components such as buttons in the popup toolbars? 
They're dxi's with a "options" object-property...

**Comment by GoshaFighten** [comment]
@tropetre 
Would you please provide me with a sample project to illustrate what you need to localize?

**Comment by tropetre** [comment]
Sure thing! Hopefully this is self-explainatory:
https://plnkr.co/edit/Bbc46CL2CqjB2l8vgCBh?p=preview

**Comment by tropetre** [comment]
@GoshaFighten Any news on the subject?

**Comment by GoshaFighten** [comment]
Thank you for your project, @tropetre . I've not found a way to make Angular i18n work with it. I suggest you use [ngx-translate](https://github.com/ngx-translate/core) instead.

**Comment by Spiti** [comment]
We ended up using ngx-translate. It works like a charm. It is more flexible than angular i18n. You can use it using attributes or binding with pipes. You can also inject the translation service into the component so that you are not only limited to the html. Example can be found here: https://github.com/GoshaFighten/dx-ngx-application

**Comment by GoshaFighten** [comment]
Yes, @Spiti . I also like `ngx-translate` more.

**Comment by tropetre** [comment]
@GoshaFighten That's unfortunate, the less dependencies the better and having to do run-time translation is a bummer.

@Spiti Might want to fix that link. It got an extraneous space at the end :)

**Comment by timothyBrake** [comment]
Ran into this issue as well. nix-translate is considered a deprecated project by the creator himself as he is hired by Google to work on Angular i18n.
Would be nice if DevExtreme has a working solutions for this issue.
