### ISSUE TITLE
Zone.js@0.8.13 causig error with devextreme Toast

### ISSUE THREAD

**Issue by tcrack326** [DevExpress/devextreme-angular#509]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.4
    devextreme-angular version: 17.1.4
- Specify the type of the issue (check one with "x"): 
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Updating my npm packages to the latest in my angular project caused a bug with the Toast. The attached screenshot shows the error message. I went through all the packages and I've narrowed it down to Zone.js@0.8.13. I change this to 0.8.12 and its working normally.

![image](https://user-images.githubusercontent.com/2215681/28186392-f99bf982-67e8-11e7-8fb5-14606f35beee.png)

**Comment by GoshaFighten** [comment]
Yes, the zone.js library of version 0.8.13 causes the issue. Also, see the following issues on their GitHub repository:

- [zone.js v0.8.13 completely brakes down Angular v4.2.6 with NO errors!!!](https://github.com/angular/zone.js/issues/836)

- [zone.js v0.8.13 Produces Extensive Zone errors in Unit tests-- 'Unhandled Promise rejection:', 'Cannot create property '__creationTrace__'](https://github.com/angular/zone.js/issues/832)

I see that the zone.js library team is working on fixing them. While they are doing this, downgrade zone.js to 0.8.12.
