### ISSUE TITLE
Cell editing, but only for certain cells

### ISSUE THREAD

**Issue by Cito** [DevExpress/devextreme-angular#511]
I like the [cell editing mode shown here](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CellEditingAndEditingAPI/Angular/Light/).

However, I do not want all columns to be editable, but only some of them. Is this possible?

I tried putting the `<dxo-editing mode="cell" [allowUpdating]="true"></dxo-editing>` into the `<dxi-column>` element, but that doesn't work.

**Comment by GoshaFighten** [comment]
Use the `allowEditing` option at the grid column level to prevent the column from being edited.

``` HTML
<dxi-column [allowEditing]="false"></dxi-column>
```

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by Cito** [comment]
Oh, this was pretty obvious, and I can confirm it works. Thank you for answering.

**Comment by Hypenate** [comment]
Despite setting` allowEditing="false"` (or `[allowEditing="false"`) I'm still able to edit all the columns.
I want to edit some columns, but I just set all columns to `allowEditing="false"` for testing purposes.

```
<dx-data-grid [dataSource]="dataSource"
    <dxo-editing mode="batch" [allowUpdating]="true"> </dxo-editing>
       <dxi-column *ngFor="let column of columns" dataField="{{column.dataField}}" caption="{{column.caption}}" [width]="column.width"
        dataType="{{column.dataType}}" allowEditing="false"></dxi-column>
</dx-data-grid>
```
Did things change?
