### ISSUE TITLE
Some issues with the "Cell Editing and Editing API" example

### ISSUE THREAD

**Issue by Cito** [DevExpress/devextreme-angular#512]
I tried the example in the [Cell Editing and Editing API ](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/CellEditingAndEditingAPI/Angular/Light/) with the current Angular 4.3.0 and DevExtreme 17.1.4 version, using the code given in the "Angular" tab.

Frist, I found several obvious errors in the code, like some invalid CSS, a "Picture" member in the "Employee" class which was missing in the example data, and a type mismatch in the "dataSrouce" definition of the component (declared as Array type, but then used as ArrayStore type), which prevent compilation. Where should I report such issues or send pull requests?

Second, after fixing these, it still doesn't work properly - the "state" menu and the "birthdate" date picker do not pop up, nothing happens if I click the corresponding buttons. Any ideas what could be the problem here, or how I should debug such problems? Since nothing happens, I don't even get an error message in the browser log. Editing the texts works, however.

**Comment by GoshaFighten** [comment]
Please post such issues to our [Support Center](https://www.devexpress.com/Support/Center). I see compilation problems with the missing Picture field and with assigning an ArrayStore instance to an array. I've created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T538975) in our Support Center.

As for invalid CSS rules, would you please clarify which rule is invalid?

As for the problem with our popups, I think that you are using the zone.js library of version 0.8.13. This version has certain issues that break our functionality. See the #509 issue that describes this.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by Cito** [comment]
Thanks for the helpful answers.

The CSS rules were ok, only me and my linter hadn't come across the `/deep/` selector before. The new syntax is `::ng-deep`, but of all thes are provisionary solutions. Maybe you should add a comment to the CSS to explain to the uninitiated what this is doing.

Regarding the problems with the popups, I can confirm I was using zone.js 0.8.13, and upgrading to 0.8.16 solved the problem.
