### ISSUE TITLE
Pivot Grid Filters Jumping

### ISSUE THREAD

**Issue by iqmeta** [DevExpress/devextreme-angular#513]
Hi,
I tried this example
https://js.devexpress.com/Demos/WidgetsGallery/Demo/PivotGrid/ChartIntegration/Angular/Light/
with the angular cli, with very strange behavior (no js errors):

![strange](https://user-images.githubusercontent.com/7533842/28322087-739320ae-6bd5-11e7-86fb-2b6b50651d57.gif)

here is the code (npm install/npm start)

[analysis.zip](https://github.com/DevExpress/devextreme-angular/files/1156150/analysis.zip)

Everything is newest major npm package.
Any idea whats wrong?

Kind regards.

**Comment by michaelkochhugobosscom** [comment]
Any news about thst ??

**Comment by GoshaFighten** [comment]
This issue is caused by zone.js of version 0.8.13. See #509 issue for more information.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
