### ISSUE TITLE
dev express dx-drop with angular2

### ISSUE THREAD

**Issue by eomer1975** [DevExpress/devextreme-angular#514]
I'm trying to port this example to **angular2**
[http://plnkr.co/edit/aMAHCZC2hDwgABHu2CmW?p=preview](http://plnkr.co/edit/aMAHCZC2hDwgABHu2CmW?p=preview).

But the event **dx-drop**
`<div class="external" dx-drop="dropped($event)"></div>` or`
`<div class="external" (dx-drop)="dropped($event)"></div>``
**doesn't fire.**

The drag work, i can bring the appointment outside the scheduler.

All the handler of the scheduler work:

`onAppointmentRendered(e) {
        var appointment = e.appointmentElement;
        var draggableAppointment = appointment.dxDraggable("instance");
        draggableAppointment.option("area", "body");

        e.appointmentElement.on("dxdragstart", function (evt) {
            this.appointmentData = e.appointmentData;
            e.element.find(".dx-scrollable-content").css("overflow", "visible");
            e.element.find(".dx-scheduler-work-space").css("overflow", "visible");
        });

        // return overflow: hidden
        e.appointmentElement.on("dxdragend", function (evt) {
            e.element.find(".dx-scrollable-content").css("overflow", "hidden");
            e.element.find(".dx-scheduler-work-space").css("overflow", "hidden");
        });
    }`

Here my destination box: 
` <div style="width:270px; min-height: 400px; border: 2px solid#F00 ;" (drop)="dropped($event)">
      <p>Drop items here</p>
      <repeater [repeaterArray]="movedBooliList" class="slotTimeMainWrapper">
        <ng-template let-row="item">
          <app-book [showtime]="row"></app-book>
        </ng-template>
      </repeater>
    </div>   `
Here the handler in the momponent:
`dropped() {
        debugger;
    }`

How could i solve?

**Comment by GoshaFighten** [comment]
Events like dxdrop, dxdragstart, dxdragend are jQuery events. You need to handle them using the jQuery [on](http://api.jquery.com/on/) method.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by alesgaber** [comment]
Is possible to implement drag & drop from external source to scheduler in angular2+?
