### ISSUE TITLE
Report viewer in Angular 4 with asp.net core

### ISSUE THREAD

**Issue by Niyasudeen** [DevExpress/devextreme-angular#515]
I am using devexteme trial version for evaluation purpose. My application using Angular4 for front end and asp.net core for back end. In my application i want to use devexpress reporting. so is it possible to use in angular4?. 

Basically i want to load the data into the report by entity framework core using front end angular4.

**Comment by GoshaFighten** [comment]
You can use our Reports in Angular applications. See my solution from the #499 issue. But, Reports needs at least full .NET Framework as a backend. See the [How to integrate DevExpress reporting components into an ASP.NET Core (a.k.a vNext / ASP.NET 5 / MVC6) web application](https://www.devexpress.com/Support/Center/Question/Details/T360117) article.
