### ISSUE TITLE
DevExtreme Angular components force Angular change detection

### ISSUE THREAD

**Issue by Aden-git** [DevExpress/devextreme-angular#516]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.4
    devextreme-angular version:  17.1.4
- Specify the type of the issue (check one with "x"): 
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

The Angular change detection strategy checks changes on every mouse event on the page when the DevExtreme Angular module is imported in the lazily loaded view. With DevExtreme components, the Angular change detection strategy also makes more checks than it should be.
It can be reproduced in the [Plunker sample](http://plnkr.co/edit/Rb7cofWwfsrPDgb0dYdc?p=preview). Just check the console.

This issue is based on DevExpress/DevExtreme#756

**Comment by Aden-git** [comment]
This issue occurs when DevExtreme is being initialized in the context of the Angular zone. Currently, we are improving our integration with Angular, and this issue will be resolved in that context.

As a workaround, some of the DevExtreme modules can be imported in the root of the application. Please check the [sample on Plunker](http://plnkr.co/edit/NhVhPnyWdKcTp4q07Vmh?p=preview).

**Comment by dxvladislavvolkov** [comment]
After additional testing, we found regression in the existing code. We reverted these changes and will make an update here once we find a more efficient solution.

**Comment by MoiraG** [comment]
I still have the problem as soon as I move the mouse over the dxdatagrid.

Here is an example: https://stackblitz.com/edit/angular-o6xaio
