### ISSUE TITLE
Class 'DxComponent' incorrectly implements interface 'ICollectionNestedOptionContainer'.

### ISSUE THREAD

**Issue by nsrtky** [DevExpress/devextreme-angular#519]
when tring to use dvextre component icollectionnestedoptioncontainer implementation  error both basenested also. i am going to give you print-screen for this error.

![image](https://user-images.githubusercontent.com/12385044/28775744-44166cba-75fc-11e7-8129-dee91d5af437.png)

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 
    devextreme-angular version: 
- Specify the type of the issue (check one with "x"): 
[* ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by GoshaFighten** [comment]
This issue is already fixed. See #502 .
