### ISSUE TITLE
Undocumented/typed "isLoadingAll" property of CustomDataStore LoadOptions

### ISSUE THREAD

**Issue by fongoid** [DevExpress/devextreme-angular#522]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version:  16.2.6
    devextreme-angular version: 
- Specify the type of the issue (check one with "x"): 
[x] bug Report -- https://plnkr.co/edit/d9ANEA81nNNlmxBNqb2l?p=preview

When using a CustomDataStore and Export on a DataGrid, the load function gets called with no `skip`/`top` properties but instead an `isLoadingAll` property which TypeScript doesn't like. Console logged the `loadOptions` object which appears as expected for load/grid manipulation, but with different properties when you click the export button.

**Comment by GoshaFighten** [comment]
This is a private option. If `loadOptions.skip` or `loadOptions.take` are not present, load all records.
