### ISSUE TITLE
Need info on webpack configuration.

### ISSUE THREAD

**Issue by verybadcat** [DevExpress/devextreme-angular#524]
Your demos refer to systemjs.config.js. See here for example:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileUploader/FileUploading/Angular/Light/

But Webpack doesn't use that file. So what do we do in an angular-cli project?

**Comment by GoshaFighten** [comment]
Check out [Using the DevExtreme Angular Components with Angular CLI](https://github.com/DevExpress/devextreme-angular/blob/master/docs/using-angular-cli.md#configuration) to learn how to include our widgets in an Angular CLI project.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
