### ISSUE TITLE
Add bindingOptions for DxPopup to disable toolbarItems dxButton widget via binding

### ISSUE THREAD

**Issue by Lindvorn** [DevExpress/devextreme-angular#526]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.3
    devextreme-angular version: 17.1.3
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[x] feature request 
[ ] support inquiry 

Hello. 

Current behavior: dxButton is declared in toolbarItems, disabled property can be specified but accepted value is of boolean type. Impossible to specify "bindingOptions" for toolbarItems.
Expected behavior: either dxButton's disabled property can be declared as function(or as a text with binding) or bindingOptions is available to specify for DxPopup.

UseCase: I need to bind popup widget's (button) disabled property and in DevExpress forum they suggest using "bindingOptions" (for AngularJS https://www.devexpress.com/Support/Center/Question/Details/T294915/controlling-popup-button-disabled-state-in-angularjs).
Setting disabled property for toolbar item with current approach just makes no sense since there's no way to change disabled value to anything else in code. And once button is declared as disabled it's just useless on UI.

**Comment by GoshaFighten** [comment]
Angular is different from Angular JS. So that Angular tracks changes of component properties, they should be bound in the component markup. So, you need to bind the toolbar item `options` option in your component markup and change the bound object:
 
``` HTML
<dxi-toolbar-item [toolbar]="'bottom'" [location]="'after'" [widget]="'dxButton'" [options]="buttonOptions"></dxi-toolbar-item>
```
 
``` TypeScript
buttonOptions = {
  text: "Ok",
  disabled: true
};
enableSubmit() {
  this.buttonOptions = {
    text: "Ok",
    disabled: false
  };
}
```
 
See the [Plunker sample](http://plnkr.co/edit/9sDJCJQiVPXh5J0Z10NL?p=preview) that illustrates this.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
