### ISSUE TITLE
Devextreme Bundlesize

### ISSUE THREAD

**Issue by MoiraG** [DevExpress/devextreme-angular#530]
devexteme version:  17.1.5
    devextreme-angular version: 17.1.5
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[x ] support inquiry 

Hello,

we are using devextreme in our angular 4 application.  For now we are using only the datagrid and the treeview. Our bundle-size has grown dramatically. We have checked the bundle with the [Webpack bundle anzalyzer](https://github.com/robertknight/webpack-bundle-size-analyzer) and devextreme is much bigger than angular + any other library. Here is an overview of the current devextreme size (without devextreme-angular): 
![2017-08-17 15_52_58-webpack bundle analyzer](https://user-images.githubusercontent.com/18344771/29415728-397488e4-8364-11e7-8108-6ca1622f0b85.png)

We are importing the grid and treeview with the "longpath"
`devextreme-angular/ui/data-grid`

Is this the normal bundle-size for grid+treeview or can we optimize the size?

Thank you

**Comment by Mehul** [comment]
Hi Moira, take a look at this and it may help you:
https://community.devexpress.com/blogs/aspnet/archive/2016/08/30/devextreme-and-modularity-bundles-requirejs-and-webpack.aspx

**Comment by MoiraG** [comment]
I can`t see any difference to my project.

I have created a minimal new project with angular-cli and installed everything for devextreme.

Between these two imports, there is no difference in bundle size:

`import { DxDataGridModule } from 'devextreme-angular';`
`import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';`

Everything from devextreme gets imported.

**Comment by GoshaFighten** [comment]
@MoiraG 
The grid needs all of these modules. So, you are getting the correct bundle size.
