### ISSUE TITLE
Asp.net Core 2 Angular Spa Template with Webpack

### ISSUE THREAD

**Issue by coneslager** [DevExpress/devextreme-angular#531]
The most recent template released from MS no longer has the vendor section and now has shakable tree stuff.  I have tried different options , but not sure what to include in the shakable/non shakable module sections.

Not sure when if I have something else setup wrong, but when I add the module into the import section of app.module, , my app no longer runs and throws errors.

Can you provide information how to setup with this new template?

**Comment by GoshaFighten** [comment]
The steps here are the same as described in the [Add DevExtreme to NET Core Angular 2 Template
](https://js.devexpress.com/Documentation/Guide/VS_Integration/Add_DevExtreme_to_NET_Core_Angular_2_Template/) article. Only add our CSS files to the `nonTreeShakableModules` array of the webpack.config.vendor.js:
 
``` JavaScript
const nonTreeShakableModules = [
    'bootstrap',
    'bootstrap/dist/css/bootstrap.css',
    'es6-promise',
    'es6-shim',
    'event-source-polyfill',
    'jquery',
    'devextreme/dist/css/dx.common.css',
    'devextreme/dist/css/dx.light.css'
];
[GH531.zip](https://github.com/DevExpress/devextreme-angular/files/1235138/GH531.zip)

```
See the attached project.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
