### ISSUE TITLE
Losing selected value on datasource change

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#533]
If I select a value from a `select-box` and than I refresh the items/datasource, I lost the current value on the UI because of the reference value change.

Is it possible to override the compare behaviour?

**NB**
I wrongly opened an issue [here](https://github.com/DevExpress/DevExtreme/issues/1105) 
 and **AlekseyMartynov** suggested me to use `valueExpr="id"` but I can't use it because of I need to bind the entire object and not only the `id`.  

### Steps to Reproduce:

[This Plunker ](http://plnkr.co/edit/S1I2RVZyT2g16n1O5tHv?p=preview) reproduce the problem.

### Results You Expected:

Changing the items/datasource I would like to not lose the current selected value

### Environment Details:
OS: MacOs 10.12.6
angular/cli: 1.2.3
node: 6.11.0

**Comment by GoshaFighten** [comment]
You create a new `items` array each time a uses clicks the "Refresh item"` button. So, while you are an object with the same field values, a reference to an object is different. This behavior is described in the [dxSelectBox/dxLookup does not select an item if the valueExpr option is set to "this" and the value option is set programmatically](https://www.devexpress.com/Support/Center/Question/Details/T371967) article. Use the first solution in the article to resolve the issue.
