### ISSUE TITLE
The Ahead-of-Time webpack plugin cannot compile devextreme-angular modules

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-angular#534]
[NGCore.zip](https://github.com/DevExpress/devextreme-angular/files/1239912/NGCore.zip)
Attached project shows the issue in action. 

Steps to reproduce:

1. Open up the webpack.config.js file.
2. Find the sharedConfig object.
3. Replace the 
```javascript 
{ test: /\.ts$/, include: /ClientApp/, use: ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] }, 
``` 
code with the following one 
```javascript 
{ test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' }, 
```
4. Save changes and execute the following command:
```
dotnet publish -c Release
```

**Comment by GoshaFighten** [comment]
Change line 20 in the `webpack.config.js` file to the following to avoid the issue.

``` JavaScript
{ test: /\.ts$/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },
```

**Comment by GoshaFighten** [comment]
According to [https://github.com/aspnet/Templates/issues/863](https://github.com/aspnet/Templates/issues/863), this is an issue in the ASP.NET Core Angular template. Wait for the next .NET 2.0 SDK.
