### ISSUE TITLE
SelectBox error with observable datasource using async pipe

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#535]
Changing the `select-box datasource` using the `async` pipe, we get an Error.

### Steps to Reproduce:

[This Plunker ](https://plnkr.co/edit/hWGdTXhoFVtazc5GUoAg) reproduce the problem.

  - select a value from the 'master' selectBox
  - 'detail' selectBox will be updated, select a value from 'detail' too
  - choose a new value from 'master'
  - see console for the error 'Cannot read property 'pageIndex' of undefined'

### Environment Details:
OS: MacOs 10.12.6
angular/cli: 1.2.3
node: 6.11.0

**Comment by GoshaFighten** [comment]
This issue was fixed in the `devextreme` package, version 17.1.6. Check out your sample again. It does not reproduce the issue anymore.

**Comment by snajahi** [comment]
The async problem is also reproducible in SimpleItem components with editor type `dxSelectBox`

`<dx-form id="form" [formData]="Product">
      <dxi-item dataField="ProductTypeId" [editorOptions]="{items: productTypes$ | async, displayExpr: 'Name', valueExpr: 'id' }" editorType="dxSelectBox"></dxi-item> <dx-form>`

The above code fails silently (empty drop-down).

Also note that when we subscribe to the observable in the component itself and populate a local array to use with the dxi-item it's always empty, but when we initialise the same array with hard-coded values, the drop-down is filled properly.
