### ISSUE TITLE
Localize calendar widget

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#539]
Hi,
is there a way to localize the calendar widget at runtime?
I tried with `locale('de');` but it does not work. Neither at the first time.

Thanks a lot

### Environment Details:
OS: MacOs 10.12.6
angular/cli: 1.2.3
node: 6.11.0

**Comment by GoshaFighten** [comment]
Our widgets take localized strings at the moment they are created. Further changes of the current locale are not tracked. If you need to change an application locale at run-time, save a new locale to cookies or local storage, then, refresh your page. On your application startup, read the saved locale and apply it. If this does not work for you, open a new [Support Center ticket](https://www.devexpress.com/Support/Center/Question/Create) along with a project to illustrate the issue.
