### ISSUE TITLE
DxMenu iconSrc not positioned correctly if assigned "later"

### ISSUE THREAD

**Issue by jakehockey10** [DevExpress/devextreme-angular#547]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.6
    devextreme-angular version: 17.1.6
- Specify the type of the issue (check one with "x"): 
- [x] bug Report 
- [ ] feature request 
- [ ] support inquiry 

I'm having trouble using an image in the `DxMenuComponent`'s `iconSrc` property.  It works fine if the image is supplied before runtime.  But if, during runtime, I provide the `iconSrc` after some time (simulating a request to gravatar for instance) and the image shows up, but covers the menu's title.

Here is a plunker replicating the issue: http://plnkr.co/edit/lyqVIf?p=preview

The first menu is the problematic one.  I gave it a timeout of 3000 milliseconds so you will see the image cover 'Menu' in 3000 seconds once the application is bootstrapped.

Is there anything I can do to get the image and title to not overlap if I'm providing the bound image in a callback?

**Comment by GoshaFighten** [comment]
The `iconSrc` property is deprecated. Use `icon` instead. See the [iconSrc](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxMenu/Default_Item_Template/#iconSrc) help topic. But, I see the issue on my side. We will research it. At the moment, set the `icon` property to a dummy value initially to avoid the issue. See the updated [plunk](http://plnkr.co/edit/exTnewXAa1HDAaYQTvsF?p=preview).

**Comment by dxvladislavvolkov** [comment]
This issue was fixed in DevExtreme of version 17.1.10
