### ISSUE TITLE
Data Grid emit event on row edit cancelled

### ISSUE THREAD

**Issue by NoahQuintero** [DevExpress/devextreme-angular#549]
devexteme version: 17.1.4
    devextreme-angular version: 17.1.4
    [x] feature request

Right now, there doesn't appear to be an event emitted for when row editing is cancelled, while row creation, updating, and deleting do have events. This makes it difficult to create behavior for when a user chooses to cancel editing a row.

**Comment by GoshaFighten** [comment]
This question does not relate to our Angular integration. It's about how our DevExtreme grid works. Yes, it does not have an event to catch if editing is canceled. Check out the [T182635](https://www.devexpress.com/Support/Center/Question/Details/T182635) ticket for possible solutions here.

**Comment by NoahQuintero** [comment]
https://embed.plnkr.co/D7Q5SInvPOA5U6tzCY34/

The problem is that the handler function is not executed within the scope of the component. Since the function isn't executed in the scope of the grid, if the user cancels editing, I cannot act upon any data within the component. When clicking on the white space of the command cell (I couldn't bind to the cancel link in the exact manner described in the provided ticket), it can be observed that the data I want to access will be undefined. Though it is defined for the component, it is not available in the scope where the function will be executed.

**Comment by GoshaFighten** [comment]
It's not clear to me what actions I should perform to see the issue. In any case, I suggest you use the approach from the [Callback Functions](https://github.com/DevExpress/devextreme-angular#callback-functions) topic to be sure that "this" references to your component.

**Comment by NoahQuintero** [comment]
This seems to work for me, thanks.
