### ISSUE TITLE
Data Grid always hide column under ellipsis

### ISSUE THREAD

**Issue by NoahQuintero** [DevExpress/devextreme-angular#550]
devexteme version: 17.1.4
    devextreme-angular version: 17.1.4
    [x] feature request

Columns can only be hidden under the ellipsis when the grid has column hiding enabled. A column attribute to have a column always hide under the ellipsis would be useful for when data should be accessible, but isn't necessarily important. There is currently the "visible" attribute, but the data of that column isn't visible until the row is being edited (and only in 'form' or 'popup' mode, it is still not shown in 'row' or 'batch' mode).

**Comment by GoshaFighten** [comment]
To be honest, I don't understand what behavior you have now and what you wish to have. Would you please provide me with a sample project to illustrate the issue?

**Comment by NoahQuintero** [comment]
https://embed.plnkr.co/D7Q5SInvPOA5U6tzCY34/

When the grid width shrinks, columns will be hidden under the ellipsis. I want an attribute on dxi-columns that lets me define that a column should always appear under the ellipsis.

**Comment by GoshaFighten** [comment]
There is no option for this. I suggest you post this request to our [Support Center](https://www.devexpress.com/Support/Center/Question/Create) so that we don't miss it.
