### ISSUE TITLE
Incomplete support for Angular i18n

### ISSUE THREAD

**Issue by tropetre** [DevExpress/devextreme-angular#553]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1
    devextreme-angular version: 17.1
- Specify the type of the issue (check one with "x"): 
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

Currently i18n works fine for most DevExtreme widgets however in some nested options we're forced to bind to a configuration object which disables support for i18n since it requires "static" variables.

We briefly discussed this in #508 where @GoshaFighten did not find a way to make the translation work on the provided [plunker]. (https://plnkr.co/edit/Bbc46CL2CqjB2l8vgCBh?p=preview)

For now, a work-around can be achieved using the package "ngx-translate" however this breaks the translation-flow provided by the i18n which is very undesirable i larger applications.

**Comment by GoshaFighten** [comment]
I believe that Angular i18n does not support all our ways to set text options. :smile: It localizes only strings directly bound to a string component option in markup. But, many people want it to localize strings in code as well. See https://github.com/angular/angular/issues/11405, for example. As for your particular scenario, you can render dxButton in the toolbar item template to localize the button text using Angular i18n. See the updated [plunk](https://plnkr.co/edit/Vv27Pax6BYgD2YtUHfpz?p=preview).

``` HTML
<dx-popup i18n-title="@@introductionHeader" title="Hello i18n!" visible="true">
  <dxi-toolbar-item>
    <dx-button i18n-text="@@btnText" text="How about this?"></dx-button>
  </dxi-toolbar-item>
</dx-popup>
```
