### ISSUE TITLE
Issue Regarding DxSchedulerModule.

### ISSUE THREAD

**Issue by nick412** [DevExpress/devextreme-angular#559]
My Issue Regarding the DxSchedulerModule Which helps me to render calendar scheduler properly but the events/appointment was not loading properly i use below reference to my angular 4 project.

https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Overview/Angular/Light/ 

![image](https://user-images.githubusercontent.com/32121809/30629472-9fb59a8a-9df9-11e7-8b76-3ec6cb0ab2f3.png)

it is looks something like above image but once i click F12 key to see my Developer console it seems like below initially it looks like resize issue once I open Developer console it is scheduler got resize.

![image](https://user-images.githubusercontent.com/32121809/30629503-d2b8d91a-9df9-11e7-8a02-dc53ad31a5bb.png)

 i didn't get what is the main issue to not render it properly i use the reference to my angular 4 + web-pack project but reference are given code as per system.js so is there any additional i want to add my current code please help me out for the same.

**Comment by GoshaFighten** [comment]
What zone.js version do you have? Upgrade it to the latest one (0.8.18). If this does not resolve the issue, provide me with a sample project to reproduce the issue.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
