### ISSUE TITLE
Treeview onItemSelectionChanged Event not fired

### ISSUE THREAD

**Issue by christophedemey** [DevExpress/devextreme-angular#577]
Hi

in my template i have 
`
  <dx-tree-view [(dataSource)]="stationsTreeviewData"
                  dataStructure="plain"
                  (onItemSelectionChanged)="hello($event)"
                  style="margin-left:5px;">
    </dx-tree-view>
`

Then in typescript i have 
`
   hello(value) {
        console.log(value);
    }
`

My plain data mode in typescript 
`
export class StationTreeviewDataModel{
    id: string;
    stationId: string;
    text: string;
    expanded: boolean;
    parentId: string;
}
`

The event does not fire when i click on a node.

Thanks.

**Comment by artem-kurchenko** [comment]
Hi,
 
The [onItemSelectionChanged](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Configuration/#onItemSelectionChanged) has effect if either selectByClick is true or selection check boxes are visible. If none of these options are suitable for you, use the [onItemClick](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Configuration/#onItemClick) handler instead.
