### ISSUE TITLE
Question on event handling

### ISSUE THREAD

**Issue by MichaelGaihede** [DevExpress/devextreme-angular#578]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1.4
    devextreme-angular version: 17.1.4
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by MichaelGaihede** [comment]
When assigning an event handler (in Typescript) to the setCellValue event  in DxDataGrid e.g. like in this method:

 onSetitemtypeLocal(rowData: any, value: any): void
{
this.defaultSetCellValue(rowData, value);
} 

where this.defaultSetCellValue(rowData, value) will update the grid value within the "this" context.

If I need to do other work, for example accessing the Angular component where the method is located, I need to re-bind the method to the component's execution context in the component constructor:

this.onSetitemtypeLocal = this.onSetitemtypeLocal.bind(this);

Doing that, however, alters the execution context, so that I can no longer call the "this.defaultSetCellValue(rowData, value);" method as it's not present in the context.

It might be simple, but how can I combine the two contexts allowing me to call the this.defaultSetCellValue method as well as accessing the component's elements via the this operator ?

**Comment by GoshaFighten** [comment]
You don't need to call the `defaultSetCellValue` method. You can assign the passed `value` to the corresponding column field or the passed `rowData` object:

``` TypeScript
onSetitemtypeLocal(rowData: any, value: any): void
{
    rowData.MyColumn = value;
}
```

This is what the `defaultSetCellValue` method does. If this does not work for you, provide me with a sample project to reproduce the issue.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
