### ISSUE TITLE
dxForm throws the E1035 error in an Angular app which is built using the Angular CLI with the Production mode when the form has an item with dxTextArea

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-angular#580]
See the [TestApp.zip](https://github.com/DevExpress/devextreme-angular/files/1383191/TestApp.zip) project.

Steps to reproduce: 

1. Open up the attached project.
2. Execute the following commands:
```
npm install
ng build --prod
```

3. Deploy the app to any web server
4. Open the app in a web browser and see the browser console.

**Comment by dxvladislavvolkov** [comment]
To use the dxTextArea widget on the form, you need to import it into your application.
I've created a corresponding ticket in our Support Center to correct our documentation

**Comment by NickMitrokhin** [comment]
Ok, thanks.

Adding the following code to the **app.module.ts** file solves the issue:
```ts
import {
  ..., DxTextAreaModule
} from 'devextreme-angular';
@NgModule({
  ...
  imports: [
    ...,
    DxTextAreaModule
  ],
  ...
})
```
