### ISSUE TITLE
Updating dxi-toolbar-item options binding causes dx-scroll-view to scroll to top

### ISSUE THREAD

**Issue by jaggedaz** [DevExpress/devextreme-angular#581]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 17.1
    devextreme-angular version: 17.1
- Specify the type of the issue (check one with "x"): 
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

See the [plunk example](https://plnkr.co/edit/exolwpndlzr2emwoFJzl?p=preview).  Steps to reproduce:

1. Scroll to the bottom of the pop-up.
2. Click the "Enable submit" button.

Observed behavior: scroll view scrolls to top.
Expected behavior: scroll does not move.

**Comment by GoshaFighten** [comment]
I've managed to reproduce this behavior if I use the jQuery approach to create our widgets. So, I've created a corresponding ticket in our Support Center to research this behavior. See the [Updating dxPopup toolbarItem options causes dxScrollView inside the popup content to scroll to top](https://www.devexpress.com/Support/Center/Question/Details/T567915) issue.
