### ISSUE TITLE
dx textbox join error

### ISSUE THREAD

**Issue by christophedemey** [DevExpress/devextreme-angular#582]
Hi

When i use this :
  <dx-text-box ([value])="treeViewFilterString" [valueChangeEvent]="keyup">
    </dx-text-box>

i get this error :
![dxerror](https://user-images.githubusercontent.com/13153164/31650888-b1b5077c-b319-11e7-803e-813bdd511c00.PNG)

It has to do with the valueChangeEvent property, when i removed it, the error is gone, when i replace it with something like [visible]="false" no error and the control is hidden.

Thanks.

**Comment by christophedemey** [comment]
When i changed it to variables it seems to work.
in my ts :
    public modeValue: string = "search";
    public changeValue: string = "keyup";

in html :
  <dx-text-box [mode]="modeValue"
               ([value])="treeViewFilterString"
               [valueChangeEvent]="changeValue">

Just the value binding does not seem to work at this point.
Can i not declare these values inline (search, keyup) ?

Thanks.

**Comment by christophedemey** [comment]
Ok, also found it, dont bind values if you want it inline, i had [mode]="keyup" but it was supposed to be mode="keyup" for inline setting of the property.

Thanks.

**Comment by GoshaFighten** [comment]
Yes, @christophedemey . You are correct. You should not use square brackets to bind a string option. See [Static String Option Value](https://github.com/DevExpress/devextreme-angular#static-option) topic. Or, if you use them, wrap the bound value in additional single quotes:
 
``` HTML
[valueChangeEvent]="'keyup'"
```
