### ISSUE TITLE
Poor performance of SelectBox (in-memory array)

### ISSUE THREAD

**Issue by Marfusios** [DevExpress/devextreme-angular#590]
Hello,

right now we are struggling with select box performance. 
Initial render (after the first click) for 100+ items takes longer than expected, and for 1000+ it's unusable. 
As I read somewhere else for a large number of items, a search should be enabled. So I did it and then strange behavior happens - if there is preselected item, then it is slow and searching is not applied. 

Example: [plunker](http://plnkr.co/edit/jAdb6I1pe9cByrtS0116?p=preview)

Did we miss something or is it really not usable in real world applications?

**Comment by GoshaFighten** [comment]
Wrap your array into our [DataSource](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/) instance and enable its [paginate](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/DataSource/Configuration/#paginate) option to improve the performance. See the updated [plunk](http://plnkr.co/edit/ksv4w56QzSsULRnCpH1C?p=preview).

``` TypeScript
import DataSource from 'devextreme/data/data_source';

@Component({
  selector: 'my2-selectbox',
  template: `<div class="dx-field">
  <div class="dx-field-label">{{label}}</div>
  <div class="dx-field-value">
    <dx-select-box
      [dataSource]="source"
    ></dx-select-box>
  </div>
</div>`
})
export class My2SelectBoxComponent implements OnInit {
  flookupItems: [];
  source: DataSource;
  @Input()
  get lookupItems(): [] { return this.flookupItems; }
  set lookupItems(value: []) {
    this.flookupItems = value;
    this.source = new DataSource({
      store: {
        data: this.flookupItems,
        type: 'array'
      },
      paginate: true
    }) 
  }
}
```
