### ISSUE TITLE
dx-form Changing readonly state of @ runtime generated fields

### ISSUE THREAD

**Issue by christophedemey** [DevExpress/devextreme-angular#591]
Hi

I have read the docs and cannot understand how to do this.
I have 3 dx-forms which are being generated with an *ngFor.
I need to set some fields to readonly.
So i found a property customizeItem (why not an event?) which i can use, so i bound it to a function.
This is my html for form.
      <dx-form [formData]="configuration.configuration"
                 (onFieldDataChanged)="onFieldDataChangedHandler($event)"
                 [customizeItem]="onCustomizeItemHandler">
        </dx-form>

This is my .ts code.
    public onCustomizeItemHandler(item: any) :void {
        alert("cust time!");
    }

The function gets called but i cannot do any modification to that object that is passed.
How can i change the readonly of the fields that are being passed into onCustomizeItemHandler as a parameter.

This is the result from debug :
![customizeitem](https://user-images.githubusercontent.com/13153164/31884385-314f7648-b7ed-11e7-92f7-af18ffd20b62.png)

Thanks!

**Comment by GoshaFighten** [comment]
Why can't you do this? You should be able to do this like the following:

``` TypeScript
customizeItem(item) {
    item.editorOptions = item.editorOptions || {};
    item.editorOptions.disabled = true;
}
```

**Comment by christophedemey** [comment]
Ooooh i did not realize i had to append properties to the object, was this in the docs ?
It works, nice, thanks!

**Comment by GoshaFighten** [comment]
You are welcome! You can change any option a form item has in this function. If an option is not defined, define it.

**Comment by aravindfz** [comment]
We need a strict typing across DevExtreme angular.
That's why we use typescript. Any release plans going on?
