### ISSUE TITLE
Problem generating production/release build with webpack 2

### ISSUE THREAD

**Issue by albrookesplowman** [DevExpress/devextreme-angular#600]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    "devextreme": "^17.1.7",
    "devextreme-angular": "^17.1.7",

- Specify the type of the issue (check one with "x"): 
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

I have incorporated devextreme into the populate JavaScriptServices template and it is successful in development mode.  I am now trying to run the **dotnet public -c Release** command to generate the files which are needed for publishing and I am getting the following errors:

ERROR in ./$$_gendir/~/devextreme-angular/ui/popup.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\popup.ngfactory.ts Unexpected token (26:35)
      You may need an appropriate loader to handle this file type.
      | import * as i15 from 'devextreme-angular/core/iterable-differ-helper';
      | import * as i16 from 'devextreme-angular/core/nested-option';
      | export const DxPopupModuleNgFactory:i0.NgModuleFactory<i1.DxPopupModule> = i0.╔Ácmf(i1.DxPopupModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/termsconditions/termsconditions.component.ngfactory.ts 9:0-98
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/toolbar-item-dxi.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\toolbar-item-dxi.ngfactory.ts Unexpected token (13:42)
      You may need an appropriate loader to handle this file type.
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | import * as i3 from 'devextreme-angular/core/template-host';
      | export const DxiToolbarItemModuleNgFactory:i0.NgModuleFactory<i1.DxiToolbarItemModule> = i0.╔Ácmf(i1.DxiToolbarItemModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/termsconditions/termsconditions.component.ngfactory.ts 15:0-116
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/data-grid.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\data-grid.ngfactory.ts Unexpected token (63:38)
      You may need an appropriate loader to handle this file type.
      | import * as i52 from 'devextreme-angular/core/iterable-differ-helper';
      | import * as i53 from 'devextreme-angular/core/nested-option';
      | export const DxDataGridModuleNgFactory:i0.NgModuleFactory<i1.DxDataGridModule> = i0.╔Ácmf(i1.DxDataGridModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 8:0-102
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/selection.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\selection.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/selection';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoSelectionModuleNgFactory:i0.NgModuleFactory<i1.DxoSelectionModule> = i0.╔Ácmf(i1.DxoSelectionModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 14:0-109
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/column-fixing.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\column-fixing.ngfactory.ts Unexpected token (12:43)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/column-fixing';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoColumnFixingModuleNgFactory:i0.NgModuleFactory<i1.DxoColumnFixingModule> = i0.╔Ácmf(i1.DxoColumnFixingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 16:0-113
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/paging.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\paging.ngfactory.ts Unexpected token (12:37)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/paging';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoPagingModuleNgFactory:i0.NgModuleFactory<i1.DxoPagingModule> = i0.╔Ácmf(i1.DxoPagingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 18:0-107
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/pager.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\pager.ngfactory.ts Unexpected token (12:36)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/pager';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoPagerModuleNgFactory:i0.NgModuleFactory<i1.DxoPagerModule> = i0.╔Ácmf(i1.DxoPagerModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 20:0-106
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/editing.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\editing.ngfactory.ts Unexpected token (12:38)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/editing';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoEditingModuleNgFactory:i0.NgModuleFactory<i1.DxoEditingModule> = i0.╔Ácmf(i1.DxoEditingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 22:0-108
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/search-panel.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\search-panel.ngfactory.ts Unexpected token (12:42)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/search-panel';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoSearchPanelModuleNgFactory:i0.NgModuleFactory<i1.DxoSearchPanelModule> = i0.╔Ácmf(i1.DxoSearchPanelModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 24:0-113
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/group-panel.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\group-panel.ngfactory.ts Unexpected token (12:41)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/group-panel';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoGroupPanelModuleNgFactory:i0.NgModuleFactory<i1.DxoGroupPanelModule> = i0.╔Ácmf(i1.DxoGroupPanelModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 26:0-112
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/filter-row.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\filter-row.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/filter-row';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoFilterRowModuleNgFactory:i0.NgModuleFactory<i1.DxoFilterRowModule> = i0.╔Ácmf(i1.DxoFilterRowModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 28:0-111
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/header-filter.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\header-filter.ngfactory.ts Unexpected token (12:43)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/header-filter';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoHeaderFilterModuleNgFactory:i0.NgModuleFactory<i1.DxoHeaderFilterModule> = i0.╔Ácmf(i1.DxoHeaderFilterModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 30:0-114
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/scrolling.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\scrolling.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/scrolling';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoScrollingModuleNgFactory:i0.NgModuleFactory<i1.DxoScrollingModule> = i0.╔Ácmf(i1.DxoScrollingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 32:0-110
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/column-dxi.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\column-dxi.ngfactory.ts Unexpected token (12:37)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/column-dxi';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxiColumnModuleNgFactory:i0.NgModuleFactory<i1.DxiColumnModule> = i0.╔Ácmf(i1.DxiColumnModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 34:0-111
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/button.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\button.ngfactory.ts Unexpected token (15:36)
      You may need an appropriate loader to handle this file type.
      | import * as i4 from 'devextreme-angular/core/watcher-helper';
      | import * as i5 from 'devextreme-angular/core/nested-option';
      | export const DxButtonModuleNgFactory:i0.NgModuleFactory<i1.DxButtonModule> = i0.╔Ácmf(i1.DxButtonModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 8:0-99
       @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
       @ ./ClientApp/boot.browser.ts
  Child
      Hash: 0505529d7c1bdd237313
      Time: 82819ms
               Asset     Size  Chunks                    Chunk Names
      main-server.js  26.1 MB       0  [emitted]  [big]  main-server

      ERROR in ./$$_gendir/~/devextreme-angular/ui/popup.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\popup.ngfactory.ts Unexpected token (26:35)
      You may need an appropriate loader to handle this file type.
      | import * as i15 from 'devextreme-angular/core/iterable-differ-helper';
      | import * as i16 from 'devextreme-angular/core/nested-option';
      | export const DxPopupModuleNgFactory:i0.NgModuleFactory<i1.DxPopupModule> = i0.╔Ácmf(i1.DxPopupModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/termsconditions/termsconditions.component.ngfactory.ts 9:0-98
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/toolbar-item-dxi.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\toolbar-item-dxi.ngfactory.ts Unexpected token (13:42)
      You may need an appropriate loader to handle this file type.
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | import * as i3 from 'devextreme-angular/core/template-host';
      | export const DxiToolbarItemModuleNgFactory:i0.NgModuleFactory<i1.DxiToolbarItemModule> = i0.╔Ácmf(i1.DxiToolbarItemModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/termsconditions/termsconditions.component.ngfactory.ts 15:0-116
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/data-grid.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\data-grid.ngfactory.ts Unexpected token (63:38)
      You may need an appropriate loader to handle this file type.
      | import * as i52 from 'devextreme-angular/core/iterable-differ-helper';
      | import * as i53 from 'devextreme-angular/core/nested-option';
      | export const DxDataGridModuleNgFactory:i0.NgModuleFactory<i1.DxDataGridModule> = i0.╔Ácmf(i1.DxDataGridModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 8:0-102
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/selection.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\selection.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/selection';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoSelectionModuleNgFactory:i0.NgModuleFactory<i1.DxoSelectionModule> = i0.╔Ácmf(i1.DxoSelectionModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 14:0-109
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/column-fixing.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\column-fixing.ngfactory.ts Unexpected token (12:43)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/column-fixing';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoColumnFixingModuleNgFactory:i0.NgModuleFactory<i1.DxoColumnFixingModule> = i0.╔Ácmf(i1.DxoColumnFixingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 16:0-113
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/paging.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\paging.ngfactory.ts Unexpected token (12:37)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/paging';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoPagingModuleNgFactory:i0.NgModuleFactory<i1.DxoPagingModule> = i0.╔Ácmf(i1.DxoPagingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 18:0-107
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/pager.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\pager.ngfactory.ts Unexpected token (12:36)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/pager';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoPagerModuleNgFactory:i0.NgModuleFactory<i1.DxoPagerModule> = i0.╔Ácmf(i1.DxoPagerModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 20:0-106
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/editing.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\editing.ngfactory.ts Unexpected token (12:38)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/editing';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoEditingModuleNgFactory:i0.NgModuleFactory<i1.DxoEditingModule> = i0.╔Ácmf(i1.DxoEditingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 22:0-108
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/search-panel.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\search-panel.ngfactory.ts Unexpected token (12:42)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/search-panel';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoSearchPanelModuleNgFactory:i0.NgModuleFactory<i1.DxoSearchPanelModule> = i0.╔Ácmf(i1.DxoSearchPanelModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 24:0-113
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/group-panel.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\group-panel.ngfactory.ts Unexpected token (12:41)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/group-panel';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoGroupPanelModuleNgFactory:i0.NgModuleFactory<i1.DxoGroupPanelModule> = i0.╔Ácmf(i1.DxoGroupPanelModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 26:0-112
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/filter-row.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\filter-row.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/filter-row';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoFilterRowModuleNgFactory:i0.NgModuleFactory<i1.DxoFilterRowModule> = i0.╔Ácmf(i1.DxoFilterRowModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 28:0-111
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/header-filter.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\header-filter.ngfactory.ts Unexpected token (12:43)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/header-filter';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoHeaderFilterModuleNgFactory:i0.NgModuleFactory<i1.DxoHeaderFilterModule> = i0.╔Ácmf(i1.DxoHeaderFilterModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 30:0-114
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/scrolling.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\scrolling.ngfactory.ts Unexpected token (12:40)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/scrolling';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxoScrollingModuleNgFactory:i0.NgModuleFactory<i1.DxoScrollingModule> = i0.╔Ácmf(i1.DxoScrollingModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 32:0-110
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/nested/column-dxi.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\nested\column-dxi.ngfactory.ts Unexpected token (12:37)
      You may need an appropriate loader to handle this file type.
      | import * as i1 from 'devextreme-angular/ui/nested/column-dxi';
      | import * as i2 from 'devextreme-angular/core/nested-option';
      | export const DxiColumnModuleNgFactory:i0.NgModuleFactory<i1.DxiColumnModule> = i0.╔Ácmf(i1.DxiColumnModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/fleetlist/fleetlist.component.ngfactory.ts 34:0-111
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts

      ERROR in ./$$_gendir/~/devextreme-angular/ui/button.ngfactory.ts
      Module parse failed: E:\Sources\pt-riskPOC5\$$_gendir\node_modules\devextreme-angular\ui\button.ngfactory.ts Unexpected token (15:36)
      You may need an appropriate loader to handle this file type.
      | import * as i4 from 'devextreme-angular/core/watcher-helper';
      | import * as i5 from 'devextreme-angular/core/nested-option';
      | export const DxButtonModuleNgFactory:i0.NgModuleFactory<i1.DxButtonModule> = i0.╔Ácmf(i1.DxButtonModule,
      |     ([] as any[]),(_l:any) => {
      |       return i0.╔Ámod([i0.╔Ámpd(512,i0.ComponentFactoryResolver,i0.╔ÁCodegenComponentFactoryResolver,
       @ ./$$_gendir/ClientApp/app/components/home/home.component.ngfactory.ts 8:0-99
       @ ./$$_gendir/ClientApp/app/app.module.server.ngfactory.ts
       @ ./ClientApp/boot.server.ts
E:\Sources\pt-riskPOC5\pt-riskPOC5.csproj(59,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.

**Comment by GoshaFighten** [comment]
This is the same issue as #534. The ASP.NET Core Angular template causes it.
