### ISSUE TITLE
How to use routerLink in dx-tree-view node in Angular?

### ISSUE THREAD

**Issue by Severanin** [DevExpress/devextreme-angular#601]
Hello!
How to use routerLink in dx-tree-view node in Angular?
Thank you.

**Comment by GoshaFighten** [comment]
Use dxTreeView's [item template](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxTreeView/Configuration/#itemTemplate). Check out [my project](https://github.com/GoshaFighten/dx-ngx-application/blob/master/src/app/app.component.html) where this is implemented in dxToolbar.
