### ISSUE TITLE
enum

### ISSUE THREAD

**Issue by m-patel** [DevExpress/devextreme-angular#603]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    
    devexteme version: 
    devextreme-angular version: 
- Specify the type of the issue (check one with "x"): 
[ ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by GoshaFighten** [comment]
What do you mean, @m-patel ?
