### ISSUE TITLE
Question: Localization with angular-l10n?

### ISSUE THREAD

**Issue by k-vekos** [DevExpress/devextreme-angular#606]
I see that there is an example to use devextreme with angular and Globalize [here](https://github.com/DevExpress/devextreme-examples/tree/17_1/webpack-angular-globalize) and I wanted to know if it was possible to do the same thing but replacing Globalize with [angular-l10n](https://github.com/robisim74/angular-l10n/) instead?

~~I can provide localized data to the dx controls but I don't know how to provide localized texts to the dx controls and at the very least I would need to be able to do that with angular-l10n.~~

**EDIT:** Actually I would need full data localization similar to how DX and Globalize work because I can't provide localized data when the user is using an input control such as a calendar control.

Thanks!

**Comment by GoshaFighten** [comment]
We have built-in support only for Intl and Globalize localization. I have no experience with `angular-i18n`. But, based on [Angular i18n solutions](https://github.com/robisim74/angular-l10n/#angular-i18n-solutions), I see that this library provides directives and pipes for localization as `ngx-translate` does using Intl. I successfully use `ngx-translate` along with [our Intl localization](https://github.com/DevExpress/DevExtreme-Intl) in [my Angular project](https://github.com/GoshaFighten/dx-ngx-application). I believe you can go the same way. If you are still unable to localize certain of our strings, provide me with a sample project to illustrate the issue.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by k-vekos** [comment]
What I am trying to do is to be able to localize data-driven DevExtreme controls such as a Select Box. For example:
```
<dx-select-box
                [dataSource]="options"
                displayExpr="text"
                valueExpr="value"
                [(value)]="selectedItem"
            ></dx-select-box>
```

In this case I would need to populate `options` in my Angular component. With `angular-l10n` I can either use the directives and pipes as you said or I can access the `TranslationService` Angular Service from my Angular Component. This creates a lot of boilerplate and duplicate code across my components.

What would be great is if I could do something like this:

```
<dx-select-box
                [dataSource]="options"
                displayExpr="translateCollection"
                [(value)]="selectedItem"
            ></dx-select-box>
```

And then `translateCollection()` would return an `Observable<string>` or something, but there are two problems I can see:

1. `displayExpr` can't handle `Observable` objects as far as I can tell.
2. I need to send the value to the `TranslationService` of angular-l10n but `displayExpr` is evaluated out of the scope of my angular component. So this won't work.

Is there a way to get this nicer behavior or a workaround? Thanks.

**Comment by k-vekos** [comment]
@GoshaFighten could you please Re-Open this issue? Thanks!

**Comment by GoshaFighten** [comment]
@k-vekos , would you please provide me with a sample project to reproduce the issue? At the moment, I see that you bind the `displayExpr` option to a function. In this case, you need to wrap the option name in square brackets so that Angular binding works.

**Comment by k-vekos** [comment]
@GoshaFighten I tried wrapping `displayExpr` in square brackets and now it is successfully calling my function. However there is a new problem. It seems like my `displayExpr` function is only being called when I expand the dropdown control on my column here and so the cell display values are not passed into the `displayExpr` function.

```
<dx-data-grid [dataSource]="schedules">
    <dxi-column dataField="type">
        <dxo-lookup [dataSource]="scheduleTypeOptions" [displayExpr]="localize"></dxo-lookup>
    </dxi-column>
</dx-data-grid>
```

As a result you can see that the display value is different in the cell than it is in the filter:

![image](https://user-images.githubusercontent.com/23462254/35121064-2ff6bef4-fc68-11e7-88c9-2dd55b639eb3.png)

**Comment by k-vekos** [comment]
I found a solution: adding `valueExpr="this"` to the `dxo-lookup` fixes the issue. This may be a bug then.

**Comment by GoshaFighten** [comment]
@k-vekos , at the moment, I'm not quite sure how to reproduce the issue on my side so that I can give you a precise answer on whether this is the correct behavior or not. Would you please provide me with a sample project that reproduces the issue so that I can better understand your scenario?

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive.
