### ISSUE TITLE
Components property and method definitions don't match documentation

### ISSUE THREAD

**Issue by acutexyz** [DevExpress/devextreme-angular#611]
Consider this example:
```typescript
// myComponent.ts

import { DxListComponent } from 'devextreme-angular';

myList: DxListComponent;

...

handleOnInitialized(e: any) {
  myList = e.component;
  myList.unselectAll(); // <--- [ts] Property 'unselectAll' does not exist on type 'DxListComponent';
}
```

Although the function is there and it works, the typescript is not able to find it in the `DxListComponent`.

**Comment by acutexyz** [comment]
Any comments on this?

**Comment by GoshaFighten** [comment]
The `e.component` parameter is not an instance of our *Angular* DxListComponent. It's an instance of our underlying [dxList widget](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxList/). So, your casting is incorrect. Use `any` as the `myList` variable type.

``` TypeScript
myList: any;
handleOnInitialized(e: any) {
    this.myList = e.component;
    this.myList.unselectAll();
}
```

**Comment by acutexyz** [comment]
@GoshaFighten I think this should be labeled as a bug, not question. 
In the link that you provided the Angular example uses `dx-list` component and we import `DxListComponent` to use it; in the docs it has `unselectAll` method, the `e.component` also has that method, but all of a sudden the `DxListComponent` does not. 
I understand that it is just a wrapper around underlying component, but then still 1) the documentation is misleading and 2) it defeats the purpose of having Angular components in the first place.
