### ISSUE TITLE
Use dx-vector-map

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#615]
Hi,

I'm trying to use the **dx-import-map** widget but I cant figure out how to load the datasource.
Following the Demo code I use this import:
`import * as mapsData from 'vectormap-data/world.js';`

But Angular can't find `vectormap-data/world.js` and throws this error at compile time:

`ERROR in src/app/app.component.ts(2,27): error TS2307: Cannot find module 'vectormap-data/world.js'.`

Is there a workaround?

OS: MacOs 10.12.6
angular/cli: 1.2.3
node: 6.11.0
devextreme 17.1.8

**Comment by GoshaFighten** [comment]
You need to import it from `devextreme/dist/js/vectormap-data/world.js`. If you take a look at the `config.js` file in the [Colors Customization](https://js.devexpress.com/Demos/WidgetsGallery/Demo/VectorMap/ColorsCustomization/Angular/Light/) demo, you will see that we provided mapping from `vectormap-data` to `npm:devextreme@17.2/dist/js/vectormap-data`. I've attached an Angular project made using Angular CLI to illustrate this.
[GH615.zip](https://github.com/DevExpress/devextreme-angular/files/1489200/GH615.zip)
