### ISSUE TITLE
DataGrid Master-Detail: Updating datasource item content from master should not redraw details from scratch

### ISSUE THREAD

**Issue by wartab** [DevExpress/devextreme-angular#629]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.3
    devextreme-angular version: 17.2.3
- Specify the type of the issue (check one with "x"):
[ x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Code to reproduce the issue (can't provide Punker, because the provided one is broken since NG5).
https://github.com/wartab/devextreme-masterdetail-bug

We are encountering an issue within master-details of DataGrids. If data can be modified within a parent grid, doing so will result in redrawing all child datagrids (even those that are not children of the updated parent row). This procedure will first show a very small datagrid that eventually expands to its actual high. This behavior is undesirable as it causes flickering as soon as some data is updated.

Table rows should probably not be removed when the backing objects haven't been removed in the datasource.

Demo of the issue: http://wartab.be/devextreme-bug/
Can be noticed the best when using the checkboxes

**Comment by GoshaFighten** [comment]
I see that this issue is reproducible without Angular as well. Let continue discussing it in the [The grid re-renders the entire master-detail layout if a cell value is changed](https://www.devexpress.com/Support/Center/Question/Details/T583586) ticket.

**Comment by wartab** [comment]
Sorry about posting that here then. I'm going to do that then.
