### ISSUE TITLE
Multiple dxTemplate with dx-tree-view or dx-tree-list and dx-drop-down-box 

### ISSUE THREAD

**Issue by AlexOliinyk1** [DevExpress/devextreme-angular#630]
Hi all,
![mqijgq9rstei0azlaeftmg](https://user-images.githubusercontent.com/10448723/33213863-1d0b76ce-d132-11e7-9864-3f2abfcd722f.png)

I'm trying to build something  like in the attachments,  this data structure looks like this:

First level should be like list with check box but should be expanded, I think for it better use tree-list or tree-view, then second level should be dropdown it will be like groupe for elements, and then under dropdown should be tree-view 

-list 
  -dropdown 
    -treeview 

data will be used from structure like 
 - for list datasource "layers"
    - for dropdown  datasource "layers.items"
       - for treeview datasource "layers.items.items" and so on.
 
![image](https://user-images.githubusercontent.com/10448723/33213966-89bf75e0-d132-11e7-85c5-b769579ed69a.png)

Main problem how it to implement 

I trying something like this but without successes  
  
![image](https://user-images.githubusercontent.com/10448723/33213915-4d219af0-d132-11e7-84ad-f46e9b5a72b8.png)

I think my main problem, I don't understand how work with *dxTemplate or maybe I should implement it at all in other way...

Thanks

**Comment by GoshaFighten** [comment]
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](www.devexpress.com/ask). There, you will get your question answered in a short time frame.
