### ISSUE TITLE
The "Expression has changed after it was checked" error is thrown if dxDataGrid options are changed in the onContentReady event handler when the grid resides in a template

### ISSUE THREAD

**Issue by NickMitrokhin** [DevExpress/devextreme-angular#631]
Can be reproduced with [this](http://plnkr.co/edit/IopNl6QWs5pfQfcpGxca?p=preview) example. See the browser console.

**Comment by dxvladislavvolkov** [comment]
The onContentReady event fires when a widget is rendered. DevExtreme components are rendered at the AfterViewInit stage of the Angular lifecycle. At this stage, the model should not be changed. That is why the error is thrown. A possible solution is to wrap the code that changes component options in a timeout as shown below:
`
onContentReady(e: any) {
    setTimeout(() => {
        if (!e.component.__gridContentLoaded) {
            e.component.__gridContentLoaded =true;
            this.allowUpdating = true     
        }  
    });
}
`
