### ISSUE TITLE
DxSelectBox Two-Way-Databinding Bug

### ISSUE THREAD

**Issue by strpipe** [DevExpress/devextreme-angular#632]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2
    devextreme-angular version: 17.2
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

Plunker:
-  https://plnkr.co/edit/EWXAeRGdAq7fek7QWQ6J?p=preview

I am not sure that it will be saved. So I link the .zip file cotaining the demo here too.
-  [DxSelectBoxChainedTwoWayBinding.zip](https://github.com/DevExpress/devextreme-angular/files/1522029/DxSelectBoxChainedTwoWayBinding.zip)

I did strip the DXSelectBox demo down and added a property in the .component file which the select boxes bind to. They both bind to the same property and do not update correctly all of the time. 

The steps to reproduce are in the plunker.

**Comment by GoshaFighten** [comment]
This issue is fixed in version 17.2.4. Check out your plunk now. It does not reproduce the issue. See the [screencast](http://take.ms/HLxUN).
