### ISSUE TITLE
How to get value from calculateCellValue and use it in cellTemplate simultanoeusly ?

### ISSUE THREAD

**Issue by pankajsri03** [DevExpress/devextreme-angular#641]
I have a column named "status" which returns values in caps and I am converting it to lower case in component  using  calculateCellValue method as below:
<dxi-column dataField="operationalStatus" caption="Operational Status" cellTemplate="cellTemplate" [calculateCellValue]="calculateCellValue"></dxi-column>

calculateCellValue(data){
    if(data.operationalStatus){
    return data.operationalStatus.toLowerCase();
    }
  }
I need to render status values as icons. My icons are lower case namely -error, warning.
I am rendering the value as icons using cellTemplate as below:

<div  *dxTemplate="let data of 'cellTemplate'">
        <mat-icon svgIcon="extraIcons:{{data.value}}" aria-label="{{data.value}}"></mat-icon>
</div>

The issue here is that this portion of div gets rendered in dom before i get the computed value in lower case from calculateCellValue and the data.value results in undefined.

    devexteme version:17.2.3
    devextreme-angular version: 17.2.3
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[x ] support inquiry

**Comment by GoshaFighten** [comment]
Please submit this issue to our [support center](www.devexpress.com/ask) along with a sample project to reproduce the issue. We will research this behavior.
