### ISSUE TITLE
DxTagBoxComponent not calling searchExprChange event

### ISSUE THREAD

**Issue by ppozeti** [DevExpress/devextreme-angular#644]
Hi,

I'm trying to implement a search while typing kind of service, using the DxTagBoxComponent.
The problem I'm facing is that searchExprChange event is not being called while I'm typing. Although other event like onInput is called, it does not have the value I'm typing.
So to me this is a bug, as we have an exposed event but it doesn't work as expected.

Version I'm using:
    "devextreme": "17.2.3",
    "devextreme-angular": "17.2.3"

[ X ] bug Report 
To reproduce: http://plnkr.co/edit/7RQCwQfuzbBpTqcWP1lq?p=preview

**Comment by GoshaFighten** [comment]
The searchExpr option is a field in your data source against which a search should be performed. You don't change it when you type something in dxTagBox. Please post this issue to our [support center](www.devexpress.com/ask) and elaborate on what you need to achieve.
