### ISSUE TITLE
Toast is not visible by-default

### ISSUE THREAD

**Issue by mohdsiddique** [DevExpress/devextreme-angular#647]
Issue: toast is not visible 
devexteme version: 17.2.4
devextreme-angular version: 17.2.4

I added below snap in my component.html file 
`    <dx-toast message="This is a sample" type="info">
    </dx-toast>
`
but toast is not visible. I tried to set visible="true" still no luck.

Could you please let me know How to show toast without calling x.instance.show()

**Comment by GoshaFighten** [comment]
This should work. See the [plunk](http://plnkr.co/edit/uaDvOz9ixNS60NItgiMX?p=preview). Would you please modify it to  reproduce the issue?

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
