### ISSUE TITLE
dx-box item template [shrink] does not work

### ISSUE THREAD

**Issue by alert83** [DevExpress/devextreme-angular#648]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by GoshaFighten** [comment]
It's not clear to me how I can reproduce the issue on my side. Please provide me with a sample project that reproduces the issue.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
