### ISSUE TITLE
dx-file-uploader allow to upload only pdf & doc type

### ISSUE THREAD

**Issue by lakhank143** [DevExpress/devextreme-angular#650]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version:
    devextreme-angular version:
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[ ] support inquiry 

hello i am using dx-file-uploader control in my project. i want to upload only specific file type e.g pdf,doc,docx . how can i restrict the file type to be upload before it upload. if file type doesn't matches it should display error message.

thank you

**Comment by GoshaFighten** [comment]
You can use the [accept](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileUploader/Configuration/#accept) option to allow a user to select files only of the required type. If this option does not meet your requirements, please post a corresponding question to our [support center](www.devexpress.com/ask).
