### ISSUE TITLE
dx-tab-panel and ngIf

### ISSUE THREAD

**Issue by genusP** [DevExpress/devextreme-angular#654]
If tab added by condition in selected tab broke content
https://plnkr.co/edit/kboDYausEPVfDV8nJdtD?p=preview
Check Show Tab2 in options pane

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by ovchinnikov** [comment]
Hello,

If your item template contains some nested components, declare it using the parameterless dxTemplate structural directive as follows:

```html
<dx-tab-panel>
    <dxi-item>
        <div *dxTemplate>
             <label>Textbox:</label>
             <dx-text-box></dx-text-box>
        </div>
    </dxi-item>
</dx-tab-panel>
```

**Comment by genusP** [comment]
It is work. Thanks.
