### ISSUE TITLE
dx-slider tooltip odd behavior when it is initialized within a display: none container

### ISSUE THREAD

**Issue by Jelledb** [DevExpress/devextreme-angular#662]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.3
    devextreme-angular version: 17.2.3
- Specify the type of the issue (check one with "x"):
[ x ] bug Report 

![image](https://user-images.githubusercontent.com/14248574/34479630-329a3996-efa8-11e7-87e4-9fff0a1beb1b.png)

See the image. The tooltip of the first dx-slider looks weird and sometimes even dissapears. The 'RangeParameterComponent1' dx-slider has been initialized before it got visible. It is inside a container that had display: none at the time of initialization. The RangeParameterComponent2 has been initialized after the container got visible.

**Comment by Jelledb** [comment]
I've managed to reproduce this on plnkr by the way: http://plnkr.co/edit/9ehZCDAV4HtZQHPSHeeE?p=preview

**Comment by ovchinnikov** [comment]
Hello,
To show a tooltip in the initially hidden element, you need to call the dxSlider.repaint method forcibly when showing this element. For example: http://plnkr.co/edit/QoTv6gJpXIcTul3hqLsk?p=preview

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
