### ISSUE TITLE
Material theme for the components

### ISSUE THREAD

**Issue by acutexyz** [DevExpress/devextreme-angular#663]
Hi, this is a feature request. Do you have any plans on implementing Material theme for the main desktop components?

**Comment by hakimio** [comment]
If you choose Android theme, you'll get something similar to material:
https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/Overview/Angular/Android/

**Comment by GoshaFighten** [comment]
We do have plans to support Material themes in our components. At the moment, you can use our Android theme that resembles Material themes as @hakimio suggested.
