### ISSUE TITLE
dx-tag-box filtered selection

### ISSUE THREAD

**Issue by selcukkutuk** [DevExpress/devextreme-angular#664]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: **17.2.4**
    devextreme-angular version: **17.2.4**
- Specify the type of the issue (check one with "x"):
[**x**] bug Report 
[ ] feature request 
[ ] support inquiry 

**1.** If one item remains after filtering, all items are selected when the selection is made.
**2.** If filtering is done and then selected and canceled again, all the data in the list will not be listed.

**UPDATE 1**
When the remaining items after filtering are selected, the select all method is executed. This method brings all items to the selected state. But only the filtered items had to be selected.
![Image of Yaktocat](https://i.imgur.com/rI0JvJc.png)

**Comment by hakimio** [comment]
Related pull request:
https://github.com/DevExpress/DevExtreme/pull/2405

**Comment by GoshaFighten** [comment]
To be sure that you are experiencing the same issue as discussed in the [https://github.com/DevExpress/DevExtreme/pull/2405](https://github.com/DevExpress/DevExtreme/pull/2405) PR, would you please provide me with a sample project to reproduce it so that I can give you a precise answer?

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.

**Comment by hakimio** [comment]
Well the fix pull request was merged, so i guess it should land in devextreme-angular sometime soon as well...

**Comment by GoshaFighten** [comment]
You can try our devextreme unstable version. You need to use devextreme@17.2.6-pre-18030.
