### ISSUE TITLE
Can not change height of DxList on ContentReady event

### ISSUE THREAD

**Issue by Yura13** [DevExpress/devextreme-angular#665]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[x] bug Report 

When trying change height of list on ContentReady event, I have the next error:
TypeError: Cannot read property 'option' of undefined

Example:
<dx-list ... (onContentReady)="onListReady()"></dx-list>

onListReady(): void {
   this.list.instance.option('height', window.innerHeight - 205);
}

This solution works for DxDataGridComponent, but doesn't work for DxListComponent.

**Comment by ovchinnikov** [comment]
Hello,
You can obtain a widget instance from arguments of the onContentReady event. For example: https://stackblitz.com/edit/angular-4dvuco?file=app%2Fapp.component.ts

**Comment by Yura13** [comment]
Thanks, it helps.
