### ISSUE TITLE
dxDateBox - is it possible to disable the validation?

### ISSUE THREAD

**Issue by experionakash** [DevExpress/devextreme-angular#666]
Is it possible to remove the validation done by DevExtream?
I need to show the validation message in my own style.
![capture45](https://user-images.githubusercontent.com/23092972/34775590-be16a6c0-f639-11e7-97f3-7dd3e17dbd53.PNG)

**Comment by GoshaFighten** [comment]
I suggest you set the [invalidDateMessage](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDateBox/Configuration/#invalidDateMessage) to an empty string. If this solution does not meet your requirements, please open a new [Support Center](https://www.devexpress.com/Support/Center/Question/Create) ticket that describes your scenario in greater detail.
