### ISSUE TITLE
Infinite Recursion in DxDateBox

### ISSUE THREAD

**Issue by steveschmitt** [DevExpress/devextreme-angular#671]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devextreme version: 17.2.4
    devextreme-angular version: 17.2.4
- Specify the type of the issue (check one with "x"):
[X] bug Report 
[ ] feature request 
[ ] support inquiry 

There's a bug in `ui.calendar.js`, in the `_moveCurrentDate` function.  It is possible to go into infinite recursion if most dates are disabled, as the function keeps calling itself until it finds a date that is not disabled.  In our case, all dates in the future are disabled, so attempts to click into the future can cause the error.  This _could_ be prevented by checking the `min` and `max` values of the DxDateBox, but the function does not check these values before recursing.

**Comment by GoshaFighten** [comment]
This issue is closed because of being inactive. If you need further assistance, leave a comment here.
