### ISSUE TITLE
dx-number-box max value is not working with formatting

### ISSUE THREAD

**Issue by skoczylm** [DevExpress/devextreme-angular#672]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
    devextreme-intl: 17.2.4

- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

![formatting-not-working-with-max-value](https://user-images.githubusercontent.com/1774283/35289936-0f959f9a-0069-11e8-87a4-aab42081bacc.gif)

**Comment by cescxu0712** [comment]
yes,i found this problem too.

**Comment by GoshaFighten** [comment]
This issue was fixed in DevExtreme of version 17.2.5.
