### ISSUE TITLE
dx-number-box Does not lock input for locale('pl') - and print changed value

### ISSUE THREAD

**Issue by skoczylm** [DevExpress/devextreme-angular#673]
devexteme version: 17.2.4
    devextreme-angular version: 17.2.4
    devextreme-intl: 17.2.4

[x] bug Report 
[ ] feature request 
[ ] support inquiry

dx-number-box with format="#,##0.00"

Input 1 from keybord until control starts to change digits.

![formatting-locale-pl-cannot-lock-max-input](https://user-images.githubusercontent.com/1774283/35290369-58946c70-006a-11e8-81a8-49465eee6f1e.gif)

**Comment by GoshaFighten** [comment]
Yes, I see this issue. But, I can reproduce it without Angular. So, I've created a ticket in our Support Center. See [T601350](https://www.devexpress.com/Support/Center/Question/Details/T601350).
