### ISSUE TITLE
ui.dialog.confirm() and ui.dialog.notify() jQuery error with Webpack2

### ISSUE THREAD

**Issue by toralux** [DevExpress/devextreme-angular#675]
Webpack2 and DevExtreme dialog-bug with example to reproduce attached.

    devexteme version: 17.2.4
    devextreme-angular version: 17.2.4 (but have failed in every version for a year)

- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

### Steps to Reproduce:

1. unzip DevExtreme_Error-reproduce.zip
2. npm install -g webpack-dev-server
3. npm install
4. webpack-dev-server --config config/webpack.prod.js --watch

### Results You Received:

After clicking test Test-button ui.dialog.confirm() is called and resulting with the following error:

> ERROR TypeError: Cannot read property 'jQuery3310043683433871879452' of undefined

(or some other random number behind jQuery)

The same problem happens with ui.dialog.notify() ...

I have fixed this by using other component for dialogs, e.g. regular javascript alert() (but since confirm() is used in dxDataGrid when deleting this makes lot of extra work bypassing the error when using devextreme-angular)

### Results You Expected:

Expected DevExtreme confirm() and notify() to work without error.
A ugly fix is to comment two lines (4 and 24) in app.module.ts ...
* import { HomeModule } from './home/home.module'; // <--- comment this line and it will work
* HomeModule, // <--- comment this line and it will work

and let the HomeModule only be referenced by Angular Router such way ...
```
const routes: Routes = [
    // Lazy async modules
    {
        path: '',
        loadChildren: './home/home.module#HomeModule'
    }
];
```
### Environment Details:

Angular.io (Angular 4 or 5)
JQuery
Webpack2

[DevExtreme_Error-reproduce.zip](https://github.com/DevExpress/devextreme-angular/files/1664355/DevExtreme_Error-reproduce.zip)

**Comment by GoshaFighten** [comment]
Hi @toralux 
 
For some reason, the method that sets the container for our overlays is not executed. This [line](https://github.com/DevExpress/DevExtreme/blob/17_2/js/core/utils/view_port.js#L26) is not executed. We will research this issue. At the moment, I suggest you call it manually in the AboutComponent constructor:
 
``` TypeScript
import { value } from 'devextreme/core/utils/view_port'
 
constructor(
) {
value(document.body);
}
```
 
Also note that you will need to add an ambient module declaration for it.
 
``` TypeScript
interface ViewPort {
value(value: any): void
}
declare module "devextreme/core/utils/view_port" {
const value: ViewPort;
export = value;
}
```

**Comment by toralux** [comment]
Thanks for quick reply and providing a hotfix, I will try it out and hopefully you find a permanent solution in some future version of DevExtreme as well :)

**Comment by toralux** [comment]
The fix worked very well for me, thanks :)

**Comment by GoshaFighten** [comment]
@toralux 
When researching this issue, we found that it relates to the zone.js version you are using. There is a bug in version 0.8.13 of zone.js that causes it to skip raising certain events. See the [Drop-down popup windows and submenus are displayed incorrectly in Angular CLI](https://www.devexpress.com/Support/Center/Question/Details/T535321) ticket. Upgrade the zone.js version to resolve the issue.
