### ISSUE TITLE
dxForm properties binding work wrong

### ISSUE THREAD

**Issue by TigranOtaryan** [DevExpress/devextreme-angular#677]
devexteme version: 17.2.4
devextreme-angular version: 17.2.4

For example if I bind formData property in OneWay mode " [ ] " it's work like twoWay binding.

Please look to my Plunker Example Code https://plnkr.co/edit/odqqqCZ11HBPJzXbxa1S?p=preview .  

formData is binded in one way mode but when I change the field it affect to the input out of the dxForm

**Comment by GoshaFighten** [comment]
Yes, the Form component does not create a new formData instance. It changes fields of the existing formData instance. So, Angular tracks these changes. What problems do you have with this?

**Comment by TigranOtaryan** [comment]
"[ ]" it is one way binding not two way like "[( )]" so angular should not track that change that is the problem

**Comment by GoshaFighten** [comment]
I did try this with a custom Angular component and it behaves in the same way. See the [plunk](https://plnkr.co/edit/2CBiqLQpQ9813k142gdh?p=preview). If our Form re-created the formData instance like:

``` TypeScript
change() {
  this.formData = {
    Name: "New"
  }
}
```

it would work as you are expecting. But, it doesn't. The Form modifies fields of the existing formData instance. For your scenario, I can only suggest you use different objects for the Form and your span. See the [plunk](https://plnkr.co/edit/4ZBTZNp4KId0H53a3auw?p=preview).

**Comment by TigranOtaryan** [comment]
Finally I see what you mean. I was very confusing because you waiting another behavior.  I agree with you solution but in my case it will make code ugly, I was thinking that by using Angular one-way and two-way binding I can just use one object.
Thanks for answer.
