### ISSUE TITLE
dx-file-uploader does not supported angular http interceptors

### ISSUE THREAD

**Issue by inyutin-maxim** [DevExpress/devextreme-angular#678]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version:
    devextreme-angular version:
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

dx-file-uploader does not supported angular http interceptor

**Comment by GoshaFighten** [comment]
Yes, the DxFileUploader component does not use the Angular Http provider to send requests. As a result, your http interceptor is not called. What are you doing in your interceptor with requests? I believe there is another way to achieve this for our DxFileUploader component.

**Comment by inyutin-maxim** [comment]
Of course it is possible to transfer to a component in titles a token, but us does not arrange to track it everywhere. We rewrote this functionality without use the dx-file-uploader components

**Comment by GoshaFighten** [comment]
@inyutin-maxim 
As far as I understand, you found a solution and this issue can be closed. Am I correct?

**Comment by inyutin-maxim** [comment]
@GoshaFighten  You are right, but it could be a good feature

**Comment by joachim-bl** [comment]
I also have an issue with this. With the angular httpClient i can set the {withCredentials:true} property through the headers object. I do this for all my calls in an interceptor. But for the upload request from dx-files-upload this is not set and I didn´t find a way to set thes property of the XMLHttpRequest through your api?

**Comment by ChrisMarais** [comment]
I am having the same problem I have tried to bind to the property on the control

html
[uploadHeaders]="uploadHeaders"

ts
  uploadHeaders = { withCredentials: true };

This does not appear to work. Could you please advise how to enable the file up load control to pass credentials.

It would be useful if you had a withcredentials property on the control that could be set to true when needed.

regards
Chris
