### ISSUE TITLE
No way to "find" cancel button within editing popup mode

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#679]
I can't figure out a way to trigger an event on the cancel onclick() of a popup editing window.

The reason for the the event is that onEditingStart I set editing to false on a certain column (primary key)

`  onEditingStart(e) {
    var grid = e.component;
    grid.beginUpdate();
    grid.columnOption("contractcode", "allowEditing", false);
    grid.endUpdate();
  }`

I've tried logging the events of onCellPrepared and onContentReady and no where in the cellElement is there ".dx-link-cancel"

I understand when using row editing the below works onCellPrepared

`    if (e.rowType === "data" && e.column.command === "edit") {
      var isEditing = e.row.isEditing
        // $links = e.cellElement.find(".dx-link");
      if (isEditing) {
        // $links.filter(".dx-link-cancel").on("click", function (args) { console.log("cancel_clicked"); });
      }
    }`

Is this adaptable for popup editing?

**Comment by GoshaFighten** [comment]
As far as I understand, you need to disable a particular cell editor based on your condition. If so, you are doing this in a wrong way. You need to use the onEditorPreparing event like this:

``` TypeScript
onEditorPreparing(e) {
  if (e.parentType === "dataRow" && e.dataField === "FirstName" && e.row.data.Prefix === "Mr.") {
    e.editorOptions.disabled = true;
  }
}
```

See the [plunk](https://plnkr.co/edit/U1857OT28ewuJ44absuZ?p=preview) that illustrates this. If this is not what you are looking for, open a new [support center](www.devexpress.com/ask) ticket and describe your scenario in greater detail.

**Comment by gwsampso** [comment]
Thank you.

onEditorPreparing was indeed the event NOT onEditingStart

I ended up using the below to enable/disable.

When editing the value would NOT be blank and edits are disabled

When inserting the value would be blank and therefore enabled.

    onEditorPreparing(e) {

      if (e.parentType === "dataRow" && e.dataField === "FirstName" && e.editorOptions.value !== "") {
        e.editorOptions.disabled = true;
      }
      if (e.parentType === "dataRow" && e.dataField === "FirstName" && e.editorOptions.value === "") {
        e.editorOptions.disabled = false;
      }
    }
