### ISSUE TITLE
Datagrid not propertly rendered when composing dxi-column with dx-drop-down-box

### ISSUE THREAD

**Issue by Frederico-Mesquita** [DevExpress/devextreme-angular#681]
I can insert a dropBox into a datagrid´s column composing layers of templates as containers but when edition is executed datagrid´s column not propertly render. In first rendering the component works very fine. When I need edit the row, the collection provided as a value to columns datafield is rendered before dropbox component takes place, printing [object],[object], ..., [object] into the column.

Bellow, an ilustration of the code used:

    <dxi-column caption="some caption" dataField="collection" cellTemplate="collCellTemplate"></dxi-column>
    <div *dxTemplate="let item of 'collCellTemplate'">
            <dx-drop-down-box 
                [dataSource]="item.value" 
                [value]="som value">
                <div *dxTemplate="let contentData of 'content'">
                    <dx-list
                        [dataSource] = "item.value"
                        keyExpr="id"
                        text = "name"
                        showSelectionControls = "true"
                        selectionMode="multiple"
                        (onSelectionChanged)="someEvent($event)"
                        itemTemplate="items">
                        <div *dxTemplate="let i of 'items'"><b>{{i.name}}</b></div>
                    </dx-list>
                </div>
            </dx-drop-down-box>
    </div>

![image](https://user-images.githubusercontent.com/30448037/35621469-867a600c-066b-11e8-86ef-8421743a894c.png)
![sem titulo](https://user-images.githubusercontent.com/30448037/35621496-a020e576-066b-11e8-84fd-27396c660adc.png)

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version:
    devextreme-angular version:
- Specify the type of the issue (check one with "x"):
[ x] bug Report 
[ ] feature request 
[ ] support inquiry

**Comment by GoshaFighten** [comment]
Set the DropDownBox [displayExpr](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDropDownBox/Configuration/#displayExpr) option to "name". If this still does not work, open a new [Support Center ticket](www.devexpress.com/ask) with a sample project to reproduce the issue.
