### ISSUE TITLE
[iOS] Unable to open DxTagBox on focus

### ISSUE THREAD

**Issue by KouglofKabyle** [DevExpress/devextreme-angular#685]
> This is a :
> [x] bug Report : iOS Safari (iPad / iPhone)
> [ ] feature request
> [ ] support inquiry
> 
> Using : 
> devexteme version: 17.2.5
> devextreme-angular version: 17.2.5

Hi guys,

I am leaving a comment here to notify that [this problem](https://www.devexpress.com/Support/Center/Question/Details/T400944/dxtagbox-it-is-difficult-to-set-focus-when-the-searchenabled-option-is-set-to-true-on-ios) seems to have reappeared.

We cannot open the uncustomized DxTagBox on focus, it only works when tapping the icon. Even when the list shows up, no element can be selected on focus.

This is reproducible on your demos pages (as for the 06/02/2018).

Sorry for the ticket duplication, and thanks in advance for your help

**Comment by GoshaFighten** [comment]
@KouglofKabyle 
Let's continue discussing this issue in the [T400944](https://www.devexpress.com/Support/Center/Question/Details/T400944) ticket.
