### ISSUE TITLE
2D array datasource in charts

### ISSUE THREAD

**Issue by gldraphael** [DevExpress/devextreme-angular#691]
Using a 2D array as a chart dataSource doesn't seem to be supported as of now because I see this error: 

> E2001 - Invalid data source. See:
[http://js.devexpress.com/error/17_2/E2001](http://js.devexpress.com/error/17_2/E2001)

**Usecase:** I'm trying to display cluster data in a scatter chart. It makes sense to represent each cluster as an array and the dataset as an array of clusters, which gives me a 2D array.

```js
data: SampleVM[][]
```

```html
<dx-chart
    [dataSource]="data">
    <dxi-series *ngFor="let d of data" 
                 argumentField="d.male" valueField="d.female">
    </dxi-series>

    <!-- Everything else follows -->
</dx-chart>
```

Could we have support for 2D arrays please?

---

**Version Info**
```
devexteme version: 17.2.5
devextreme-angular version: 17.2.5
```

**Type of Issue**
[ ] Bug Report
[x] Feature Request
[ ] support inquiry

**Comment by GoshaFighten** [comment]
No, our charts don't support 2D arrays. I suggest you open a new [support center ticket](www.devexpress.com/ask) and describe in great detail why you need to use such arrays.
