### ISSUE TITLE
Use Angular pipe with 'calculateCellValue'

### ISSUE THREAD

**Issue by k-vekos** [DevExpress/devextreme-angular#693]
devexteme version: 17.2.5
devextreme-angular version: 17.2.5

[x] feature request

In my Angular component template I have a dxDataGrid with a column defined like so:

    <dxi-column dataField="schedule" [calculateCellValue]=""></dxi-column>

What I would like to be able to do is bind 'calculateCellValue' such that it passes the value to an Angular Pipe. If my value was defined as a component property it would have been done like so:

    {{ value | myCustomPipe }}

Ideally I would be able to do something like this:

    [calculateCellValue]="columnData | myCustomPipe"

**Comment by GoshaFighten** [comment]
I've replayed to you regarding this question in your [dxDataGrid - Use Angular pipe with 'calculateCellValue'?](https://www.devexpress.com/Support/Center/Question/Details/T607300) ticket. Check out my answer.
