### ISSUE TITLE
Error! Can't resolve icons/dxicons.woff

### ISSUE THREAD

**Issue by M90K7** [DevExpress/devextreme-angular#696]
HELLO.

When i create `ng new ExamDevex` ...
and next time add `npm install --save devextreme devextreme-angular`
then [Configuring Angular CLI](https://github.com/DevExpress/devextreme-angular/blob/master/docs/using-angular-cli.md#configuration)

I'll deal with this error:
````
D:\Document\Projects\Angular\NgDevex>ng build
Date: 2018-02-23T19:05:56.791Z
Hash: 3d7ff31342cc77600f0c
Time: 27659ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 3.89 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 6.94 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 203 kB [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 583 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 12.9 MB [initial] [rendered]

ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/devextreme/dist/css/dx.light.css
(Emitted value instead of an instance of Error) CssSyntaxError: D:\Document\Projects\Angular\NgDevex\node_modules\devextreme\dist\css\dx.light.css:3219:12: Can't resolve 'icons/dxicons.woff)%20format(%27woff%27),%20url(icons/dxicons.ttf)%20format(%27truetype%27' in 'D:\Document\Projects\Angular\NgDevex\node_modules\devextreme\dist\css'

  3217 | @font-face {
  3218 |   font-family: 'DXIcons';
> 3219 |   src: url(icons/dxicons.woff) format('woff'), url(icons/dxicons.ttf) format('truetype');
       |            ^
  3220 |   font-weight: normal;
  3221 |   font-style: normal;
````
How resolve this error?

**When edit the `/node_modules/devextreme/dist/css/dx.light.css` file and change the url of font inside quotation this error is resolved.**
`
@font-face {
  font-family: 'DXIcons';
  src: url('icons/dxicons.woff') format('woff'), url('icons/dxicons.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}`

Do you have any idea?
Add quotation  to the url while standard of the CSS has true ???

thanks

**Comment by Brandinga** [comment]
Hello,

this is a bug in angular-cli 1.7.1 --> 1.7.0 is working
[see here](https://github.com/angular/angular-cli/pull/9738)

**Comment by GoshaFighten** [comment]
Yes, this is an Angular CLI bug. See https://github.com/DevExpress/DevExtreme/issues/3061 and https://github.com/angular/angular-cli/issues/9726.
