### ISSUE TITLE
Example for file uploader inside dxForm

### ISSUE THREAD

**Issue by kodermax** [DevExpress/devextreme-angular#697]
Could you please provide example for dxFileUploader to next code?
https://embed.plnkr.co/?show=preview

**Comment by GoshaFighten** [comment]
Your sample is empty. You need to place the FileUploader component in the Form item template. Please refer to the [dxForm - How to define an item template in Angular](https://www.devexpress.com/Support/Center/Question/Details/T460000) ticket where we discussed how to use an item template for the Form widget in Angular apps. Use the same approach in your scenario. If you wish to update the [formData ](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxForm/Configuration/#formData) option when a file is selected, do this in the [FileUploader.onValueChanged](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxFileUploader/Configuration/#onValueChanged) event handler.
