### ISSUE TITLE
DxTagbox not clear typing text after selection the item

### ISSUE THREAD

**Issue by Yura13** [DevExpress/devextreme-angular#700]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version: 17.2.5
    devextreme-angular version: 17.2.5
- Specify the type of the issue (check one with "x"):
[x] bug Report

DxTagbox doesn't clear typing text after selection the item. Its cleared after click outside of the field. This issue reproduced when showSelectionControls=true.

![image](https://user-images.githubusercontent.com/17030431/36893161-ac1f58d8-1e0f-11e8-96d7-40364d7142f7.png)

**Comment by GoshaFighten** [comment]
I can reproduce this issue without Angular. So, I've created a ticket in our Support Center. See [TagBox does not clear the search text after selecting an item](https://www.devexpress.com/Support/Center/Question/Details/T612546).

**Comment by Yura13** [comment]
Thanks!

**Comment by anikets43** [comment]
Hello @GoshaFighten Is this issue resolved?
