### ISSUE TITLE
changes from 17.2.x to 18.x

### ISSUE THREAD

**Issue by SpiraMira** [DevExpress/devextreme-angular#701]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version:
    devextreme-angular version:
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[ ] support inquiry 

Are there release notes for 18.x yet? Would love to play with it ...

**Comment by hakimio** [comment]
You can see release notes in the following page:
https://github.com/DevExpress/DevExtreme/releases

**Comment by SpiraMira** [comment]
Thank you. I was looking at devextreme-angular and not seeing release-notes there for 17.2.6 etc.  

When will devextreme-angular 17.2.6 be out?  

I think devextreme and devextreme-angular should always be paired - right? 

Where can I find notes one bootstrap 4 support ?

Thanks.

**Comment by hakimio** [comment]
> The DevExtreme team is currently working on updating the DevExtreme themes and the ThemeBuilder tool to support Bootstrap 4. Therefore, you'll see official DevExtreme support for Bootstrap 4 in the upcoming v18.1 major release.

https://community.devexpress.com/blogs/aspnet/archive/2018/01/26/bootstrap-4-support-v17-2-5.aspx

**Comment by SpiraMira** [comment]
Cool.  When will 18.1 be released?  Is the 18.1 beta good enough to test?  My project is b4 based ...

Thx again.

**Comment by hakimio** [comment]
I would expect a stable release around beginning of June or end of May.

**Comment by SpiraMira** [comment]
Excellent. Thx!
