### ISSUE TITLE
Change detection runs far to often (dxDataGrid)

### ISSUE THREAD

**Issue by MarioGruda** [DevExpress/devextreme-angular#702]
devexteme version: 18.1.1 beta
    devextreme-angular version: 18.1.1 beta
- Specify the type of the issue (check one with "x"):
[x ] bug Report 

It looks like the dxDataGrid is subscribing to an onmouseover event (maybe other or further events) within the angular zone. This causes the angular Changedetector to run far too often.

Here is a small example: https://stackblitz.com/edit/angular-o6xaio

best regards

**Comment by ovchinnikov** [comment]
After additional testing, we found regression in the existing code. We reverted these changes and will make an update here once we find a more efficient solution.

**Comment by SanderElias** [comment]
I'm seeing the same behaviour, plus an overly eager calling off all helper functions. I opened up #839 for this. The excessive calling off helpers is on top of this.

**Comment by LexDX** [comment]
After thorough research, we came to the conclusion that it is not possible to change the current behavior without rewriting a big part of our DevExtreme package. Such a huge change can affect a lot of our existing customers and break their projects. We are unable to introduce such changes in minor versions without thorough testing. So, we will consider enhancing the current behavior in future versions of our library but I can't provide you with any ETA.
