### ISSUE TITLE
DataGrid- swap 2 rows content

### ISSUE THREAD

**Issue by arwindgao** [DevExpress/devextreme-angular#706]
I need swap two rows content in DataGrid
My current solution is swap values of DataGrid data source (Array), it's works but page rendering is very slow(2000 lines, 20 columns). 
Version info: devextreme & devextreme-angular 17.1.7
Is there a better solution? Thanks in advanced.

**Comment by GoshaFighten** [comment]
I see that you asked this question in the T612737 ticket in our Support Center. Let's discuss it there. But, the ticket is private. If you wish to allow other people to see it, we can make it public.
