### ISSUE TITLE
DxMap in dynamic mode is just grey (no map shows)

### ISSUE THREAD

**Issue by jakehockey10** [DevExpress/devextreme-angular#709]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: latest
    devextreme-angular version: latest
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

https://js.devexpress.com/Demos/WidgetsGallery/Demo/Map/ProvidersAndTypes/Angular/Light/

The dynamic map is just grey both on my site and on the demo page above.  I don't see any errors in the console in either case.  What's going on?

**Comment by San4es** [comment]
@jakehockey10 

It is a DevExtreme known issue. See [this ticket](https://www.devexpress.com/Support/Center/Question/Details/T612644/map-a-map-is-not-loaded-if-the-google-provider-is-used) for more details.
