### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by kodermax** [DevExpress/devextreme-angular#714]
```   
 "devextreme": "^18.1.1-pre-18064",
    "devextreme-angular": "18.1.1-beta.2"
 "@angular/cli": "v6.0.0-beta.5"
```
When i run 
```
ng build --target=production
```
I have this error when i open page.
![image](https://user-images.githubusercontent.com/590985/37424751-4a2da266-27d2-11e8-81f7-fbc2f99ce1a3.png)
![image](https://user-images.githubusercontent.com/590985/37424770-564741e2-27d2-11e8-9f65-3f63462d3565.png)

**Comment by ovchinnikov** [comment]
Hello,
I suggest you update `@angular/cli` to the latest version. If this does not help, open a new [Support Center ](https://www.devexpress.com/Support/Center/Question/Create)ticket with a sample project to reproduce the issue.
