### ISSUE TITLE
Visual studio code autocomplete

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/devextreme-angular#715]
Is there the chance to create vs code snippets for the devextreme Angular version?

**Comment by hakimio** [comment]
What exactly do you want to auto-generate with the snippets?

**Comment by Franki1986** [comment]
I mean some kind of intellisense or autocomplete.

**Comment by hakimio** [comment]
That's different from snippets.
Do you want to auto-complete devextreme tags and their properties (ie "dx-button") or Typescript code?

**Comment by Franki1986** [comment]
Yes exactly, I will change the title.

**Comment by hakimio** [comment]
For tag auto-generation you can try the following:
https://marketplace.visualstudio.com/items?itemName=asafari72.devextremesnippet

Typescript auto-completion and type checking should work if you just import the right classes and use them.

**Comment by Franki1986** [comment]
Yes I have seen this on the marketplace, but it is only a little part, the more important like grid is missing.

**Comment by hakimio** [comment]
I would highly recommend to try some of JetBrains IDEs. Jetbrains WebStorm, PhpStorm and Rider have the best support for Angular projects from all the IDEs I have tried yet. Not only great static code analysis (template and controller) but also perfect auto-completion of all things angular including all DevExtreme tags.

**Comment by hakimio** [comment]
https://blog.jetbrains.com/webstorm/2016/04/angular-2-workflow-in-webstorm

**Comment by Franki1986** [comment]
I will give Jetbrains Rider a try and report.

**Comment by Franki1986** [comment]
Rider works very well for auto complete! Furthermore I like the combination of fast and slim VS-Code and powerfull VS 2017..
