### ISSUE TITLE
Use UpperCasePipe When Editing Datagrid in Popup Mode

### ISSUE THREAD

**Issue by kentsitugbc** [DevExpress/devextreme-angular#716]
devexteme version: 17.2.3
    devextreme-angular version: 17.2.3
- Specify the type of the issue (check one with "x"):
[x] support inquiry 
I there any way I can use UpperCasePipe for the column data, so I can convert the input data into all uppercase automatically in popup edit form?

**Comment by ovchinnikov** [comment]
Hello,
You can use the [customizeText](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/columns/#customizeText) method to achieve the required behavior. If this solution does not meet your requirements, please open a new [Support Center](https://www.devexpress.com/Support/Center/Question/Create) ticket that describes your scenario in greater detail.
