### ISSUE TITLE
How to customize the order of the header in dx-pivot-grid?

### ISSUE THREAD

**Issue by Flourad** [DevExpress/devextreme-angular#730]
not inc or decs order by the amount,
order by your own definition~

**Comment by ovchinnikov** [comment]
Hello, 
You can use the [sortingMethod](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/PivotGridDataSource/Configuration/fields/#sortingMethod) to achieve the required behavior. If this solution does not meet your requirements, please open a new [Support Center](https://www.devexpress.com/Support/Center/Question/Create) ticket that describes your scenario in greater detail.

**Comment by Flourad** [comment]
@ovchinnikov thank you so much, it helps me to solve my problem~
