### ISSUE TITLE
Custom Store LoadOptions - accessing searchExpr

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#738]
How do we access searchExpr within our LoadOptions?

![image](https://user-images.githubusercontent.com/19770122/38292754-37fbaec4-3828-11e8-9793-ffc27eae5bbc.png)

If I add a dxo-search-panel to my grid and start typing the filter option is populated rather than the expected "searchExpr"

![image](https://user-images.githubusercontent.com/19770122/38292827-83da0e3a-3828-11e8-98ed-7f2530089870.png)

Here is my demo plnkr with a CRUD service which is trying to use remote operations to search
https://plnkr.co/edit/JMTfJWLsz7pHzauhnAoM?p=preview

**Comment by GoshaFighten** [comment]
This questions relates to how our DevExtreme DataGrid works. So, the appropriate place to ask it is to use our [support center](www.devexpress.com/ask).

The grid does not use the searchExpr, searchOperation, searchValue load options. Our editors like SelectBox uses them. The grid performs searching and filtering using the loadOptions filter parameter as described in the [Widgets -> DataGrid -> Data Binding -> Custom Sources -> Load Data](https://js.devexpress.com/Documentation/18_1/Guide/Widgets/DataGrid/Data_Binding/Custom_Sources/#Load_Data) help topic. So, you need to use this parameter on your server or convert it to another parameter that your server understands before sending your request in the CustomStore load method. If you have further questions, feel free to ask them in our Support Center.
