### ISSUE TITLE
DevExtreme Grid onEditorPreparing & onCellPrepared 17.2 can no longer identify cell changes

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#741]
devexteme version: 17.2.7
devextreme-angular version: 17.2.7
[X ] bug Report 

In version 16.2 we were able to us a combination of onEditorPreparing & onCellPrepared to identify when a cell within the grid had changed values.
https://embed.plnkr.co/GwgBD1Mp8XF5oLZoYt4k/

In version 17.2 this no longer works
https://embed.plnkr.co/eHoyfi/

Please advise

**Comment by gwsampso** [comment]
in 17.2  combination of  (onEditorPreparing) & (onRowUpdating) can be used

example 
(onEditorPreparing)= "EditCell($event) (onRowUpdating)="onRowUpdating($event)" 

```
    EditCell(e) {
        this.start = 0;
        this.end = 0;
        this.keyDataField = e.dataField;
        this.start = e.value;
    }
```

```
   onRowUpdating(value) {
    this.changeinvalue = value.newData[this.keyDataField] - this.start; 
        }

```

**Comment by GoshaFighten** [comment]
After research, we found that fixing the [T555797](https://www.devexpress.com/Support/Center/Question/Details/T555797) bug causes this behavior. Now, the onEditorPreparing event is raised again before a cell editor is closed. For your scenario, I suggest you use the onEditingStart event instead. See the [plunk](https://plnkr.co/edit/jJ5lwdxDkEOmhSTDmWyZ?p=info) that illustrates this.

If you have further questions in this regard, please open a [Support Center ticket](www.devexpress.com/ask) for it.
