### ISSUE TITLE
[NoDataText] is showing nothing

### ISSUE THREAD

**Issue by JacopoSciampi** [DevExpress/devextreme-angular#753]
devexteme version: 17.2.7
    devextreme-angular version: 17.2.7

[x ] bug Report

This is my snap : 

```
<dx-data-grid [dataSource]="items" [columns]="['activityTitle', 'activityStartDate', 'activityEndDate']" [noDataText]="Test"></dx-data-grid>
```

But when I load the component, instead of the text "Test" I just see no text. If I don't put the [NoDataText] attr it shows "No Data". 

Am I missing something or what? I just wanted to have a custom text when there is no data to display.

**Comment by ovchinnikov** [comment]
I recommend that you refer to the following thread where a similar inquiry was discussed: [When to use square brackets [ ] in directives @Inputs and when not?](https://stackoverflow.com/questions/43633452/when-to-use-square-brackets-in-directives-inputs-and-when-not)
