### ISSUE TITLE
[databox] navigation buttons disabled on a small date range

### ISSUE THREAD

**Issue by dylanvansteen** [DevExpress/devextreme-angular#754]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.5
    devextreme-angular version: 17.2.5
- Specify the type of the issue (check one with "x"):
[ x] bug Report 
[ ] feature request 
[ ] support inquiry 

When i set a small min and max range on the dxdatebox the navigation buttons are disabled but i can still click the month name and go to the next month to select a date. If i do that the navigation buttons will become active.

plunker for example date
http://plnkr.co/edit/57VGQMgGYLiyaeqk7cMG?p=preview

**Comment by ovchinnikov** [comment]
It looks like this issue is not related to the Angular integration. I have created a corresponding ticket [T629064](https://www.devexpress.com/Support/Center/Question/Details/T629064/dxdatebox-navigation-buttons-should-be-disabled-for-a-small-date-range) in our Support Center.
