### ISSUE TITLE
dxSelectBox - Selected item doesn't appear in the popup list

### ISSUE THREAD

**Issue by andrii-oleksyshyn** [DevExpress/devextreme-angular#759]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.7
    devextreme-angular version: 17.2.7
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

**Prerequisites:**
- big list of items (that you need to scroll to see the last one)
- search enabled

**Steps to reproduce:**
1. Click on dropdown, see the list of items appears.
2. Type something (e.g. IP) for search.
3. Select the item, the popup with list closes.
4. When you click on dropdown and popup opens you can see that the list is not scrolled to the selected item and is rendered from the top.
5. Close the dropdown and open it again and see that the item is in focus now.

**Expected:**
After opening dropdown for the first time the list should be scrolled so the selected item is shown.

**Reproduction:**
Plunker: http://plnkr.co/edit/5nmFtrZTL0yhf3B1MIT7?p=preview
Gif:
![selected_item_focus_issue](https://user-images.githubusercontent.com/1427132/38926998-123e8a90-430d-11e8-97c0-a72e857137cc.gif)

**Comment by mrjohn0011** [comment]
Hello. Thank you for a report. I have created a [ticket in the Devextreme Support Center](https://www.devexpress.com/Support/Center/Question/Details/T629578/). Please subscribe to it to be notified when this issue is fixed.

**Comment by Yura13** [comment]
Hello, currently this issue still reproduced in 18.1.6 and 17.2.10
Repo: https://codesandbox.io/s/71z526xzy0
![select-box](https://user-images.githubusercontent.com/17030431/45879992-2acffb80-bdaf-11e8-9584-70c66f76178e.gif)
