### ISSUE TITLE
How to set as chart-bar color a linear gradient (from bottom to top)

### ISSUE THREAD

**Issue by EdoardoLenzi9** [DevExpress/devextreme-angular#763]
version: 
 devextreme@17.2.7
 devextreme-angular@17.2.7
[X] feature request 
[X] support

I need to set the background color of a chart-bar with a linear gradient.
Actualy I use a <dx-chart> with a  <dxi-series> and a <dxo-legend> 

The result must be something like [this](https://user-images.githubusercontent.com/31968677/39179643-113d607e-47b5-11e8-9cc1-efe4b07f8a05.png):
![Example](https://user-images.githubusercontent.com/31968677/39179643-113d607e-47b5-11e8-9cc1-efe4b07f8a05.png)

**Comment by ovchinnikov** [comment]
Hello,

Currently, dxChart does not support gradient bars. We will consider improving this functionality in future versions.

**Comment by vermashailesh** [comment]
Any update on this.
