### ISSUE TITLE
Circular gauge label

### ISSUE THREAD

**Issue by EdoardoLenzi9** [DevExpress/devextreme-angular#766]
version:
devextreme@17.2.7
devextreme-angular@17.2.7
browser: Chrome last version
[X] feature request
[X] support

I need to hide the circular gauge labels, I'm trying to set the tickInterval bigger than the endValue but the 0 label still remaining
![5](https://user-images.githubusercontent.com/31968677/39293330-e5643ace-4938-11e8-8ffd-d7bbe9f7751e.png)
![6](https://user-images.githubusercontent.com/31968677/39293337-e7553e1e-4938-11e8-84af-1a4095c74532.png)

# Gauge code
```html
<dx-circular-gauge id="gauge" [value]="settings.value">
	<dxo-scale [startValue]="settings.minValue" [endValue]="settings.maxValue" [minorTickInterval]="settings.minValue" [tickInterval]="settings.interval">
		<dxo-label [useRangeColors]="true"></dxo-label>
	</dxo-scale>
	<dxo-range-container palette="pastel">
		<dxi-range [startValue]="settings.minValue" [endValue]="minMiddleValue" color="#92000A"></dxi-range>
		<dxi-range [startValue]="minMiddleValue" [endValue]="maxMiddleValue" color="#E6E200"></dxi-range>
		<dxi-range [startValue]="maxMiddleValue" [endValue]="settings.maxValue" color="#77DD77"></dxi-range>
	</dxo-range-container>
	<dxo-title [text]="settings.title | translate">
		<dxo-font [size]="12"></dxo-font>
	</dxo-title>
</dx-circular-gauge>
```

**Comment by ovchinnikov** [comment]
Hi,
Set the [label.visible](https://js.devexpress.com/Documentation/ApiReference/Data_Visualization_Widgets/dxBarGauge/Configuration/label/#visible) option to false to hide a label. If this solution does not meet your requirements, please open a new [Support Center](https://www.devexpress.com/Support/Center/Question/Create) ticket that describes your scenario in greater detail.
