### ISSUE TITLE
dxSelectBox, dxTagBox - When searching for non-existing value popup with 'No data to display' blinks and hides

### ISSUE THREAD

**Issue by andrii-oleksyshyn** [DevExpress/devextreme-angular#772]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.7
    devextreme-angular version: 17.2.7
- Specify the type of the issue (check one with "x"):
[ x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Prerequisites:
- list of items
- search enabled

Steps to reproduce:

- Click on dropdown, see the list of items appears.
- Type something that doesn't match with list items (e.g. qqqq) for search.
- See the popup with 'No data to display' appears and immediately disappears, sometimes it's even impossible to read the wording.

Expected:
When the popup with 'No data to display' appears it shouldn't immediately disappear. Or ideally it should be configurable.

Reproduction:
Plunker: http://plnkr.co/edit/5mkoG2v7zV2eprmDbbJh?p=preview

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. This behavior is not Angular-specific and is implemented at the widget level. Currently, there is no built-in option to customize it. As a workaround, you can manually re-open dxSelectBox in the onOptionChanged handler as in the following example - http://plnkr.co/edit/haitPklypz2g1npvdtX0?p=preview
 
We have plans to add a similar option in the future

P.S. This forum is mainly for issues related to our Angular integration package. For common questions about widgets, I kindly ask you to use either our [DevExtreme GitHub page](https://github.com/DevExpress/devextreme/issues) or the [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
