### ISSUE TITLE
DevExtreme components used in several modules

### ISSUE THREAD

**Issue by jakehockey10** [DevExpress/devextreme-angular#781]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 17.2.7
    devextreme-angular version: 17.2.7
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[x] support inquiry 

I am trying to follow best practice for Angular applications and separate my code out into app, core, shared, and <feature> modules.  I'm using components from DevExtreme in my core module as well as in my app module.  What is the recommended way to import the `DevExtremeModule` in this scenario?  I would expect that I would NOT want to import it twice, but I can't seem to find the right place to import it and what to export if I have to to get this to work.  Would I want to import it in my core module and then export the components I use throughout the application?  I found this difficult because I ended up having to dig through and find the right import paths for things like the `DxValidationRuleComponent`.

Any help is much appreciated!

**Comment by jakehockey10** [comment]
Ah, I think I might understand...

I can import the `DevExtremeModule` in my `SharedModule`.  I can also export the `DevExtremeModule` from the `SharedModule`.  Now any module, whether it be core, app, or a feature module, I can import `SharedModule` and it looks like that seems to work.

Do you see any issues with this?  This seems to be the right way to do it from what I do understand.

**Comment by GoshaFighten** [comment]
Yes, this is a recommended Angular approach to share a module across all of your application as described in the [SharedModule](https://angular.io/guide/ngmodule-faq#sharedmodule) Angular help topic. So, use this approach in your application.

**Comment by jakehockey10** [comment]
@GoshaFighten  Thanks for the confirmation.  I appreciate it!
