### ISSUE TITLE
Customized toolbar button does not become part of this button menu on media screen

### ISSUE THREAD

**Issue by gwsampso** [DevExpress/devextreme-angular#783]
In this example we customize the toolbar and add a refresh button
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/ToolbarCustomization/jQuery/Light/
https://embed.plnkr.co/?show=preview

In our browser if we reduce the size of the window and it gets to a certain width the buttons become a menu.

The customized toolbar "request button" however does not become part of this menu..

Is this the expected behaviour?

**Comment by ovchinnikov** [comment]
We don't process questions related to the DevExtreme UI widgets specifics in this repository. If you have any questions regarding your scenario or widget behavior, please submit a support request to our [support center](https://www.devexpress.com/Support/Center/Question/Create).
