### ISSUE TITLE
Compiling .less themes with webpack plugins?

### ISSUE THREAD

**Issue by k-vekos** [DevExpress/devextreme-angular#785]
Is there a way to compile the .less files included in the https://github.com/DevExpress/DevExtreme repository into .css at build time using webpack and its plugins? I don't know how I would otherwise use the style-compiler .DLL in conjunction with webpack to get hot-reloaded css files generated from the .less source.

**Comment by GoshaFighten** [comment]
We didn't test any other approaches to build our themes. So, I can't suggest any exact approach here. But, our themes are compiled using a Gulp task. As far as I understand you already found it. Gulp provides the `watch` method that can be used to track changes in a folder and execute another function when this occurs. You can reload the Webpack Dev Server. I found that the [How to fire a live reload from gulp?](https://github.com/webpack/webpack-dev-server/issues/166) issue that describes how to do this.
