### ISSUE TITLE
Method hideAppointmentPopup() do'nt work for dropdownAppointment

### ISSUE THREAD

**Issue by peterson-lc** [DevExpress/devextreme-angular#787]
Hello Dx Team!
I'm trying to hide all AppointmentPopup, but it doesn't work for dropdownAppointment, and same for AppointmentDblClick.

using this method:

```
Test(appointment) {
    debugger;
    this.scheduler.instance.hideAppointmentTooltip();
    this.scheduler.instance.hideAppointmentPopup();

   console.log('Call method okay');
}
```
 Thanks, 
Péterson Cardoso

    devexteme version: 17.2.8
    devextreme-angular version: 17.2.7

[x] bug Report 
[ ] feature request
[ ] support inquiry

**Comment by GoshaFighten** [comment]
The Scheduler does not have a method to show/hide the appointment collector's drop-down list programmatically. I suggest you open a ticket in our [support center](www.devexpress.com/ask) to elaborate on why you need to show or hide it in code. We will research your scenario to find an appropriate solution.
