### ISSUE TITLE
Interceptors stopped working

### ISSUE THREAD

**Issue by granella** [DevExpress/devextreme-angular#791]
After upgrading to version 18.1.3, the interceptors stopped working, version 17.2.7 it works normally.

devexteme version: 18.1.3
devextreme-angular version: 18.1.3

[x] bug Report 
[ ] feature request
[ ] support inquiry

**Comment by keserwan** [comment]
Same issue.
I have this code below in the interceptor: 
`      request = request.clone({ headers: request.headers.set('Authorization', authToken) });`

This code below works fine in 17.2.7

```
      let me = this;
      this.dataSource.store = new CustomStore({
        load: function (loadOptions) {
          return me.service.getAll(loadOptions, me.myTasksOnly, me.showCompletedTasks, me.fromDate, me.toDate).toPromise().then(json => {
            return json;
          })
        },
        key: "idTask"
      });
```

Check the image attached, no Authorization included in the request header.
![untitled](https://user-images.githubusercontent.com/11554745/40223736-b68f5c0a-5a8c-11e8-8072-e5cac493b8c3.png)

**Comment by granella** [comment]
online sample code https://angular-xcuxyl.stackblitz.io - v17.2.8
but stackblitz don't allow update to new version.

**Comment by ovchinnikov** [comment]
@granella I checked it with version 18.1.2-beta.1, but the result is the same
https://stackblitz.com/edit/angular-gwxetn

**Comment by GoshaFighten** [comment]
@granella,

If you don't use our CustomStore, does your code to request your server work?

**Comment by keserwan** [comment]
it is very weird to me.
with out devextreme custom store, some of the API's are sent with JWT tokens and some are not.
Also, I have one of the pages with Devextreme custom store and was calling the API with token.

Most of my API calls are are not injecting the JWT.
I reverted back the devextreme to 17.2.x and everything went back fine.

**Comment by keserwan** [comment]
The issue was:
All service files that are add to app.module--> providers were working fine.
All service files that are added to lazy loaded modules -->providers had this issue.

I moved all service files into 1 folder (_services) and I added them to the app.module-->providers.

I don't know if this is the best practice.

**Comment by MateuszBogdan** [comment]
I have the exact same problem.
The probable reason is that Devextreme feature modules imports HttpClientModule which should be imported only once in the root application module. It resets internal state of interceptors for lazy loaded routes.
More info: https://github.com/angular/angular/issues/20575

**Comment by joobeck** [comment]
@MateuszBogdan is correct, having the HttpClientModule imported again is overriding the interceptors, which shouldn't be done.  Likewise his solution won't work in most cases, devextreme likely needs to find a way around that.  We will be reverting to 17 and not updating until this is fixed.

**Comment by albertoVieiraNeto** [comment]
Is this issue resolved, i'm having the same problem on devextreme 18.1.5
