### ISSUE TITLE
main bundle size

### ISSUE THREAD

**Issue by keserwan** [DevExpress/devextreme-angular#793]
I am using devextreme 18.1.3.
I am only importing the following from devextreme: 
import { DxAutocompleteModule } from 'devextreme-angular/ui/autocomplete';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
import { DxDateBoxModule } from 'devextreme-angular/ui/date-box';
import { DxDropDownBoxModule } from 'devextreme-angular/ui/drop-down-box';
import { DxLoadPanelModule } from 'devextreme-angular/ui/load-panel';
import { DxNumberBoxModule } from 'devextreme-angular/ui/number-box';
import { DxPopupModule } from 'devextreme-angular/ui/popup';
import { DxScrollViewModule } from 'devextreme-angular/ui/scroll-view';
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { DxTextAreaModule } from 'devextreme-angular/ui/text-area';
import { DxTextBoxModule } from 'devextreme-angular/ui/text-box';
import { DxTreeListModule } from 'devextreme-angular/ui/tree-list';
import { DxValidationGroupModule } from 'devextreme-angular/ui/validation-group';
import { DxValidationSummaryModule } from 'devextreme-angular/ui/validation-summary';
import { DxValidatorModule } from 'devextreme-angular/ui/validator';

The main.bundle is still big, look at the image below...
if I do (ng build --prod) the main.bundle will be 2.7MB, (695KB gzipped).

is there any suggestion to minify the bundle?

Angular CLI: 6.0.3
Node: 8.9.3
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

![devextreme](https://user-images.githubusercontent.com/11554745/40422383-daad2eb4-5e97-11e8-830d-981f7d90cfb8.png)

**Comment by GoshaFighten** [comment]
You are getting the correct bundle size. This is how much space our code occupies. There is no way to reduce the bundle size.
