### ISSUE TITLE
Data grid "calculateCellValue" plus grid "editing" plugin forcing Angular change detection

### ISSUE THREAD

**Issue by hakimio** [DevExpress/devextreme-angular#797]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version: 18.1.3
    devextreme-angular version: 18.1.3
- Specify the type of the issue (check one with "x"):
[x] bug Report

**Steps to reproduce**:
- Enable grid editing (tested with "popup" mode)
- Assign non-existant "dataField" value to a column
- Assign "calculateCellValue" function which returns **new** array/object for the same column
- Run the test and click on "Edit" to edit one of the rows

Expected behavior:
- It should just work

Actual behavior:
- After clicking "Edit" the custom "calculateCellValue" function keeps being called until the app completely freezes

PS: yes, setting change detection to "OnPush" "fixes" this particular bug, but it also introduces some other bugs. So, no, that's not a proper solution.

**Comment by hakimio** [comment]
@ovchinnikov Any thoughts about this?

**Comment by ovchinnikov** [comment]
Yes, I can reproduce this issue with the [example](https://stackblitz.com/edit/angular-dx-numberbox-defect-lzfbq7?file=app%2Fapp.component.html). We will research it.
