### ISSUE TITLE
Feature Request: dxLoadPanel - Error handling for Position Attribute - Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by radomeit** [DevExpress/devextreme-angular#799]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    "devextreme": "^18.1.3",
    "devextreme-angular": "^18.1.3",

Other dependencies:
    "@angular/animations": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "angular-svg-icon": "^6.0.0",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.4",
    "jszip": "^3.1.5",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.2.0",
    "zone.js": "^0.8.26"

- Specify the type of the issue (check one with "x"):
[X] feature request 

Hi, I used the dxLoadPanel like this:

<dx-load-panel shadingColor="rgba(0,0,0,0.4)" [position]="{ of: '#appbody' }"
 [visible]="showLoadingAnimation" [showIndicator]="true"
[showPane]="true" [shading]="true" [closeOnOutsideClick]="false">
</dx-load-panel>

I accidently mistyped the position id ('#appbody') and at runtime got the error "Cannot read property 'nodeType' of undefined" in:

 * DevExtreme (animation/position.js)
 * Version: 18.1.3
 * Build date: Tue May 15 2018
...
var calculatePosition = function(what, options) {
...
        if (isWindow( of [0])) {
            h.atLocation = of .scrollLeft();
            v.atLocation = of .scrollTop();
            h.atSize = of [0].innerWidth > of [0].outerWidth ? of [0].innerWidth : of .width();
            v.atSize = of [0].innerHeight > of [0].outerHeight ? of [0].innerHeight : of .height()
        } else {
            if (9 === of [0].nodeType) {      ==> Error occurs here 
                h.atLocation = 0;
                v.atLocation = 0;
                h.atSize = of .width();
                v.atSize = of .height()
....

It's not so easy to get from that error message to the point of finding out that the position id is incorrect, especially if you made several changes between builds. I'd like to suggest a more accurate error message, if the id given in the position attribute cannot be found. Thank you very much.

**Comment by DokaRus** [comment]
This behavior is related to a core DevExtreme package. So, I've created [a new ticket](https://www.devexpress.com/Support/Center/Question/Details/T641281) in our SC. You can subscribe to it to get a notification once we fix it.
