### ISSUE TITLE
CustomStore insert and update methods return identifier instead of custom promise result

### ISSUE THREAD

**Issue by akushnikov** [DevExpress/devextreme-angular#803]
devexteme version: **18.1.3**
devextreme-angular version: **18.1.3**

[x] bug Report
[ ] feature request
[ ] support inquiry

**Desired behaviour**
`insert` and `update` promises of `CustomStore` should be resolved with custom implementation results

**Current behaviour**
When using `CustomStore` that is provided below, `update` and `insert` promises are resolved with record identifier instead of web service result.

**Code example**
```javascript
store = new CustomStore({
  key: 'id',
  // getList: () => Observable<UserModel[]>
  load: () => this.service.getList().toPromise(),	
								
  // post: (model: UserModel) => Observable<UserModel>
  insert: (model: UserModel) => this.service.post(model).toPromise(),	
		
  // delete: (id: number) => Observable<any>  
  remove: (id: number) => this.service.delete(id).toPromise(),	
				
  // put: (model: UserModel) => Observable<UserModel>
  update: (id: number, model: UserModel) => this.service.put(model).toPromise()	
});

save(model: UserModel) {
  let promise = Promise.resolve();
  if (model.id) {
	promise = promise.then(() => this.store.update(model.id, model));
  } else {
	promise = promise.then(() => this.store.insert(model))
  }
	
  promise.then((model: UserModel) => {
     /* Getting model identifier instead of model itself */ 
    console.log(model)
  })
}
```

**Comment by hakimio** [comment]
Have you looked into the [documentation](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/CustomStore/Methods/#updatekey_values)? It clearly shows that the first parameter is key and the second is the actual updated item.

**Comment by akushnikov** [comment]
@hakimio According to [the promise specification](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve), it receives only one input parameter. So if you use native `Promise` you get only identifier as argument of your `resolve` method.

**Comment by anna-zhernovkova** [comment]
Hello,
This issue was solved in the context of [this ticket](https://www.devexpress.com/Support/Center/Question/Details/T627023/odatastore-the-promise-then-callback-function-should-accept-a-single-parameter).
