### ISSUE TITLE
Need help on dx-tag-box

### ISSUE THREAD

**Issue by ismailsaleekh** [DevExpress/devextreme-angular#804]
"devextreme": "^17.2.7",
    "devextreme-angular": "^17.2.7",

## Support inquiry
i am using dx-tag-box, i am displaying a list of grouped items, my goal is to manipulate with these items. Note: value mode is set to useButtons, so i am getting my values only when i click Ok button. Firstly, i should take each ticked item, (when user clicks on checkbox next to item), before clicking Ok button, there is read only property selectedItems, but i couldnt get it. Secondly, i should set some items to prechecked, and should check them programmaticaly, so i should interpret clicking on checkbox, but i should not set values (it is crucial), 

in simple html select input, i would easily do it, by manipulating option element, but i need some help on using dx-tag-box, i will appreciate if u answer soon, thanks in advance

**Comment by hakimio** [comment]
Selecting items but not setting value part doesn't make any sense. There shouldn't be any need to modify the UI without modifying the value of the widget.

**Comment by artem-kurchenko** [comment]
TagBox doesn't provide a public API to get the dxList widget placed inside a drop-down window. 
In addition, there is no way to prevent selection when a user clicks one of loaded items. Would you please clarify why it's necessary to prevent selection at runtime? Is it possible to hide all items that cannot be selected beforehand. It would be great if you could describe your general task in greater detail, and we'll check if there are any alternative solutions.
