### ISSUE TITLE
getSelectedRowsData() not working

### ISSUE THREAD

**Issue by kodermax** [DevExpress/devextreme-angular#807]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.3
    devextreme-angular version: 18.1.3
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 
I use DxDataGrid.
When I select items on the second page
The function  getSelectedRowsData returns an empty array

**Comment by ovchinnikov** [comment]
Please provide me with a sample project that reproduces the issue.

**Comment by ovchinnikov** [comment]
This issue is closed because of being inactive. If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
