### ISSUE TITLE
Using Globalize in Angular CLI project

### ISSUE THREAD

**Issue by PoltavaPride** [DevExpress/devextreme-angular#808]
- I use latest version Angular and Angular CLI it's 6+.
- Devextreme and Devextreme-angular has versions **18.1.3**.

I can use "**_devextreme-intl_**" and "**_loadMessages_**" function and localized components, but not all of I need.

When i install **cldr-data** + **globalize** and try to use different functions like:

`Globalize.load(
    deCaGregorian, deNumbers, deCurrencies,
    ruCaGregorian, ruNumbers, ruCurrencies
);`

I get a lot of errors in console related with working globalize with "**cldr**" and "**cldr/event**".

Can you create example project with Angular CLI + Globalize and **_Globalize.load()_** ?
The main what i need it's use **Globalize.load()**.

**Comment by korotinmain** [comment]
I have the same problem with my Angular 5 and CLI 1.7 version and dev-extreme 18.1.3 version. Globalize not working with CLI (

**Comment by ovchinnikov** [comment]
I recommend that you refer to the following thread where a similar inquiry was discussed: [Can't get Globalize to work inside an Angular CLI project](https://github.com/angular/angular-cli/issues/7949)

**Comment by PoltavaPride** [comment]
Excellent! Working! Thank you!
