### ISSUE TITLE
Problems integrating DevExtreme with ASP .Net Core using Webpack

### ISSUE THREAD

**Issue by strpipe** [DevExpress/devextreme-angular#810]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.3
    devextreme-angular version: 18.1.3
- Specify the type of the issue (check one with "x"):
[ ] bug Report 
[ ] feature request 
[x] support inquiry 

When following the instructions on: https://js.devexpress.com/Documentation/Guide/Getting_Started/Installation/How_To/Add_DevExtreme_to_an_ASP.NET_Core_Angular_Application/ , I get many error messages.

Here are the first three of them:
```
ERROR in ./~/devextreme-angular/core/http-request.js
Module not found: Error: Can't resolve '@angular/common/http' in 'D:\Benutzer\Adrian\Code\Visual Studio\WebApplication4\WebApplication4\node_modules\devextreme-angular\core'
 @ ./~/devextreme-angular/core/http-request.js 16:13-44
 @ ./~/devextreme-angular/index.js
 @ ./ClientApp/app/app.shared.module.ts
 @ ./ClientApp/app/app.browser.module.ts
 @ ./ClientApp/boot.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts
ERROR in ./~/devextreme-angular/ui/accordion.js
Module not found: Error: Can't resolve '@angular/common/http' in 'D:\Benutzer\Adrian\Code\Visual Studio\WebApplication4\WebApplication4\node_modules\devextreme-angular\ui'
 @ ./~/devextreme-angular/ui/accordion.js 25:13-44
 @ ./~/devextreme-angular/index.js
 @ ./ClientApp/app/app.shared.module.ts
 @ ./ClientApp/app/app.browser.module.ts
 @ ./ClientApp/boot.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts
ERROR in ./~/devextreme-angular/ui/action-sheet.js
Module not found: Error: Can't resolve '@angular/common/http' in 'D:\Benutzer\Adrian\Code\Visual Studio\WebApplication4\WebApplication4\node_modules\devextreme-angular\ui'
 @ ./~/devextreme-angular/ui/action-sheet.js 25:13-44
 @ ./~/devextreme-angular/index.js
 @ ./ClientApp/app/app.shared.module.ts
 @ ./ClientApp/app/app.browser.module.ts
 @ ./ClientApp/boot.browser.ts
 @ multi event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.browser.ts
```

Can you help me resolve the issue?

**EDIT:**  This is happening on the "node node_modules/webpack/bin/webpack.js"-Command, found in the .csproj

**Comment by strpipe** [comment]
This is just a problem related to versioning.

**Comment by dadams71** [comment]
What is the versioning issue? what Version should be used? Your answer is quite vague...

**Comment by borisgappov** [comment]
Here this instruction works, there are no problems: https://github.com/DevExpress/devextreme-angular/tree/18.2#quick-start

**Comment by dadams71** [comment]
> Here this instruction works, there are no problems: https://github.com/DevExpress/devextreme-angular/tree/18.2#quick-start

Thanks for the help.
