### ISSUE TITLE
Large Bundle Size - Angular

### ISSUE THREAD

**Issue by anikets43** [DevExpress/devextreme-angular#811]
I tried compiling the angular 6 project with and without devexteme-angular. I just used simple customer grid in the app.component and build the project using `ng build --configuration production`. main.*.js bundle seems to be too large for such a small demo app. I did set AOT, buildOptimizer and other configurations for the prod.

**Versions**:
   "devextreme": "^17.2.7",
   "devextreme-angular": "^17.2.7"

Here's the screenshot
![image](https://user-images.githubusercontent.com/7136799/41582928-95da8546-73c0-11e8-8939-4d8555246d85.png)

Please let me know if I'm missing anything in the configuration or any optimization strategy needs to be done.

Cheers,
Aniket

**Comment by hakimio** [comment]
Check [issue 592](https://github.com/DevExpress/devextreme-angular/issues/592). dxvladislavvolkov has posted a solution at the bottom of the thread.

**Comment by anikets43** [comment]
Thanks @hakimio Unfortunately doesn't make any difference even after referencing only the used module; bundle size remains same.
 
`import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';`

**Comment by hakimio** [comment]
Did you replace all the places where you are importing something from "devextreme-angular"?

**Comment by anikets43** [comment]
@hakimio This is just a demo app containing a datagrid, so only imported in the app.module.ts.

**Comment by hakimio** [comment]
@default23 It does make sense if you want to reduce your bundle size. See the comment I linked in my previous post.
2MB is the normal size for DevExtreme + DevExtreme-Angular ([comment from one of DevExtreme devs](https://github.com/DevExpress/devextreme-angular/issues/592#issuecomment-339413270)).
If you are using gzip compression on your http server, the size should be around 4 times less than the number you get when you run "ng build --prod". For example, 2.37MB "main.js" file when transferred with gzip only weighs 584KB.
Also, if initial load time is so important for you, you can use server side rendering.

**Comment by default23** [comment]
@hakimio is all of your library code using in the `data-grid`? Why u shouldn't use tree-shaking?

**Comment by b-veiga-fi** [comment]
@webcat12345 same here. Why do we have every widgets in the bundle ? I'm using only 5 widgets from "devextreme-angular" (with the correct imports).

**Comment by webcat12345** [comment]
my final decision was just don't use this library. Its optimization is bad.

**Comment by hakimio** [comment]
> @webcat12345 same here. Why do we have every widgets in the bundle ? I'm using only 5 widgets from "devextreme-angular" (with the correct imports).

Most likely because you are importing modules and components wrong way.
Don't do the following:
```
import { DxButtonModule } from 'devextreme-angular';
```
Do this instead:
```
import { DxButtonModule } from 'devextreme-angular/ui/button';
```

And this applies both to modules **and** components:
```
import { DxButtonComponent } from 'devextreme-angular/ui/button';
```

If you do that it should only pull required modules.

**Comment by hakimio** [comment]
> my final decision was just don't use this library. Its optimization is bad.

It's your loss. Should have read the README. DevExtreme is an awesome UI component library.

**Comment by b-veiga-fi** [comment]
@hakimio this is exactly what I am doing. 
My imports : 
![image](https://user-images.githubusercontent.com/44065020/57918579-57350c80-7897-11e9-98bd-de530dd8425d.png)
and my bundle:
![image](https://user-images.githubusercontent.com/44065020/57918765-b561ef80-7897-11e9-9b9d-2ded9aead484.png)

**Comment by hakimio** [comment]
Maybe some of the components you are using are importing other components. For example, data grid has a lot of dependencies.

**Comment by webcat12345** [comment]
I can't remember exactly but I think I used this way to import only for a timepicker. Let me walk through Git history if I was wrong.

**Comment by hakimio** [comment]
Also, here are few recommendations to improve initial app load time:
* Use gzip compression
* Set "cache-control" and "expires" headers:
```
cache-control: max-age=31536000
expires: Sat, 16 May 2020 09:38:43 GMT
```
* Enable http/2 protocol
* Use CDN (AWS CloudFront, Azure CDN, Cloudflare, etc)

**Comment by webcat12345** [comment]
I tried to gzip compression actually, and http/2 protocol couldn't be used because we were using Heroku. And from my understanding even if we import libraries without targetting the specific destination, it should be handled by tree-shaking automatically, isn't it? Readme says that exactly [here](https://github.com/DevExpress/devextreme-angular#bundlers-with-tree-shaking-support), but obviously it didn't work. Or is this feature introduced recently?

**Comment by hakimio** [comment]
> And from my understanding even if we import libraries without targetting the specific destination, it should be handled by tree-shaking automatically, isn't it?

It should but with DevExtreme Angular, it never did work that way and it doesn't work right now. That section of the readme should be fixed. Even in all official examples where they are using Angular CLI, they are still importing using specific modules / long paths. Otherwise you get a huge bundle.

**Comment by webcat12345** [comment]
That document update is quite important for these guys otherwise they could lose users and I can certainly say that they could write it on medium or twitter which is the worst case (I think I have read about it on medium 6 months ago or not sure), for me I was able to reduce 2.0 MB by removing dev extreme from the project and the entire team was happy with it. :D 
Looking forward to updated documentation!

**Comment by StevenFewster** [comment]
FYI - I created a new project with one page, and implemented this widget: https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/Overview/Angular/Light/

I ran two tests, one using the long path, one using the short path imports.

In both cases main.js came out at 2.43MB using:
`ng build --project=myproj --configuration=production`

```
configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/myproj/src/environments/environment.ts",
                  "with": "apps/myproj/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            }
```

Reviewing the stats.json I can see that what is imported is (plausibly) needed for all the various bits (it's a very full featured grid).

IMHO: Tree shaking I guess is either working, or the library imports are using short paths and pulling in everything. I couldn't verify using short paths making a difference to my build with prod settings as above.

Mine is for an internal app, meaning that size is (ahem) less of a priority - I've now got to go down the PWA route and see if that helps.  The usual things to improve server configs will help, sure - but I totally see webcat12345's point, serving this over 3G to a tablet would be less than great where your trying to ensure that only the absolute necessities are downloaded.

**Comment by hakimio** [comment]
@StevenFewster Try to make the same test with textbox or some other smaller component. 
And no, Tree Shaking is not supported according to one of the developers. See issue #353.

**Comment by StevenFewster** [comment]
Absolutely right - I guess if using DataGrid (Pivot too, probably) you're going to have to accept a large bundle size. DxButtonGrid came in at 858kB for main.js, and unaffected by full/partial path.

**Comment by Brandinga** [comment]
there are some infos in the roadmap
https://js.devexpress.com/Roadmap/#Performance


![image](https://user-images.githubusercontent.com/31313315/58429049-da7b0d00-80a4-11e9-8a4d-5892d3895899.png)

**Comment by OmniAndy** [comment]
I am also using the DxDataGrid.  It doesn't matter how I import the Modules/Components, my bundle size does not change.  Main.js is 2.9mb and Vendor.js is 5.4 mb.

I've tried this:
import { DevExtremeModule } from 'devextreme-angular'; -- in app.module only

this:
import { (ControlModule) } from 'devextreme-angular';  -- in all modules that contain the specified control

this:
import { (ControlModule) } from 'devextreme-angular/ui/(control name)';  -- in all modules that contain the specified control

Main and Vendor files remains the same.  Yes, I am using a production build.  With a dev build, Main.js is 3.8mb and Vendor.js is 16.5mb.

**Comment by hakimio** [comment]
@OmniAndy you have to import everything from "devextreme-angular" library using long paths ("devextreme-angular/ui/(control name)" or similar) from specific sub-folders, no matter if it's UI module, component or "DxServerTransferStateModule". If you have `import {SomeThing} from 'devextreme-angular'` anywhere in your code, it will result in a huge bundle. Normally DevExtreme Angular app (JS + CSS) weighs between 2 and 3MB. Try to build [devextreme-angular-template](https://github.com/DevExpress/devextreme-angular-template) example project to see how much the bundle should weigh when everything is imported correctly.

**Comment by OmniAndy** [comment]
@hakimio ... like I said.  I tried that.  Bundle was the same exact size.  I think people are right when they say Data-Grid has so many dependencies that it ends up importing everything anyway.

**Comment by hakimio** [comment]
@OmniAndy we also use the data grid (and many other widgets), but we don't generate separate vendor.js - everything's included in main.js. The output looks like this:
```
$ ng build --prod

Date: 2019-06-27T13:16:32.868Z
Hash: cd5d65433cfd386e034b
Time: 42819ms

chunk {0} runtime.a5dd35324ddfd942bef1.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.3b629f44655bed6ddbac.js (main) 2.82 MB [initial] [rendered]
chunk {2} polyfills.1cd3466dbc8de4b5c45c.js (polyfills) 41 kB [initial] [rendered]
chunk {3} styles.0fbb3dafd701930074f1.css (styles) 638 kB [initial] [rendered]

Done in 55.03s.
```

**Comment by OmniAndy** [comment]
@hakimio How do you not use a vendor file?  Is that the "vendorChunk" flag in angular.json?

**Comment by Franki1986** [comment]
What helped me was take a look at your Component import not anly at your Module import, some of my Component imports where also from devextreme-angular/ui/all..

**Comment by adryx86** [comment]
https://github.com/DevExpress/devextreme-angular/issues/811#issuecomment-493388263
This worked succesfully on my project.
Thanks @hakimio

**Comment by scote** [comment]
I did the same thing and my vendor bundle size is less large then before.

**Comment by michal-husak** [comment]
For me the update to 19.2.3 helped a lot.
before:
![image](https://user-images.githubusercontent.com/5699580/68872437-5540ee80-06fe-11ea-977e-a6218e047f57.png)
after:
![image](https://user-images.githubusercontent.com/5699580/68872489-64c03780-06fe-11ea-8740-a1497f67a45b.png)

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by hakimio** [comment]
@pedrofurtado major improvements should come in DevExtreme 20.1 once they [split DevExtreme into modules](https://js.devexpress.com/Roadmap/#Performance).

**Comment by pedrofurtado** [comment]
@hakimio Thanks for feedback! It's a great news that devextreme 20.1 will provide this feature 🎉

**Comment by nigrosimone** [comment]
20.1 Is out, any news on this issue? Bundle optimization seam planned for 20.2

**Comment by hakimio** [comment]
They postponed it until v20.2.

**Comment by riheldo** [comment]
> @hakimio Thanks for feedback! It's a great news that devextreme 20.1 will provide this feature 🎉

Not yet... 🙁

**Comment by nigrosimone** [comment]
20.2 Is in the pre-release https://github.com/DevExpress/DevExtreme/releases/tag/20.2.1-sprint.2 any news on bundle optimization?

**Comment by pedrofurtado** [comment]
@BingoRUS @DevExpress Any news available for us?

**Comment by basilinjoe** [comment]
No bundle optimization yet?

**Comment by LexDX** [comment]
Hi @all,
 
Let me share our current progress with you. We prepared our codebase migration to ES6 modules and these modules will be available in v20.2. Our next goal is to properly support tree shaking and perform code splitting. We have plans to introduce tree shaking in the next major release (v20.2) if it all goes well. As for the code splitting, this task requires more time and I can't give you any estimates.

**Comment by IlyaKhD** [comment]
We're going to deliver a set of ES6 modules starting with v20.2, see https://github.com/DevExpress/DevExtreme/issues/14351 for more details.

**Comment by dathoang** [comment]
LoL I don't know what you guys are expecting. The DataGrid is the most complex component and it uses nearly every other component (Button, Popup, Form, all the editor). It's the way this library is designed. 
I don't know if there is a way datagrid automatically import required module depend on configuration ?

**Comment by dxbykov** [comment]
Hi @dathoang,

> The DataGrid is the most complex component and it uses nearly every other component

That's true.

> It's the way this library is designed.

That's also true, but that's what we want to change - redesign it.

> I don't know if there is a way datagrid automatically import required module depend on configuration ?

If we are talking about static imports, the only way to achieve this goal is to let developers import what's required. For instance, if you need to enable data editing and Filter Row in our DataGrid, you will import a set of modules that contains required child components as follows:

```
import { DxDataGridBaseModule, DxDataGridEditingModule, DxDataGridFilterRowModule } from 'devextreme-angular';

...

@NgModule({
    imports: [
        ..
        DxDataGridBaseModule,
        DxDataGridEditingModule,
        DxDataGridFilterRowModule
    ],

...

<dx-data-grid>
  <dx-data-grid-editing />
  <dx-data-grid-filter-row />
</dx-data-grid>
```

So, if we treat each child component as a 'plugin', it won't be bundled until it's manually imported as a module. Each plugin can have its own configuration properties. That's the way we consider for better code splitting. Any feedback on this approach is welcome.

**Comment by danigt91** [comment]
How this goes? Any news or dates here? I'm trying to adopt dev-extreme in my company due I think is the best actor in the market, but the bundling size & tree shacking is kinda stopper. Thx in advance.

**Comment by hakimio** [comment]
@danigt91 https://github.com/DevExpress/DevExtreme/issues/14351#issuecomment-717278424

**Comment by wpitallo** [comment]
20.2.4 bundle is still quite big for the few controls that I am using :(

**Comment by pedrofurtado** [comment]
Any official updates on it?

**Comment by hakimio** [comment]
It's not in v20.2. Check the link I've posted.

**Comment by wpitallo** [comment]
Ah thanks @hakimio what's the eta?

**Comment by hakimio** [comment]
If DX release schedule doesn't change, v21.1 should be out around May this year.

**Comment by kkachniarz220** [comment]
By adding 

> > @webcat12345 same here. Why do we have every widgets in the bundle ? I'm using only 5 widgets from "devextreme-angular" (with the correct imports).
> 
> Most likely because you are importing modules and components wrong way.
> Don't do the following:
> 
> ```
> import { DxButtonModule } from 'devextreme-angular';
> ```
> 
> Do this instead:
> 
> ```
> import { DxButtonModule } from 'devextreme-angular/ui/button';
> ```
> 
> And this applies both to modules **and** components:
> 
> ```
> import { DxButtonComponent } from 'devextreme-angular/ui/button';
> ```
> 
> If you do that it should only pull required modules.

It helped me: from 5.9MB to 500 kB

**Comment by derHodrig** [comment]
I am using the report designer and the report viewer. The Js is in production build at 5.34 MB. Is this serious?

**Comment by MaximKudriavtsev** [comment]
Hi everyone,

We have released the ES6 modules feature. It is the first step to reducing bundle size. You can find detailed information [here](https://github.com/DevExpress/DevExtreme/issues/14351#issuecomment-800307575). Try the feature in your application and let us know if you encounter issues. Also, please share your project bundle size with and without the ES6 modules feature. This information will help us plan future enhancements.

**Comment by dathoang** [comment]
> Hi everyone,
> 
> We have released the ES6 modules feature. It is the first step to reducing bundle size. You can find detailed information [here](https://github.com/DevExpress/DevExtreme/issues/14351#issuecomment-800307575). Try the feature in your application and let us know if you encounter issues. Also, please share your project bundle size with and without the ES6 modules feature. This information will help us plan future enhancements.

Does this import style still useful to reduce bundle size ?
`import { DxButtonModule } from 'devextreme-angular/ui/button';`

**Comment by hakimio** [comment]
@dathoang No.

**Comment by eqplanoFront** [comment]
My problem is related to this, my build time increased up to 160% after adding the DE library, any tips?

**Comment by adams-family** [comment]
I believe the same issue here. An very simple app (just one component) with a very reasonable subset of DX elements:

```
import { DxChartModule,
  DxPieChartModule,
  DxDataGridModule, 
  DxAutocompleteModule, 
  DxTextBoxModule, 
  DxButtonModule, 
  DxDropDownButtonModule, 
  DxPopupModule,
  DxCheckBoxModule } from 'devextreme-angular';
```

Any ideas how to reduce this?

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/19559733/147072490-18ad10ea-09f5-47a6-ade1-90b5f4ac78e6.png">

**Comment by hakimio** [comment]
That's way too much for production bundle. Have you enabled all optimizations? "ng build --environment production"?

**Comment by AbdealiJK** [comment]
Just thought I'd add a note here with my findings - as I felt the thread was a bit confusing.
When I test it now with devex 21.2:
 - Empty angular project - 60.11 kB
 - Install devex but don't use it - 60.11 kB
 - Use devex button with 'devextreme-angular' imports - 122.62 kB
 - Use devex button with 'devextreme-angular/ui/button' imports - 122.62 kB

Based on the discussion in https://github.com/DevExpress/DevExtreme/issues/14351#issuecomment-717278424 and @hakimo 's comments
It looks like:
 - If you are using devex 21.1+ - you don't need to worry about how you import stuff anymore!
 - If you are using older versions - you may need to worry about it

Versions I used:
```
$ ng --version
Angular CLI: 13.1.2
Node: 14.18.2
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

<details>
  <summary>Empty angular project: (60.11 kB)</summary>

    # Benchmark setup
    $ npm i -g @angular/cli
    $ ng new angular-devex-test --minimal --routing --style css
    $ cd angular-devex-test

    $ npm run build
    > ng build
    Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
    main.efb0a080abc6a125.js      | main          | 178.82 kB |                48.05 kB
    polyfills.b5b0149eb4f94cba.js | polyfills     |  36.21 kB |                11.47 kB
    runtime.511212c3af742c14.js   | runtime       |   1.06 kB |               602 bytes
    styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -
                                | Initial Total | 216.09 kB |                60.11 kB

</details>

<details>
  <summary>Install devex but don't use it: (60.11 kB)</summary>

    $ npm i --save devextreme devextreme-angular
    # In package.json these were added:
    #       "devextreme-angular": "^21.2.4",
    #       "devextreme": "^21.2.4",

    $ npm run build
    Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
    main.efb0a080abc6a125.js      | main          | 178.82 kB |                48.05 kB
    polyfills.b5b0149eb4f94cba.js | polyfills     |  36.21 kB |                11.47 kB
    runtime.511212c3af742c14.js   | runtime       |   1.06 kB |               602 bytes
    styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -
                                | Initial Total | 216.09 kB |                60.11 kB

</details>

<details>
  <summary>Use devex button with 'devextreme-angular' imports: (122.62 kB)</summary>

    # Diff of changes done to `app.component.ts`:
    +import { DxButtonComponent } from 'devextreme-angular';
    ...
    +  constructor() {
    +    DxButtonComponent; // just use it here
    +  }

    # Diff of changes done to `app.module.ts`:
    +import { DxButtonModule } from 'devextreme-angular';
    ...
    -  imports: [BrowserModule, AppRoutingModule],
    +  imports: [BrowserModule, AppRoutingModule, DxButtonModule],
    +  exports: [DxButtonModule],

    $ npm run build
    Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
    main.76d364d8c9e2ba24.js      | main          | 453.00 kB |               110.50 kB
    polyfills.b5b0149eb4f94cba.js | polyfills     |  36.21 kB |                11.47 kB
    runtime.f0b34f53f7009121.js   | runtime       |   1.23 kB |               661 bytes
    styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -

                                | Initial Total | 490.44 kB |               122.62 kB
</details>

<details>
  <summary>Use devex button with 'devextreme-angular/ui/button' imports: (122.62 kB)</summary>

    # Diff of changes done to `app.component.ts`:
    +import { DxButtonComponent } from 'devextreme-angular/ui/button';
    ...
    +  constructor() {
    +    DxButtonComponent; // just use it here
    +  }
    
    # Diff of changes done to `app.module.ts`:
    +import { DxButtonModule } from 'devextreme-angular/ui/button';
    ...
    -  imports: [BrowserModule, AppRoutingModule],
    +  imports: [BrowserModule, AppRoutingModule, DxButtonModule],
    +  exports: [DxButtonModule],

    $ npm run build
    Initial Chunk Files           | Names         |  Raw Size | Estimated Transfer Size
    main.76d364d8c9e2ba24.js      | main          | 453.00 kB |               110.50 kB
    polyfills.b5b0149eb4f94cba.js | polyfills     |  36.21 kB |                11.47 kB
    runtime.f0b34f53f7009121.js   | runtime       |   1.23 kB |               661 bytes
    styles.ef46db3751d8e999.css   | styles        |   0 bytes |                       -

                                | Initial Total | 490.44 kB |               122.62 kB
</details>

**Comment by AbdealiJK** [comment]
Here are the numbers when I use a single module one by one (for the modules I am interested in) ... if it helps anyone get a benchmark

```
 - NO Devex Module       -  216.09 kB (transfer size:  60.11 kB)
 - DxDataGridModule      -    2.01 MB (transfer size: 456.46 kB)
 - DxButtonModule        -  490.44 kB (transfer size: 122.62 kB)
 - DxAccordionModule     -  532.60 kB (transfer size: 135.66 kB)
 - DxCheckBoxModule      -  600.51 kB (transfer size: 146.85 kB)
 - DxDateBoxModule       -    1.10 MB (transfer size: 249.78 kB)
 - DxDropDownBoxModule   -  823.09 kB (transfer size: 190.71 kB)
 - DxFileUploaderModule  -  640.07 kB (transfer size: 154.39 kB)
 - DxListModule          -  950.25 kB (transfer size: 216.42 kB)
 - DxLoadIndicatorModule -  338.45 kB (transfer size:  94.10 kB)
 - DxLoadPanelModule     -  485.68 kB (transfer size: 124.67 kB)
 - DxNumberBoxModule     -  710.36 kB (transfer size: 167.73 kB)
 - DxPopoverModule       -  729.09 kB (transfer size: 173.72 kB)
 - DxRadioGroupModule    -  638.58 kB (transfer size: 156.24 kB)
 - DxScrollViewModule    -  492.81 kB (transfer size: 127.05 kB)
 - DxSelectBoxModule     -  977.27 kB (transfer size: 218.51 kB)
 - DxSwitchModule        -  500.09 kB (transfer size: 128.31 kB)
 - DxTabsModule          -  694.76 kB (transfer size: 164.95 kB)
 - DxTagBoxModule        - 1002.96 kB (transfer size: 222.74 kB)
 - DxTemplateModule      -  255.70 kB (transfer size:  71.66 kB)
 - DxTextAreaModule      -  648.38 kB (transfer size: 157.03 kB)
 - DxTextBoxModule       -  688.89 kB (transfer size: 162.69 kB)
 - DxTooltipModule       -  729.61 kB (transfer size: 173.85 kB)
 - DxTreeViewModule      -  858.30 kB (transfer size: 198.77 kB)
 - DxMenuModule          -  899.05 kB (transfer size: 206.56 kB)
 - ALL the above Modules -    2.32 MB (transfer size: 485.06 kB)
 - ALL the above Modules (except data grid) - 1.50 MB (transfer size: 298.96 kB)
```

Note: As you can see - data-grid does use most of these internally.

All the tests:
 - Use a template created by `ng new --minimal --routing --style css`
 - Directly import from 'devextreme-angular'
 - Use devextreme and devextreme-angular v21.2.4
 - Use angular 13.1.2, Node 14.18.2

For those who want to see the project in more detail:
[angular-devex-test.zip](https://github.com/DevExpress/devextreme-angular/files/7837151/angular-devex-test.zip)

Overall - it seems ES6 modules and tree shaking is working to a particular degree. So, that is much much better than the previous versions :+1:

I still feel that for the amount I use devex ( I use datagrid :) ), I wouldn't want to make my bundle increase by 2MB (400kb in transfer size)... 

To give you a comparison the size after minification (without going into functionality comparison):
 - [jquery+datatables](https://datatables.net/download/) is: 87KB (datatable) + 88KB (jquery) = 175 KB
 - [angular-datatables](https://github.com/l-lin/angular-datatables) is: 402.56 kB - 216.09 kB = ~200kb
 - Angular + devex data grid is: 2.01 MB - 216.09 kB = ~1.8MB

So, it feels like there is definitely a scope for some sort of improvement here in terms of modularization. (Devex's datagrid is around 9x larger)
Maybe that should be captured in a separate more specific ticket.
The idea put forth in https://github.com/DevExpress/devextreme-angular/issues/811#issuecomment-717791571 seems to be intuitive and reasonable
