### ISSUE TITLE
Use ngx translate for devextreme widgets

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/devextreme-angular#812]
I am using ngx translate for my Angular application.
The translation files are loaded from my webserver over a webservice.
Is it possible that I put in a section "DevExtreme" into my json file and let the widgets take the localized texts from the ngx translation file?

I have already seen your ngx translate sample but it is not so clear how this works there...

**Comment by Franki1986** [comment]
Ok after some time now it works.
The json files in the localize message folder can be saved in the database. Then the part that contains this Devextreme json is passed to the loadmessage() method.
Unlike ngx translate the devextreme components change their language onl on page reload.

**Comment by Razgort** [comment]
Hi man,
How did you succeded ?
I can't get devextreme widget work with ngx translate

**Comment by Franki1986** [comment]
Tomorrow I will post my sample.. If you see it, it is realy simple, but the docs are not clear enough if you read them as beginner.

**Comment by Franki1986** [comment]
I have problems letting devextreme loading into stackblitz, but basically you could do the folowing :

[https://stackblitz.com/edit/angular-lzrqpx?file=src%2Fapp%2FCustomTranslateLoader.ts](example)

important is to import the intl libs:

```
import "devextreme-intl";
import {loadMessages, locale} from 'devextreme/localization';

// the content of these you have to load in your ngx-translate loader from the webservice  
import deMessages from 'devextreme/localization/messages/de.json';
import enMessages from 'devextreme/localization/messages/en.json';
import frMessages from 'devextreme/localization/messages/fr.json';
import nlMessages from 'devextreme/localization/messages/nl.json';
```

initialize the language with the needed mesage:

`loadMessages(frMessages)`


Then after you select the specific language set it with the 'locale'-method:

```
      locale('de');
      localStorage.setItem("locale", current);
```

I don't know if this is sufficent for you?
Let me know..

**Comment by NickMitrokhin** [comment]
> the docs are not clear enough if you read them as beginner

@Franki1986, would you please clarify what is not clear in our documentation regarding localization so that we will be able to improve it?

**Comment by BobaFett58** [comment]
I hope this information will be useful to someone.

Initially, I had problems loading json files into my project.
To solve the problem, you need to create a file in the 'src' folder with the name 'typings.d.ts' and add the following code there:
`
declare module 'devextreme/localization/messages/*' {
    const value: any;
    export = value;
}
`
After you need to change 
`import  ruMessages from 'devextreme/localization/messages/ru.json';`
`import * as ruMessages from 'devextreme/localization/messages/ru.json';`

And finally to apply our json we need to change this
`
loadMessages(ruMessages);
locale('ru');
`
to this
`
loadMessages(ruMessages.default);
locale('ru');
`
best regards.

**Comment by leonkosak** [comment]
I just added "resolveJsonModule": true in tsconfig.json.

{
  "compilerOptions": {
    .
    .
    "resolveJsonModule": true
    .
    .
  }
}

No need to add module declaration to typings.d.ts.
And importing this way:
import * as ruMessages from 'devextreme/localization/messages/ru.json';
