### ISSUE TITLE
Infinite Scrolling Is Not Working in Version 18.1.4

### ISSUE THREAD

**Issue by kentsitu** [DevExpress/devextreme-angular#815]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.4
    devextreme-angular version: 18.1.4
- Specify the type of the issue (check one with "x"):
[x] bug Report 
Recently I upgraded my DevExtreme version from 17.2.3 to 18.1.4. After I installed the new devextreme and devextreme-angular package, I found the infinite scrolling is not working anymore. The data grid height setting in scss file didn't work. The height of the grid became as long as the number of the total rows. 
Please take a look. 
html:
		<dx-data-grid class="gridContainer" [dataSource]="data" [columnAutoWidth]="true" [allowColumnResizing]="true" [rowAlternationEnabled]="true" [allowColumnReordering]="true" (onRowClick)="edit($event)" (onEditorPreparing)="checkReadOnly($event)" (onRowInserting)="add($event)"
		    (onRowUpdating)="update($event)" (onSelectionChanged)="selectionChanged($event)" (onRowRemoving)="delete($event)">
...
<dxo-scrolling mode="infinite"></dxo-scrolling>
<dxi-column dataField="..." caption="..." sortOrder="asc">
				<dxi-validation-rule type="required"></dxi-validation-rule>
			</dxi-column>
...
</dx-data-grid>

scss:
.gridContainer {
  height: calc(99vh - 180px);
  width: 100%;
}

**Comment by ovchinnikov** [comment]
Would you please modify the https://stackblitz.com/edit/angular-qn7raq example to reproduce the issue?

**Comment by kentsitu** [comment]
It seems working here.... But it is not working in my  project, so weird.... The height of the data grid could not be define, the width can. Any possible reason? Upgrade improperly?

**Comment by kentsitu** [comment]
Sorry, closed by mistake...

**Comment by ovchinnikov** [comment]
It is difficult to determine the cause of the problem without reproducing the issue on our side. Would you please send us a simple working project that shows the issue in action?

**Comment by ovchinnikov** [comment]
This issue is closed because of being inactive. If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
