### ISSUE TITLE
ErrorRow depends on showColumnHeaders

### ISSUE THREAD

**Issue by NorDroN** [DevExpress/devextreme-angular#816]
Hi!
Unexpected behavior: 
when I hide column headers ( [showColumnHeaders]="false" ) I don't see error row.

https://codesandbox.io/s/814kpq9vn0

**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.3
    devextreme-angular version: 18.1.3
- Specify the type of the issue (check one with "x"):
[*] bug Report

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular integration. I have created a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T653307) in our Support Center.

**Comment by NorDroN** [comment]
Hi!
I see that you created issue on your support center, but nobody has answered in [that](https://www.devexpress.com/Support/Center/Question/Details/T653307) place yet.
