### ISSUE TITLE
DxDataGrid filter builder throws errors when using boolean data type columns

### ISSUE THREAD

**Issue by muni127** [DevExpress/devextreme-angular#822]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.4
    devextreme-angular version: 18.1.4

- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request
[ ] support inquiry

Problem when using dxDataGrid filter builder with boolean dataType columns.

Demo has boolean column "Bool" which will throw error when you open the filter builder under the grid -> https://codesandbox.io/s/oo0k7mwr0z

ERROR Error: E1048 - The "=" operation is not found in the filterOperations array

Also, if you clear the filter and create a new filter and set to filter the "Bool" column, the grid throws another error 

ERROR Error: E1048 - The "undefined" operation is not found in the filterOperations array.

This does not occur with any other data types, only happens to boolean data types.

EDIT:
Upon further investigation I found that if I either set the "dataType" of the column to "boolean" or use State Storing the issue arises.

So the only way to prevent this right now is to not use state storing and not define boolean column types if I want to use the data grid's filter builder on that column.

**Comment by ovchinnikov** [comment]
The issue is not related to the Angular integration. I have created a corresponding [ticket ](https://www.devexpress.com/Support/Center/Question/Details/T653737/dxdatagrid-filter-builder-throws-errors-when-boolean-data-type-columns-are-used) in our Support Center.
