### ISSUE TITLE
Dx-number-box doesn't work properly with format

### ISSUE THREAD

**Issue by arndwestermann** [DevExpress/devextreme-angular#824]
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.4
    devextreme-angular version: 18.1.4
- Specify the type of the issue (check one with "x"):
[x] bug Report
If i apply a format like format="###,###,##0.00€" and tab through the boxes, it erases or resets the content of the boxes. You can reporduce it in your demo section. https://js.devexpress.com/Demos/WidgetsGallery/Demo/NumberBox/Overview/Angular/Light/

[ ] feature request 
[ ] support inquiry

**Comment by nightskylark** [comment]
The issue is not related to the Angular integration. We have a corresponding [ticket](https://www.devexpress.com/Support/Center/Question/Details/T653896/numberbox-widget-resets-its-value-if-tab-is-used-to-navigate-to-another-control) in our Support Center.
