### ISSUE TITLE
Scroll view working so fast

### ISSUE THREAD

**Issue by neco122** [DevExpress/devextreme-angular#828]
devexteme version: 18.1.4
    devextreme-angular version: 18.1.4

[ ] bug Report

https://stackblitz.com/edit/angular-skrhrf?file=src%2Fapp%2Fapp.component.html

**This project is a small example of the problem. You can also examine the problem in the following images in detail.

https://image.ibb.co/nb3dBo/bandicam_2018_07_14_19_46_00_178.gif
https://image.ibb.co/cJryBo/bandicam_2018_07_14_19_43_10_941.gif

**Comment by hakimio** [comment]
You mean it doesn't have "smooth" scroll effect or what exactly is the problem? From what I can see, it works as expected.

**Comment by NickMitrokhin** [comment]
Hi,
 
Yes, dxScrollView operates in this manner and there is no option to change this behavior. We will consider adding an API that will help you adjust scrolling speed. 
 
If the current behavior does not meet your requirements, wrap your content in a scrollable DIV element. This is the only option we can suggest at the moment.
```HTML
<div style=" overflow-y:scroll; ...">
   ...
</div>
```
