### ISSUE TITLE
dxDataGrid doesn't invoke event handlers

### ISSUE THREAD

**Issue by SanderElias** [DevExpress/devextreme-angular#838]
**To help us process the issue more efficiently, please provide the following information:**
Angular 6.1.2, devExtreme 18.1.5

In the folowing code, the `activateRow` method is never called.
```html
<dx-data-grid [dataSource]='data' (onRowClick)="activateRow($event)">
	<dxi-column caption='Server' dataField="serverId">
		<dxo-lookup [dataSource]="servers" valueExpr='id' displayExpr="name"></dxo-lookup>
	</dxi-column>
	<dxi-column caption='Database' dataField="databaseId" [calculateDisplayValue]='getDbName(servers)'></dxi-column>
</dx-data-grid>
```

Here is an [stackblitz](https://stackblitz.com/edit/angular-fawfyc?file=src%2Fapp%2Fapp.component.html) showcasing the problem. the `onRowClick` handler is not being called. 
No errors are logged to the console. I tried also with `calculateCellValue`  

- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Also, on every event that is fired, there is a console warning:
![image](https://user-images.githubusercontent.com/1249083/44094991-f4ced2b2-9fd7-11e8-9470-0847acba8048.png)
This seems to orginate in  DevExtreme (core/dom_adapter.js) line 148 (In the version in the stack)

(1) https://stackblitz.com/edit/angular-fawfyc?file=src%2Fapp%2Fapp.component.html

**Comment by hakimio** [comment]
"onRowClick()" event seems to be firing just fine for me:
https://stackblitz.com/edit/angular-hzte8r

Can't reproduce the other issue as well.

**Comment by SanderElias** [comment]
@hakimio you took out the ` [calculateDisplayValue]='getDbName(servers)'` out of my sample.
Are you saying the stackblitz I provided works for you? And not seeing the other issue in there neither?

**Comment by SanderElias** [comment]
@hakimio Sorry, I didn't see that before I answered. I will close this issue so we can focus the conversation in #839
