### ISSUE TITLE
Issue with content re-render when switching contentTemplate in dxPopUp

### ISSUE THREAD

**Issue by amangupta17** [DevExpress/devextreme-angular#844]
I am trying to achieve this functionality: 
https://js.devexpress.com/Documentation/18_2/Guide/Widgets/Popup/Customize_the_Appearance/Customize_the_Content/#Switching_Templates_On_the_Fly

While switching templates on the go, the template content of the first selected content doesn't go away and the newly selected content template is displayed below the pre-existing content. 
Here's a sandbox replicating the issue: 
https://codesandbox.io/s/vmk25lnr9l

When you click Change the Template, it adds the the content below the old  content.

**Comment by hakimio** [comment]
Apparently it can only be changed while the popup is visible. 
Anyway, you'll have more luck if you post this issue in "DevExpress/devextreme" github page.

**Comment by ovchinnikov** [comment]
Thanks for reporting this bug. We will research it in the context of this ticket: [T669408](https://www.devexpress.com/Support/Center/Question/Details/T669408/dxpopup-renders-content-twice-after-the-contenttemplate-option-is-changed)
