### ISSUE TITLE
Performance issues in size.js

### ISSUE THREAD

**Issue by Franki1986** [DevExpress/devextreme-angular#847]
Hello,

I am not sure if this is the right place, but after analyzing my angular app with the google chrome dev tools (Performance) I have often found some rendering peeks that always point to devextreme core utils syze.js.

```
var getSizeByStyles = function(elementStyles, styles) {
    var result = 0;
    styles.forEach(function(style) {
       // problematic position...
        result += parseFloat(elementStyles[style]) || 0
    });
    return result
};

```
The message is 'Forced reflow is likely performance bottleneck'

![performance-analyzing](https://user-images.githubusercontent.com/6066590/44914822-a64f0780-ad31-11e8-9fdb-e23d8719d71e.PNG)

**Comment by hakimio** [comment]
Maybe because the function is defined and used in "DevExpress/DevExtreme" repository ([js/core/utils/size.js](https://github.com/DevExpress/DevExtreme/blob/3481c3caa6a6e8fe2d5600f447001e8cd0083ddd/js/core/utils/size.js#L3)) it would be better to open the issue there?

**Comment by ovchinnikov** [comment]
DevExtreme widgets require to calculate DOM elements sizes during rendering. That is why the size.js util is called. If you face with performance issues, please submit a [support request](https://www.devexpress.com/Support/Center/Question/Create) to our support center along with a sample project to reproduce the issue.
