### ISSUE TITLE
DX-CHART DOESN'T DISPLAY WELL INSIDE CARDS

### ISSUE THREAD

**Issue by albertomodigliani** [DevExpress/devextreme-angular#848]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version:  18.1.5
    devextreme-angular version: 18.1.5
- Specify the type of the issue (check one with "x"):
[x] bug Report 
[ ] feature request 
[ ] support inquiry 

Hi,

my company is evaluating, in order to purchase, your devextreme product for angular. 
We think that your offer is good, but I have a question. When I put a dx-chart inside a card (e.g. angular-material mat-card) the chart doesn't render itself in the boundary of the card, but is bigger or smaller basing on card initial dimesion. 
I did a workaround calling the render method on the dx-chart component in the ngAfterViewChecked lyfe cycle hook, but the performance of the application drops down. Is there another way to resolve the problem?

Thank you for the help.

Regards,
Alberto

**Comment by hakimio** [comment]
Try to put the chart in a div with the following CSS:
```css
.container {
    display: flex;
    flex-direction: column;
}
```
If that doesn't work, you'll have to play a bit with static height/width, ie: 
```
height: 100%;
height: calc(100% - 48px);
```

The problem is that most DevExtreme components don't work very well in flex CSS layouts.

Also, it would help if you could create [Stackblitz ](https://stackblitz.com) example showing the issue you are dealing with.

**Comment by ovchinnikov** [comment]
@albertomodigliani 
I see the [same ticket](https://www.devexpress.com/Support/Center/Question/Details/T669166/chart-doesn-t-display-well-inside-cards) in our Support Center that might be created by you, so I suggest you continue discussing the issue there.
