### ISSUE TITLE
Datagrid filter panel triggers a loop of calls to the db

### ISSUE THREAD

**Issue by nicolomanni** [DevExpress/devextreme-angular#858]
Hello, 

below the versions used in my app:

    @angular: 6.1
    devexteme version: ^18.1.4
    devextreme-angular version: ^18.1.4

[x] bug Report 
[ ] feature request
[ ] support inquiry

As anticipated in the title, when I activate the filter panel in a datagrid with custom remote datasource, after activating a couple of header filters, a loop of requests is sent to the db without the possibility of stopping it.

Here my datagrid configuration: 
` <dx-data-grid  #grid  [dataSource]="datasource">

      <dxo-paging [enabled]="true"></dxo-paging>
      <dxo-load-panel [enabled]="false"></dxo-load-panel>
      <dxo-filter-row [visible]="true"></dxo-filter-row>
      <dxo-header-filter [visible]="true"></dxo-header-filter>
      <dxo-filter-panel [visible]="true"></dxo-filter-panel>
      <dxo-filter-builder></dxo-filter-builder>

      <dxo-remote-operations
        [filtering]="true"
        [sorting]="true"
        [grouping]="true"
        [paging]="true"
        [summary]="true">
      </dxo-remote-operations>

      <dxo-paging [pageSize]="10"></dxo-paging>
      <dxo-pager
        [visible]="grid.dataSource._totalCount > 0"
        [showPageSizeSelector]="true"
        [allowedPageSizes]="[5, 10, 20, 50, 100]"
        [showInfo]="true"
        [showNavigationButtons]="true">
      </dxo-pager>

      <dxi-column caption="col 1" dataField="col_one"></dxi-column>
      <dxi-column caption="col 2" dataField="col_two"></dxi-column>
      <dxi-column caption="col 3" dataField="col_three"></dxi-column>
</dx-data-grid> `

**Comment by hakimio** [comment]
Can you create some simple working fiddle (ie StackBlitz)?
It might be that the way you are assigning some configs are causing Angular change detection to trigger. Does it still happen if you set `changeDetection: ChangeDetectionStrategy.OnPush` in your .component.ts?

**Comment by ovchinnikov** [comment]
Please provide me with a sample project that reproduces the issue.

**Comment by ovchinnikov** [comment]
This issue is closed because of being inactive. If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).
