### ISSUE TITLE
ODataStore does not contain all responses body

### ISSUE THREAD

**Issue by neco122** [DevExpress/devextreme-angular#871]
I'm using all the crud operations of ODataStore, but I can't catch any errors and answers content. For example  **ODataStore** "**errorHandler**" catches BadRequest, but does not include body object return. I will inform the user of the return value, but I cannot do so. Do you plan to make an update on this?

    devexteme version: 18.1.6
    devextreme-angular version: 18.1.6

[ ] bug Report 
[x ] feature request 
[ ] support inquiry

**Comment by ovchinnikov** [comment]
We have added the "errorDetails" field for an ErrorHandler argument in v18.2. See the updated documentation here https://js.devexpress.com/Documentation/18_2/ApiReference/Data_Layer/ODataStore/Configuration/#errorHandler
