### ISSUE TITLE
onUploaded event does not fire for File Uploader

### ISSUE THREAD

**Issue by cfsean** [DevExpress/devextreme-angular#877]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.4
    devextreme-angular version: 18.1.4
- Specify the type of the issue (check one with "x"):
[x ] bug Report 
[ ] feature request 
[ ] support inquiry 

Steps to reproduce

1. Configure the file uploader to upload successfully to your endpoint 
1. Bind to the uploaded event like this `(onUploaded)="onUploadSuccess()"`
1. The onUploadSuccess method is never triggered

**Please note:** Since the file uploader requires an endpoint to upload to, I have not created a sample plunker for the issue. The problem is very easy to replicate though. I have tried with many configurations for the uploader (single, multiple, instant, using buttons) and none of them seem to help the event get fired. I was even able to replicate the problem by editing the example at https://js.devexpress.com/Demos/WidgetsGallery/Demo/FileUploader/FileUploading/Angular/Light/

**Comment by ovchinnikov** [comment]
I could not reproduce the issue on my side.
![upload](https://user-images.githubusercontent.com/1101267/47360166-725fe500-d6d7-11e8-8311-921cdb22464f.gif)

**Comment by cfsean** [comment]
Apologies. Issue seems to have been my code. Thanks for your help
