### ISSUE TITLE
devextreme chart throws error on swipe

### ISSUE THREAD

**Issue by ankitr-nalkv** [DevExpress/devextreme-angular#897]
A constant error is thrown when the chart is swiped. 

**Reproduction**

- Open this link https://k1o3mzx953.codesandbox.io/ in chrome, click on the mobile view.
- Try swiping on the chart, there is a constant error, that is thrown : -

"**ERROR TypeError: Cannot read property 'tracker' of undefined**"

it uses the latest devextreme version - 18.1.6
and devextreme-angular - 18.1.6

Is there a solution for this.

![image](https://user-images.githubusercontent.com/14043700/47785166-e03a8b00-dd2d-11e8-898d-19eefd5c6ac4.png)

**Comment by alexanderPolosatov** [comment]
Hi,

We already fixed this issue in the context of this [ticket](https://www.devexpress.com/Support/Center/Question/Details/T672275/datagrid-throws-the-illegal-invocation-error-when-a-mobile-device-simulator-is-enabled).
