### ISSUE TITLE
DxDataGrid Scroll Moves Left on Width Change in RTL Environments

### ISSUE THREAD

**Issue by mohammad-matini** [DevExpress/devextreme-angular#904]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.

    devexteme version: 18.1.6
    devextreme-angular version: 18.1.6
- Specify the type of the issue (check one with "x"):
[ x ] bug Report 
[ ] feature request 
[ ] support inquiry 

## Issue Details

Given a `DxDataGrid` with `rtlEnabled: true` and long content causing inner horizontal scroll, and a page's `<html>` tag that has a `direction="rtl"`.

### Current behavior
The grid's inner horizontal scroll moves to the left when the grid's width becomes smaller.

### Expected behavior
The scroll position should stay in the same position relative to the *right* side of the grid, in contrast to LTR situations where it is relative to the left side.

## Other Notes
* Native browser elements behave as expected.
* The grid's scroll is apparently behaving as if it is in an LTR situation, where elements loose width from the right side, but on RTL elements loose width from the left.

## Reference Plunker
http://next.plnkr.co/edit/wgPqBoGPEGkVJfEj

I got a random Plunker I found and changed it to illustrate the issue. When clicking the `toggle-width` button, the grid and the native div element become narrower. Notice how the grid's first column no longer is visible (but the left side is), while the native element's scroll is still on the right side where it should be.

**Comment by DokaRus** [comment]
Hi,
I've examined this issue and reproduced it.
It is related to the `devextreme` package and can be reproduced without `devextreme-angular`.
I've created a corresponding [ticket in our Support Center](https://www.devexpress.com/Support/Center/Question/Details/T688562). You can subscribe to it to get a notification once we have any news.

**Comment by gozar33** [comment]
Hi @mohammad-matini , @DokaRus 
Did you fix this problem?
I have this issue in my project in devextreme-angular version 19.2.7 when set RTL to HTML tag, what can i do  to fix this problem ?!
