### ISSUE TITLE
DataGrid scrollbar

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#905]
**To help us process the issue more efficiently, please provide the following information:**
- Specify the version of the *devextreme-angular* and *devextreme* packages you are using.
    devexteme version: 18.1.6
    devextreme-angular version: 18.1.6
- Specify the type of the issue (check one with "x"):
[X] bug Report

We encountered a disparity in the Data Grid scrollbar. Here the two scenarios:

1) [MacOS] [Chrome]

By default, the scrollbar is visible, square-shaped and it is aside from the grid.

1) [Windows10] [Chrome]

By default, the scrollbar is hidden. When the mouse pointer goes on the area of the grid, the scrollbar shows up. In this situation the scrollbar is thin, rounded and it is not aside from the grid, but it is over it. Then if the mouse pointer goes on the scrollbar area, it gets wider and square-shaped.

It would be more consistent if the scrollbar is visible and aside from the grid, in any case. We tried with the "showScrollbar: always", but nothing changed.

**Comment by hakimio** [comment]
I can't reproduce the issue with DevExtreme 18.1.7. Data Grid scrollbars seem to be fine in Chrome running on Mac OS 10.13.6. Though they seem to be a bit buggy on Safari 12.01.

**Comment by MasDevProject** [comment]
Versione 18.1.7 resolves the issue.

I'm using `<dxo-scrolling useNative="true"></dxo-scrolling>` to make the scroolbar always visible
