### ISSUE TITLE
Path not resolved during build

### ISSUE THREAD

**Issue by a6datta** [DevExpress/devextreme-angular#910]
devexteme version: 18.2.3
devextreme-angular version: 18.2.3

I get the following errors during production build. 18.1 was working fine. I can see the files are physically in there.

ERROR in ./node_modules/devextreme-angular/ui/nested/item-dxi.js
Module not found: Error: Can't resolve './base/context-menu-item-dxi' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui\nested'
ERROR in ./node_modules/devextreme-angular/index.js
Module not found: Error: Can't resolve './core/http-request' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular'
ERROR in ./node_modules/devextreme-angular/core/integration.js
Module not found: Error: Can't resolve './http-request' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\core'
ERROR in ./node_modules/devextreme-angular/ui/vector-map.js
Module not found: Error: Can't resolve './nested/area-settings' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/circular-gauge.js
Module not found: Error: Can't resolve './nested/major-tick' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/linear-gauge.js
Module not found: Error: Can't resolve './nested/major-tick' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/range-selector.js
Module not found: Error: Can't resolve './nested/major-tick-interval' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/vector-map.js
Module not found: Error: Can't resolve './nested/marker-settings' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/chart.js
Module not found: Error: Can't resolve './nested/overlapping-behavior' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/circular-gauge.js
Module not found: Error: Can't resolve './nested/overlapping-behavior' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/linear-gauge.js
Module not found: Error: Can't resolve './nested/overlapping-behavior' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/range-selector.js
Module not found: Error: Can't resolve './nested/placeholder-size' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'
ERROR in ./node_modules/devextreme-angular/ui/range-selector.js
Module not found: Error: Can't resolve './nested/selected-range' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\ui'

**Comment by a6datta** [comment]
In 18.1.7 these are the errors. I will check with 18.1.3, i believe there were no errors on that version.

ERROR in ./node_modules/devextreme-angular/index.js
Module not found: Error: Can't resolve './core/http-request' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular'
ERROR in ./node_modules/devextreme-angular/core/integration.js
Module not found: Error: Can't resolve './http-request' in 'C:\Users\datta\Source\Repos\xxx\node_modules\devextreme-angular\core'

**Comment by nightskylark** [comment]
Hi
Which versions of Angular and Angular CLI are you using?

**Comment by a6datta** [comment]
i first tried with 6.1.10 then i upgraded to 7.0.6

**Comment by hakimio** [comment]
Everything seems to be working fine for me with DevExtreme 18.1.7 and Angular CLI 7.0.4 .
Can you create a repo on github which reproduces the issue?

**Comment by EvgenijIvanov** [comment]
Magic. I received such an error when trying to build a project with the "npm run build" command, it always worked before. But if you use - "ng build --prod", then everything is building to without problems.

**Comment by PhineasJiang** [comment]
Any news about this issue? I met the same problem with angular-devextreme 18.1.7 and angular-cli 6.0.3.

**Comment by hakimio** [comment]
@PhineasJiang if you want it fixed, create a test app which reproduces the issue. It seems to be dependent on your environment.

**Comment by cjdreiss** [comment]
Same issue here. Ng build —prod fails with 18.2.4. Works on 18.1.7. Ng build non prod works, but I need to build prod. 

Angular cli 6.0.8.

**Comment by cjdreiss** [comment]
I started a new project and couldn’t re-produce the issue... 

I finally broke down and deleted node_modules and did a fresh npm install and it works now.

I was looking at the errors that were being thrown, and those files didn’t have any requires for the ones it said couldn’t be resolved.  I’ll go instal and older version, then then new one to see if that’s somehow related.

**Comment by a6datta** [comment]
It works after I deleted node_modules and reinstalled.

**Comment by httpete** [comment]
I am seeing this after upgrading to 19.2.5.

**Comment by nicosaliagas** [comment]
> 
> 
> I am seeing this after upgrading to 19.2.5.

me too!
what's the solution?

**Comment by anikets43** [comment]
This works with 19.2.5, 
`import { DxTemplateModule } from 'devextreme-angular/core';`

should have been 
`import { DxTemplateModule } from 'devextreme-angular/core/template';`

**Comment by keserwan** [comment]
based on @anikets43 's reply,
I can confirm too it was working before v19.2.5 with this line
import { DxTemplateModule } from 'devextreme-angular/core/template';
now with version 19.2.5 we have to remove /template to let it work.
