### ISSUE TITLE
Suggestion : Add Interfaces definition files - don't use any

### ISSUE THREAD

**Issue by stonecourier** [DevExpress/devextreme-angular#92]
All the d.ts files using any for everything. This is limiting the power of typescript and means we have to keep referring back to the online documentation.

For example, I have made my own interfaces for the DxToolbar.

export interface IToolbarItemOption
{
    text : string;
    icon : string;
    onClick : Function;
}

export interface IToolbarItem
{
    toolbar : "bottom";
    location : "before" | "center" | "after";
    widget : "dxButton";
    options : IToolbarItemOption;
}

**Comment by KevinGruber** [comment]
How far is the implementation with this one?

also why is the autocompletion for your components in WebStrom not working? 
All other libraries are working.

BR,
Kevin

**Comment by dxvladislavvolkov** [comment]
Hi! In the current major version 17.2, we added new typings for components (see [#638](https://github.com/DevExpress/devextreme-angular/pull/638)). And in the upcoming version [18.1](https://github.com/DevExpress/devextreme-angular/releases/tag/v18.1.1-beta.1), we improved typings for our nested options (see [#684](https://github.com/DevExpress/devextreme-angular/pull/684))
