### ISSUE TITLE
Grid columns not aligned with the header.

### ISSUE THREAD

**Issue by sleimanrami** [DevExpress/devextreme-angular#933]
# Bug Report

**Package versions:**

    devexteme version:18.2.4
    devextreme-angular version:18.2.4
    angular version: 7.0.2

**Steps to reproduce:**

**Current behavior:**

When adding the grid inside a dx-popup and after opening the popup we populate grid with data.
The grid appears with Grid columns borders not aligned with the one of the header.
Any help will be appreciated
**Expected behavior:**

**Screenshots:**

![image](https://user-images.githubusercontent.com/19321936/52798145-02a7a880-3080-11e9-8e74-617b8b1bd6c1.png)

**Comment by AlexanderKovalenko** [comment]
Hi,

I have checked this issue using the latest version of our components: [https://codesandbox.io/s/4q554wjny9](https://codesandbox.io/s/4q554wjny9). 
Here is a sample screenshot that illustrates my results: [https://www.screencast.com/t/PfCa6kss](https://www.screencast.com/t/PfCa6kss). Do you see the same result on your side? If so, please upgrade to the latest version (18.2.6). If the issue persists, modify this sample (use the Fork button) to illustrate the glitch.

**Comment by sleimanrami** [comment]
Hi Alexander,
Thank you for your reply.
The issue has been resolved after adding the following line to my grid

<dxo-scrolling mode="standart" showScrollbar="always" scrollByContent="true"></dxo-scrolling>
