### ISSUE TITLE
dxDataGrid Infinite Scroll stops working when resized

### ISSUE THREAD

**Issue by brunoccsnasajon** [DevExpress/devextreme-angular#935]
With the following configuration:

<dx-data-grid #grid
              id="grid"
              [dataSource]="dataSource"
              [remoteOperations]="true"
              [showBorders]="false"
              [showColumnLines]="false"
              [showRowLines]="true"
              [rowAlternationEnabled]="true"
              [twoWayBindingEnabled]="false"
              height="100%">

    <dxo-load-panel [enabled]="true" [showPane]="false" text=""></dxo-load-panel>
    <dxo-scrolling mode="infinite" [preloadEnabled]="false"></dxo-scrolling>
    <dxo-paging [pageSize]="50"></dxo-paging>

    <dxi-column dataField="anoReferenciaPeriodo" caption="Período" width="05%"></dxi-column>
    <dxi-column dataField="nomeFuncionario" caption="Funcionário" width="20%"></dxi-column>
    <dxi-column dataField="descricaoConhecimento" caption="Conhecimento" width="15%"></dxi-column>
    <dxi-column dataField="inicio" caption="Início" dataType="date" [format]="{ type: 'dd/MM/yyyy' }" width="10%"></dxi-column>
    <dxi-column dataField="fim" caption="Fim" dataType="date" [format]="{ type: 'dd/MM/yyyy' }" width="10%"></dxi-column>
    <dxi-column dataField="situacao" caption="Status" width="10%"></dxi-column>
    <dxi-column dataField="nota" caption="Nota" dataType="number" width="05%"></dxi-column>
    <dxi-column dataField="evidencia" caption="Evidência" width="05%"></dxi-column>
    <dxi-column dataField="padrinho" caption="Padrinho" width="20%"></dxi-column>
</dx-data-grid>

Whenever I resize the browser (Chrome) to a smaller size, and then resize it back to a bigger size, infinite scroll stops working. The load indicator appears but the load method is not executed.

**Comment by brunoccsnasajon** [comment]
Apparently setting [preloadEnabled]="true" solves the issue, but on the other hand preloadEnabled seems to be ignoring the pagesize, calling load() twice even if the first load brings less rows than pagesize.

**Comment by ovchinnikov** [comment]
Please provide me with a sample project that reproduces the issue.

**Comment by ovchinnikov** [comment]
This issue is closed because of being inactive. If you need further assistance, post your question in our [Support Center](https://www.devexpress.com/Support/Center/Question/Create).

**Comment by VladSabre** [comment]
For people ending up here trying to find a solution for a similar issue (displayed loader with load method not called after resize or changing the size of the rows) - you just have to call `updateDimensions()` method of the grid after any changes in the size of the grid or its rows
