### ISSUE TITLE
Reactive forms documentation

### ISSUE THREAD

**Issue by JulioMaragnas** [DevExpress/devextreme-angular#949]
# Where can i find documentation about reactive forms with DevEXtreme controls ?

Hello, i started in a new project with devExtreme controls, I have used Reactive forms but i can´t found the way how to use it with angular.

somebody can help me, thanks in advance!

**Comment by hakimio** [comment]
I guess you saw the following section in the README:
https://github.com/DevExpress/devextreme-angular#angular-forms

Anyway, why not use [DevExtreme forms](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Form/Validation/Angular/MaterialTealLight/) instead?
