### ISSUE TITLE
dx-list: Web Api Paginate Missing Data

### ISSUE THREAD

**Issue by neco122** [DevExpress/devextreme-angular#950]
# Bug Report

**Package versions:**

    devexteme version: 18.2.5
    devextreme-angular version: 18.2.5

**Steps to reproduce:**

Example App *:
https://codesandbox.io/s/o488mprl2y

**Current behavior:**

If i reloaded dxlist datasource, pagination is not working perfectly.
Please open the example app and scroll buttom last page and click test button. To see that your list is missing.

**Expected behavior:**

I want the paginate to work properly.

**Screenshots:**

![Capture](https://user-images.githubusercontent.com/20782752/54461311-44119d80-477d-11e9-95bd-3b34fc8d0c61.PNG)

**Comment by hakimio** [comment]
If you call reload() on the list instance, it works as expected:
https://codesandbox.io/s/n4vy5o9v84
