### ISSUE TITLE
Adding the chat component

### ISSUE THREAD

**Issue by abelardolg** [DevExpress/devextreme-angular#954]
# Feature request
CHAT component
**Package versions you currently use:**

    devexteme version: last version
    devextreme-angular version: last version

**Description:**

A chat component is essential today in web applications.
**Preferred Solution:**

A chat located at the bottom-right corner (or wherever).
**Alternatives:**

**Comment by hakimio** [comment]
DevExpress/devextreme github page might be better suited for this kind of feature requests.

**Comment by briosheje** [comment]
I don't think this belongs to this repository.

Besides, @abelardolg what about just looking for an existing component? https://github.com/rpaschoal/ng-chat

**Comment by abelardolg** [comment]
Hi, 

I thought this site is valid for new requests too.

@briosheje , this is a new request in order so that DevExpress adds a chat component into Angular collection.

Sorry for the inconveniences.

Best regards.

**Comment by abelardolg** [comment]
@briosheje , thanks for your link.

Best regards.

**Comment by briosheje** [comment]
@abelardolg as a side note, I'm not a devexpress team member. I was just wondering how "dynamic" a chat component could be. Anyway, glad this helped. You may think about integrating devextreme widgets in that chat component, I think the result would be somewhat interesting ;).

**Comment by ovchinnikov** [comment]
Hello,

Thank you for the suggestion. This component is not in our nearest development plans. However, we are tracking all the customer requests to consider implementing it in the future. It will appear in our [Roadmap](https://js.devexpress.com/Roadmap/) once we decide to start working on it.

**Comment by 16adianay** [comment]
Hello,

We included the feature you inquired about in our plans for the upcoming major release - v24.2. You can find more details in the [DevExtreme Roadmap](https://js.devexpress.com/jQuery/Roadmap/#chat-component).

Your feedback is valuable to us as we strive to incorporate user requests throughout the development process. If you have any insights or suggestions to share, please take a moment to complete our [survey](https://www.devexpress.com/support/surveys/devextreme-roadmap-chat.xml).

Stay tuned for updates regarding the development progress. We have an Early Access Program (EAP) release scheduled for September, during which a portion of the features planned for the major release will be available for early testing. We will publish a blog post about the EAP release.

The RTM version of the major release 24.2 is planned for December.

Thank you.

**Comment by 16adianay** [comment]
Hello,

I'm happy to let you know that we introduced a new Chat component in v24.2: [New Chat Component](https://www.devexpress.com/subscriptions/whats-new/#js-chat). You can check the following demo and help topic to learn more about this component: 
- [Chat Demo](https://js.devexpress.com/Angular/Demos/WidgetsGallery/Demo/Chat/Overview/Light/)
- [Getting Started with Chat](https://js.devexpress.com/Angular/Documentation/Guide/UI_Components/Chat/Getting_Started_with_Chat/)

Please also refer to our other [JavaScript-related features](https://www.devexpress.com/subscriptions/whats-new/#devextreme) and, if time permits, leave your feedback in the [survey](https://www.devexpress.com/subscriptions/whats-new/#devextreme-survey).

Thank you. Your feedback matters to us.
