### ISSUE TITLE
ODataStore dates conversions

### ISSUE THREAD

**Issue by MasDevProject** [DevExpress/devextreme-angular#969]
# Bug Report

Hi
I'm using a devextreme DataGrid with OData and ODataStore.
Everything works fine except the dates which are showed in UTC from the grid.

Our endpoint for OData returns dates in this format: `"2019-05-15T08:19:17.158253Z"` which is **ISO 8601** and **UTC**.

It looks like dates in the store are re-converted in UTC and then in local time. In fact using a template for the date columns to print the column value, the date was moved another 2 hours back (our localtime is GTM+2).

The following is a sample response from our endpoint:
```
{
"@odata.context":"http://localhost:5000/api/audit-records?%24top=30&%24count=true",
"@odata.nextLink":"http://localhost:5000/api/audit-records?$top=0&$count=true&$skip=30",
"value":[
	{
		"id":1,
		"timestamp":"2019-05-15T08:19:17.158253Z",
		"auditAction":2,
		"entityName":"Product",
		"message":"Updated Product with id 2",
		"retailerId":null,
		"retailerName":null,
		"userId":1,
		"userName":"admin"
	}
],
"@odata.count":1
}
```

**Package versions:**

    devexteme version: 18.2.8
    devextreme-angular version: 18.2.8

**Comment by hakimio** [comment]
Have looked into [deserializeDates](https://js.devexpress.com/Documentation/ApiReference/Data_Layer/ODataStore/Configuration/#deserializeDates) and [dateSerializationFormat](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#dateSerializationFormat) configs?

**Comment by MasDevProject** [comment]
Yes, we tried both without success. In particular:

- with `deserializeDates` to false dates are displayed correctly (GMT+2) but filtering a date column will cause errors (date filters are treated like strings)

- with `dateSerializationFormat` to `"yyyy-MM-ddTHH:mm:ssZ"`, dates are still displayed as UTC and filtering a date column will cause errors like above

**Comment by hakimio** [comment]
Have to tried to set dateSerializationFormat to null?

**Comment by MasDevProject** [comment]
> Have you tried to set dateSerializationFormat to null?

@hakimio thank you. It does the trick.
So, the solution is:
`[dateSerializationFormat]="null"` in the html element
and `deserializeDates:false` into the `store` obj.

I think that this is not as clear as it should be

**Comment by LexDX** [comment]
The initial problem is resolved, so I closed the issue. As for the documentation, we will consider adding more information about serialization specifics in the future, but I can't provide you with any time frames.
