### ISSUE TITLE
/node_modules/devextreme/viz/export"' has no exported member 'exportWidgets'.

### ISSUE THREAD

**Issue by tegarjgap** [DevExpress/devextreme-angular#974]
# Support Question

Hi,. I use angular version 5 for my project, and i want to add custom export button for print multiple chart. I follow this [documentation](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/ExportSeveralCharts/Angular/Light/),  when i import this -->  **import { exportWidgets } from 'devextreme/viz/export';**

I getting error _/node_modules/devextreme/viz/export"' has no exported member 'exportWidgets'._

what wrong with that?

**Comment by tegarjgap** [comment]
devextreme + devextreme-angular version which i use
"devextreme": "18.2.7",
 "devextreme-angular": "18.2.7",

thanks

**Comment by roman-simionov** [comment]
The [exportWidget](https://js.devexpress.com/Documentation/ApiReference/Common/utils/viz/Methods/#exportWidgetswidgetInstances_options) is available since DevExtreme v19.1.

**Comment by tegarjgap** [comment]
ok thanks Mr Roman
