### ISSUE TITLE
Incorrect DxDataGrid rendering with useNative scrolling option

### ISSUE THREAD

**Issue by oledb** [DevExpress/devextreme-angular#976]
# Bug Report

**Package versions:**

    devexteme version: 19.1.3 and 18.2.9
    devextreme-angular version: 19.1.3 and 18.2.9
**Steps to reproduce:**
Horizontal and vertical scrolling is visible, useNative scrolling is true, the first column is fixed, the height of the table is set by a constant. Scroll down to the end.
[Demo](https://codesandbox.io/s/z5jk6)

**Current behavior:**

**Expected behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/9335658/59675079-354be400-91cd-11e9-9c15-911d46425e0f.png)

**Comment by hakimio** [comment]
Seems to be DevExtreme bug, not devextreme-angular wrapper. You should either create [support ticket](https://www.devexpress.com/Support/Center/) or open a bug report in [DevExtreme github page](https://github.com/DevExpress/devextreme).

**Comment by oledb** [comment]
Bug was fixed in 19.1.4
