### ISSUE TITLE
deleteRow without confirm dialog

### ISSUE THREAD

**Issue by allahyar** [DevExpress/devextreme-angular#985]
# Feature request
deleteRow without confirm dialog

**Package versions you currently use:**

    devexteme version: 19.1.5
    devextreme-angular version: 19.1.5

**Description:**
I was looking for a method that delete rows in dxDatagrid, But I didn't need to confirm dialog .
I couldn't find a solution :)

**Comment by Alyar666** [comment]
Hello @allahyar,

You need to set the [editing.texts.confirmDeleteMessage](https://js.devexpress.com/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/editing/texts/#confirmDeleteMessage) option to an empty string to achieve your goal. For example - check the https://codesandbox.io/embed/row-editing-and-editing-events-devextreme-data-grid-lcg59 example illustrating this.
