### ISSUE TITLE
dx-data-grid footer summary rounding

### ISSUE THREAD

**Issue by BobaFett58** [DevExpress/devextreme-angular#987]
# Bug Report

 ```
currencyConf: any = { type: 'currency', precision: 2, currency: 'PLN' };

<dx-data-grid>
    <dxi-column dataField="value" dataType="currency" [format]="currencyConf">
    </dxi-column>
    <dxo-summary>
         <dxi-total-item column="value" summaryType="sum">
         </dxi-total-item>
    </dxo-summary>
</dx-data-grid>
```

and the result will be:

![image](https://user-images.githubusercontent.com/16953976/62700523-76e55800-b9e2-11e9-8b46-1d1db6b4e8c5.png)

When I use the same code but with the [groupIndex]="0" it will work fine.

**Package versions:**

    "devextreme": "19.1.4",
    "devextreme-angular": "^19.1.4",

**Comment by hakimio** [comment]
Maybe you should submit this bug report on `DevExpress/devextreme` github page. Most likely here DevExtreme devs won't see it for quite some time.
