### ISSUE TITLE
Separate dx_fileuploader and the list of file you have uploaded

### ISSUE THREAD

**Issue by lowzijian** [DevExpress/devextreme-angular#998]
# Feature request

**Package versions you currently use:**

    devexteme version: 19.1.3
    devextreme-angular version:19.1.3

**Description:**
It would be best if there are detailed documentation or API reference teaching how angular 
devextreme widget 's CSS can be customized. I would like to separate the list of the files uploaded and widget for custom styling. BTW ,is it possible to customised the whole text and button in to middle ? It seems align content , align text center doesnt work at all.

**Preferred Solution:**
The expected output: 
![image](https://user-images.githubusercontent.com/40559529/66185364-bca46100-e6b1-11e9-822a-e985ef470dfb.png)

**Comment by LexDX** [comment]
Please refer to the following documentation article:
https://js.devexpress.com/Documentation/Guide/Themes_and_Styles/HTML-Based_Widgets_Customization/
and try the approaches from it to achieve your goal.
